### ISSUE TITLE
Instabug 8.0.0 Prevents Building - unescaped apostrophe in string

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#104]
I updated instabug to 8.0.0 and when I try to build my app, AAPT 2 fails with the following error:

>  java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  Output:  /home/eli/workspace/myapp/app/build/intermediates/incremental/mergeDevDebugResources/merged.dir/values-fr/values-fr.xml:137: error: unescaped apostrophe in string
  "Impossible de capturer la capture d'écran en raison d'une mémoire insuffisante".

**Comment by Korazy** [comment]
Hey @eygraber

Thanks for reaching out. This should be resolved in 8.0.1. Please feel free to reopen the issue if you run into it again :)
