### ISSUE TITLE
Instabug 8.0.1 Screws with Text Alignment

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#105]
I'm not sure what styles you guys messed with, but any `TextView` in my app that uses `textAlignment` is screwed up when using Instabug 8.0.1

If I revert to 4.15.3 then it works fine.

**Comment by rdiaa** [comment]
@eygraber Can you please update the SDK V8.0.2 and tell me if this still exists.

**Comment by eygraber** [comment]
I updated to 8.0.2 and the issue still exists.

**Comment by ahndrew** [comment]
I'm seeing the same issue

**Comment by rdiaa** [comment]
@eygraber 

Can you add the below snapshot?

1-Add the following to your  build.gradle file:
allprojects  {  
repositories {   
maven {url “https://oss.sonatype.org/content/repositories/snapshots”   
} }   
}   

2-Add the dependency to your app module:
dependencies {   
compile ‘com.instabug.library:instabug: 8.0.2.5-SNAPSHOT’   
}

**Comment by eygraber** [comment]
This appears to fix the issue.

**Comment by rdiaa** [comment]
Glad to hear that 👍

**Comment by eygraber** [comment]
Any idea when this will be released?
