### ISSUE TITLE
Where can I find an updated Changelog?

### ISSUE THREAD

**Issue by FerrariBruno** [Instabug/Instabug-Android#107]
I can't seem to find an updated Changelog. Where can I find it?

**Comment by rdiaa** [comment]
@FerrariBruno, please check the screen below.
![changelog](https://user-images.githubusercontent.com/41108492/42760562-26607512-890b-11e8-942c-93ab440eb635.png)

**Comment by FerrariBruno** [comment]
Thanks!!

**Comment by rdiaa** [comment]
My pleasure to help you :)
