### ISSUE TITLE
Crash Samsung S6 Android 6.0.1

### ISSUE THREAD

**Issue by Christophe668** [Instabug/Instabug-Android#115]
Hi, a user on our app has a crash every time she opens the app.
It seems to happen only on her device and it seems related to Instabug.
I'm using the version 8.0.3 of the library.
You will find enclosed the stacktrace I got from Crashlytics.

[bike.cowboy.app_issue_14_crash_5AE17F39024900013F87F0039383B575_DNE_0_v2.txt](https://github.com/Instabug/Instabug-Android/files/2261586/bike.cowboy.app_issue_14_crash_5AE17F39024900013F87F0039383B575_DNE_0_v2.txt)

**Comment by rdiaa** [comment]
Hi @Christophe668 , 
Thank you for reaching out, I will be investigating in the issue and get back to you as soon as I can

**Comment by Christophe668** [comment]
Since it's very blocking for that user. 
Could you help me find a workaround? I'm thinking about disabling temporarily Instabug for that device.  Is there something else I could do?

It's only happening for that specific device and occurred every time (44 times)

**Comment by rdiaa** [comment]
@Christophe668 
 After investigating I found out two things
1.  This crash happens on android version 6.0.x but actually, the stack trace from Crashlytics shows 8.0.x 
2. The stack-trace not matching 8.0.3 it matches 4.13.2 & this issue has been resolved in 4.13.3, so it should not happen on 8.0.x you just need to make sure he is on the latest version.

**Comment by Christophe668** [comment]
Hi, indeed, my bad. here's the correct stacktrace with version 8.0.3
[bike.cowboy.app_issue_66_crash_5B672D60000200014229C7177F427495_DNE_0_v2.txt](https://github.com/Instabug/Instabug-Android/files/2262564/bike.cowboy.app_issue_66_crash_5B672D60000200014229C7177F427495_DNE_0_v2.txt)

**Comment by rdiaa** [comment]
@Christophe668 
Thank you, I will check it and update you

**Comment by Christophe668** [comment]
Thank you very much!

**Comment by rdiaa** [comment]
@Christophe668 

 Please try this snapshot, it should fix your issue:

To use the snapshot:
Add these to your app-level build.gradle file to grab snapshots:


dependencies {
  Implementation 'com.instabug.library:instabug:`8.0.3.1-SNAPSHOT`'
}

repositories {
    
maven {
        
url "https://oss.sonatype.org/content/repositories/snapshots"
    
}
}

**Comment by Christophe668** [comment]
Hi, thank you for this quick fix. Will it fix the issue for that device you think? 
Unfortunately, in this case, I had to disable Instabug for now as it might be critical for the user if she has no access to the app.
Because of that, I can't give you feedback on that fix right now at least. I'll keep you informed in the future when I can integrate this fix in the app.
Thank you for your reactivity!

**Comment by rdiaa** [comment]
@Christophe668 
No, This fix will be applied on all devices not only  the device of this specific user
