### ISSUE TITLE
UI issues on Android 6.0.1 Tablet - landscape orientation

### ISSUE THREAD

**Issue by kpalczewski** [Instabug/Instabug-Android#121]
### Steps to Reproduce the Problem
After Instabug integration I open the app on Nexus 7 tablet in landscape orientation. 

### Expected Behavior
Popup should utilize whole width. background around it should be transparent with some % opacity

### Actual Behavior
Popup is squashed, background is black without opacity

### Instabug integration code
Instabug.Builder(this, "")
                    .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                    .build()
            Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
(...)
if (viewModel.shouldShowInstabugWelcome()) Instabug.showWelcomeMessage(WelcomeMessage.State.LIVE)

### SDK Version
8.0.4
### Android Version
6.0.1
### Device Model
Nexus 7
![094e174a](https://user-images.githubusercontent.com/16464271/44473950-c8f66780-a631-11e8-9426-2b8e1496ab88.jpg)

**Comment by Korazy** [comment]
Hey @kpalczewski 

Thanks for reaching out. We're currently investigating this issue, thank you for pointing it out.

**Comment by Korazy** [comment]
@kpalczewski would you be able to try this snapshot and let me know if the issue is fixed for you?
com.instabug.library:instabug:8.0.6.1-SNAPSHOT

To grab a snapshot, please add the following to your code:
repositories {
    maven {
        // TODO add this only if interested in getting SNAPSHOT releases
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

**Comment by kpalczewski** [comment]
the issue is fixed for me. thank you very much.
