### ISSUE TITLE
CrashPlugin.javajava.lang.IllegalStateException: Not allowed to start service Intent 

### ISSUE THREAD

**Issue by dharmitaepaisa** [Instabug/Instabug-Android#125]
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=/com.instabug.crash.network.InstabugCrashesUploaderService }: app is in background uid UidRecord

 SDK Version  : 8.0.6

 Android Version : API level 26

**Comment by ramiimagdi** [comment]
Hey @dharmitaepaisa,
Thank you for reaching out to us, we'll be investigating the issue you have reported and get back to you as fast as possible.
Thank you

**Comment by kamelnabil** [comment]
@dharmitaepaisa Our apologies for the delay here!
Could you please share with us the full stack trace to dive in and debug?

**Comment by ramiimagdi** [comment]
Hello again @dharmitaepaisa, we are just wondering if you were able to share the full stack trace with us so that we can investigate the issue further. Please let us know if you need any help here.

**Comment by ramiimagdi** [comment]
Hello @dharmitaepaisa, we hope you are doing great!
Please don't hesitate to reach out to us again whenever you have any questions at all. Have a great day!
