### ISSUE TITLE
InstabugSessionUploaderService Crashing on Android O

### ISSUE THREAD

**Issue by balrampandey19** [Instabug/Instabug-Android#127]
`  Caused by java.lang.IllegalArgumentException: Given work is not active: JobWorkItem{id=1 intent=Intent { /com.instabug.library.network.worker.uploader.InstabugSessionUploaderService } dcount=1}
       at android.app.job.JobParameters.completeWork(JobParameters.java:233)
       at android.support.v4.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:267)
       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:393)
       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)  `

**Comment by Korazy** [comment]
Hey @balrampandey19 

Thanks for reaching out! Would you be able to tell the SDK version of Instabug you're using?

**Comment by balrampandey19** [comment]
hi @Korazy 
I am using the latest version of Instabug SDK "instabug:8.0.3"

**Comment by balrampandey19** [comment]
Hi @Korazy 
Any update on this issue? , app crashing on Prod.

**Comment by sandys** [comment]
hi guys 
any update on this issue ?

**Comment by Korazy** [comment]
Hey all,

Apologies for the delay, we’re still trying to reproduce the issue and find a fix

**Comment by Korazy** [comment]
Hi again,

Can you please tell me if you are using JobIntentService in their apps or not. If YES, are you using any service with one of the following JOB_IDs?
0xa11 (2577)
0xa13 (2579)
0xa14 (2580)
0xa15 (2581)
0xa16 (2582)
0xa18 (2584)
0xa19 (2585)
0xa20 (2592)
0xa33 (2611)

**Comment by balrampandey19** [comment]
Hi @Korazy 

we are not using JobIntentService.

**Comment by Korazy** [comment]
Would you be able to use this snapshot? It should have the fix: **8.0.11.1-SNAPSHOT**

To be able to grab the snapshots, add the following to your code:
repositories {
    maven {
        // TODO add this only if interested in getting SNAPSHOT releases
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

**Comment by Korazy** [comment]
@balrampandey19 did it fix the issue for you?

**Comment by balrampandey19** [comment]
hi @Korazy  yes, it seems like issue fixed. thanks for support.

**Comment by Korazy** [comment]
Happy to help :)

Feel free to reach out if you have any other questions!

**Comment by paradizIscool** [comment]
@Korazy Hi, What did you change in the snapshot to fix this issue?

**Comment by Korazy** [comment]
@paradizIscool apologies for the late reply here 😅 

 You can find the details of what we did to solve this issue in particular in this blog post [here](https://medium.com/@mohamed.zak/workaround-to-solve-securityexception-caused-by-jobintentservice-1f4b0e688a26).

Please feel free to reach out to us on our support channels or here on Github if you have any questions or issues.
