### ISSUE TITLE
Can take screen recording even when declining permission

### ISSUE THREAD

**Issue by oleandre** [Instabug/Instabug-Android#132]
### Steps to Reproduce the Problem
Press Floating button to activate Instabug -> Report a problem -> Take a screen recording -> Deny 
### Expected Behavior
"Record"-icon should not become visible, and shouldn't be able to take screen recording
### Actual Behavior
"Press record when ready"-icon appears and able to record
### Instabug integration code
new Instabug.Builder(application, "")
                .setInvocationEvents(InstabugInvocationEvent.FLOATING_BUTTON)
                .setCrashReportingState(Feature.State.DISABLED)
                .setSurveysState(Feature.State.DISABLED)
                .setReproStepsState(State.DISABLED)
                .build();

### SDK Version
28
### Android Version
Android 9
### Device Model
Pixel 2

**Comment by rdiaa** [comment]
Hello @oleandre I will check it now and get back to you shortly

**Comment by rdiaa** [comment]
Hello again @oleandre 
I checked it from my side and found that it's not a bug. the permission is asking for audio permission to record audio while recording the screen, but when you declined the permission we scan to record the screen without audio. Please tell me if anything is unclear

**Comment by rdiaa** [comment]
@oleandre did you have the chance to catch my previous me. I just want to make that everything is clear to you

**Comment by rdiaa** [comment]
Hello, @oleandre I hope you are fine. If what I mentioned is not clear to you or you want to discuss it more, I will always be here to help!
