### ISSUE TITLE
Not a valid string in the French translation

### ISSUE THREAD

**Issue by saramotiv** [Instabug/Instabug-Android#134]
Hello, I just updated my gradle files to use 
```
    compileSdkVersion 28
    buildToolsVersion '28.0.3'
```
and I receiving an error while building the app:

```
/Users/xxx/.gradle/caches/transforms-1/files-1.1/instabug-core-8.0.0.aar/491c67102ad9e94c2af1336dbc1034a4/res/values-fr/values-fr.xml:101:5-147: AAPT: error: unescaped apostrophe in string
    
/Users/xxx/.gradle/caches/transforms-1/files-1.1/instabug-core-8.0.0.aar/491c67102ad9e94c2af1336dbc1034a4/res/values-fr/values-fr.xml:101:5-147: AAPT: error: not a valid string.
```

### SDK Version
   ` implementation 'com.instabug.library:instabug:8.0.0'`

**Comment by ramiimagdi** [comment]
Hey @saramotiv, thank you for reaching out to us!
Can you please try:
`implementation 'com.instabug.library:instabug:8.0.11'`

**Comment by saramotiv** [comment]
Better, cannot reproduce the error.

Thank you

**Comment by ramiimagdi** [comment]
It's definitely a pleasure @saramotiv. Have a great day 😊
