### ISSUE TITLE
Build Failure 

### ISSUE THREAD

**Issue by pouriabagheri** [Instabug/Instabug-Android#138]
### Steps to Reproduce the Problem
Upgrade to '**com.instabug.library:instabug:8.0.11**'
from '**com.instabug.library:instabug:8.0.6**'

### Expected Behavior
to build project
### Actual Behavior
failed to build project 
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
implementation 'com.instabug.library:instabug:8.0.11'
### Android Version
    compileSdkVersion 27
    buildToolsVersion '28.0.2'
    minSdkVersion 17  
    targetSdkVersion 27
### Error Log

```
Android resource linking failed
Output:  C:\Users\pc\Documents\example\app\build\intermediates\incremental\mergeBetaDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
C:\Users\pc\Documents\example\app\build\intermediates\incremental\mergeBetaDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
C:\Users\pc\Documents\example\app\build\intermediates\incremental\mergeBetaDebugResources\merged.dir\values\values.xml:1814: error: resource android:attr/fontVariationSettings not found.
C:\Users\pc\Documents\example\app\build\intermediates\incremental\mergeBetaDebugResources\merged.dir\values\values.xml:1815: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: C:\Users\pc\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\ad38307fca616a7c685d02a37a2f8a02\aapt2-3.2.0-4818971-windows\aapt2.exe link -I\
        C:\Users\pc\AppData\Local\Android\Sdk\platforms\android-27\android.jar\
        --manifest\
        C:\Users\pc\Documents\example\app\build\intermediates\merged_manifests\betaDebug\processBetaDebugManifest\merged\AndroidManifest.xml\
        -o\
        C:\Users\pc\Documents\example\app\build\intermediates\processed_res\betaDebug\processBetaDebugResources\out\resources-betaDebug.ap_\
        -R\
        @C:\Users\pc\Documents\example\app\build\intermediates\incremental\processBetaDebugResources\resources-list-for-resources-betaDebug.ap_.txt\
        --auto-add-overlay\
        --java\
        C:\Users\pc\Documents\example\app\build\generated\not_namespaced_r_class_sources\betaDebug\processBetaDebugResources\r\
        --proguard-main-dex\
        C:\Users\pc\Documents\example\app\build\intermediates\legacy_multidex_aapt_derived_proguard_rules\betaDebug\processBetaDebugResources\manifest_keep.txt\
        --custom-package\
        co.example.app\
        -0\
        apk\
        --output-text-symbols\
        C:\Users\pc\Documents\example\app\build\intermediates\symbols\beta\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #0

```

**Comment by ramiimagdi** [comment]
Hey @pouriabagheri,
Thank you for reaching out to us. Please allow me some time to check this further and get back to you as fast as possible.

**Comment by ramiimagdi** [comment]
Hello again @pouriabagheri,
I was wondering if you could give it a shot an try upgrading your compileSDK to version v28. Please let me know if you need help here.

**Comment by hussammustafa** [comment]
i am also getting this error please help to solve this issue

**Comment by Korazy** [comment]
Hey @hussammustafa 

Did you try setting your compileSDK to version v28?

**Comment by pouriabagheri** [comment]
@ramiimagdi & @Korazy yes I have tried with compileSDK to version v28 and it complies with no issues. unfortunately wont be able to use the latest SDK as we have other dependencies which won't allows us to upgrade to  v28 at this very moment

**Comment by Korazy** [comment]
Hey @pouriabagheri 

After checking, we will be unable to lower the compileSDK version, but if you would still prefer v27 or before, you can use Instabug v8.0.9 normally with those versions.

**Comment by KiranCNayak** [comment]
@Korazy I needed the link of v8.0.10 or lower (which supports build version 27). The webpage of Instabug doesn't have the support for v8.0.10, it is a 404 page. If there is any way to get this version working, it would be great. Is there any way I can specify the version of Instabug in podfile?

**Comment by mzelzoghbi** [comment]
Hey @KiranCNayak, Are you asking for android or iOS SDK?

**Comment by KiranCNayak** [comment]
It was for android actually, but we are upgrading the compileSDK version to 28, so I don't think it is required. But if you want to answer for android with v27, then please go ahead.

**Comment by mzelzoghbi** [comment]
@KiranCNayak you can grab v8.0.10 by just adding 
```
implementation 'com.instabug.library:instabug:8.0.10'
``` 
to you gradle build file. 

But we will always recommend using our latest version **8.4.0**

**Comment by KiranCNayak** [comment]
Ok, Thanks. We will be using the latest one now.
