### ISSUE TITLE
MotionEventRecognizer NullPointerException

### ISSUE THREAD

**Issue by araujotadeu** [Instabug/Instabug-Android#139]
I am getting the error message described below on Fabric.

### My code:
`
    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        InstabugTrackingDelegate.notifyActivityGotTouchEvent(ev, this);
        return super.dispatchTouchEvent(ev);
    }
`
### Error message from Fabric
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'float android.view.MotionEvent.getRawX()' on a null object reference

### Stacktrace
`
com.instabug.library.d.a.a (MotionEventRecognizer.java:65)
com.instabug.library.d.a.a (MotionEventRecognizer.java:37)
com.instabug.library.d.a$b.onFling (MotionEventRecognizer.java:286)
android.view.GestureDetector.onTouchEvent (GestureDetector.java:667)
com.instabug.library.d.a.a (MotionEventRecognizer.java:59)
com.instabug.library.tracking.c.a (InstabugTouchEventsTracker.java:44)
com.instabug.library.tracking.InstabugInternalTrackingDelegate.trackTouchEvent (InstabugInternalTrackingDelegate.java:392)
com.instabug.library.tracking.b.a (InstabugTouchEventsHandler.java:24)
com.instabug.library.InstabugTrackingDelegate.notifyActivityGotTouchEvent (InstabugTrackingDelegate.java:38)
org.stopbreathethink.app.view.activity.AbstractFragmentActivity.dispatchTouchEvent (AbstractFragmentActivity.java:158)
android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:68)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
`
### Devices / Systems
Samsung / Huawei
Android 7 and 8

### SDK version used
8.0.9

**Comment by Korazy** [comment]
Would you be able to try out this snapshot? 8.0.11.9-SNAPSHOT

To grab a snapshot, add the following as well to your code:
repositories {
    maven {
        // TODO add this only if interested in getting SNAPSHOT releases
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

**Comment by araujotadeu** [comment]
Hi @Korazy thanks for the fast answer. I can't reproduce the problem by myself ( only on production unfortunately ) I will try to reach out the specific users that had this problem and send a version of the app with the SNAPSHOT )

**Comment by Korazy** [comment]
Awesome, please let me know how it goes :)

**Comment by Korazy** [comment]
Feel free to reopen the issue should it occur again :)
