### ISSUE TITLE
Optimizing PNG assets

### ISSUE THREAD

**Issue by dirkam** [Instabug/Instabug-Android#142]
Please try to optimize the PNG images used by the SDK. Currently, these are not optimized and take up a lot of space. A simple image optimization tool could make the SDK more lightweight in a matter of minutes.

**Comment by rdiaa** [comment]
@dirkam  Thank you for your feedback, we will try to do so and I will update you

**Comment by Korazy** [comment]
@dirkam Can you please confirm the SDK version?

**Comment by dirkam** [comment]
8.0.11

**Comment by rdiaa** [comment]
@dirkam the latest version is already optimized, if you please know which PNGs that are not optimized, can you please send me the names?

**Comment by rdiaa** [comment]
@dirkam  Thank you so much for helping us with the information you provided, we used `ImageOptim` in a recent build and we will give `ImageAlpha` a try in future builds.
