### ISSUE TITLE
InstabugTrackingDelegate is removed in 8.0.12

### ISSUE THREAD

**Issue by sfseyhan** [Instabug/Instabug-Android#145]
Documentation and example code use InstabugTrackingDelegate to track touch events in activity, but it was removed in last patch version.
Example code:
https://github.com/Instabug/Instabug-Android/blob/master/app/src/main/java/com/example/instabug/BaseActivity.java

patch and minor version updates should be backwards compatible, especially if the suggested way of adding dependency is as follows:
implementation 'com.instabug.library:instabug:8+'

If this is intentional, can you provide an alternative way of tracking touch events?

**Comment by vezikon** [comment]
It wasn't intentional it was a bug. It's fixed in 8.0.13.

**Comment by sfseyhan** [comment]
Ok thanks, closing the issue.
