### ISSUE TITLE
Instabug screenshot popup is annoyingly re-shown after dismiss

### ISSUE THREAD

**Issue by anilCFLAG** [Instabug/Instabug-Android#146]
Steps to Reproduce the Problem
- instabug 8.0.13. take a screenshot and try tap outside the popup when shown. it goes for a second and reappears. 

Expected Behavior
- it should not reappear after dismiss

Actual Behavior
- it is shown again and again

SDK Version
8.0.13

Android Version
7.1.2

Device Model
Samsung Galaxy S4

**Comment by mzelzoghbi** [comment]
Hi @anilCFLAG, Thanks for reporting this. Can you please send the code you use to integrate instabug? Also, does this issue consistently occur across multiple devices or only this one?

**Comment by Nastia-SM** [comment]
I have the same issue. Even without making a screenshot. When first popup appears, it can't be dismissed. The code of integration looks like this:
```
Instabug.Builder(this, getString(R.string.instabug_key)).setInvocationEvents(
                InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT
        ).build()
```
Device: Samsung S6

**Comment by mzelzoghbi** [comment]
@Nastia-SM Thanks for reporting this. we need to know some information to be able to tackle this bug 
1. Instabug-SDK version
2. Device Android version
3. Does this happen on all devices or on this specific device?
4. If we removed SHAKE from invocation and replaced it with `FLOATING_BUTTON` did the issue still occurs?

**Comment by Nastia-SM** [comment]
@mzelzoghbi 
1) Instabug SDK version 8.0.13
2) Android version 6.0.1
3) We noticed this issue only on this device
4) Unfortunately, yes.

**Comment by mzelzoghbi** [comment]
@Nastia-SM Can you try to increase shaking threshold using this API and tell us if this will solve the issue or not?
 ```        
BugReporting.setShakingThreshold(800);
```
_Note_: `650` is the default value.

**Comment by Nastia-SM** [comment]
The problem was gone after pressing on "Suggest an improvement"

**Comment by mzelzoghbi** [comment]
I’m glad to hear that everything is working fine now! If the problem occurs again, please feel free to reopen this issue.
