### ISSUE TITLE
Screenshot deleted from Android device when bug report cancelled

### ISSUE THREAD

**Issue by adapptor-kurt** [Instabug/Instabug-Android#148]
### Steps to Reproduce the Problem
1. Configure Instabug with Instabug.invocationEvent.screenshot
2. Take a screenshot.
3. Select "Report a problem"
4. Discard the report
5. Open Photos, and see that the latest screenshot is grey.  Photos will not be able to view the screenshot because it is corrupted/deleted by Instabug.

### Expected Behavior
Screenshots that were manually taken by a user, not taken by Instabug, should remain on the device.  This is already the behaviour on iOS.

### Actual Behavior
The screenshot is corrupted/deleted by Instabug, even though Android believes it still exists.

### Instabug integration code
Android:
```
new RNInstabugReactnativePackage.Builder(BuildConfig.INSTABUG_TOKEN, MainApplication.this)
                      .setInvocationEvent("none") // Will be set in JavaScript after permissions requested at a better time
                      .build())
```

JavaScript:
```
    Instabug.startWithToken(Config.INSTABUG_TOKEN, [ Instabug.invocationEvent.screenshot ]);
    Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled);
    Instabug.setCrashReportingEnabled(false);
    BugReporting.setPromptOptionsEnabled(
      false, // chat
      true, // bug
      true // feedback
    );
```

### SDK Version
instabug-reactnative 8.0.17

### React Native, iOS and Android Versions
RN 0.56.0
Confirmed on Android O & P

### Device Model
Confirmed on HTC HTC 2PS6200 and Pixel 2

**Comment by salmamali** [comment]
@adapptor-kurt 
This issue was fixed as of version 8.1.2. Please update to the latest instabug-reactnative version.
