### ISSUE TITLE
Screen recording resets if the app requests permission or goes into the background

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#151]
As the title says, users and QA are upset when the recording stops in middle of what they want to show us.

**Comment by vezikon** [comment]
@eygraber The screen recording designed to only record inside the app, whenever the app goes to the background it stops and it attaches it to the bug report. 

As for the issue with permission requests, I couldn't reproduce this on my own. Does happen with a certain type of permission? I'm assuming that we are talking about version 8.0.14

**Comment by mzelzoghbi** [comment]
I’m glad to hear that everything is working fine now! If the problem occurs again, please feel free to reopen this issue.
