### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by mateusgrb** [Instabug/Instabug-Android#154]
Hello everyone,

I thought I'd find here releases and release notes of each sdk version, like I can see on Instabug-React-Native, Instabug-iOS and other libraries. However there's just a single release from 2015 and `CHANGELOG.md` hasn't been updated since February. Where can we find such information? It's a bit hard to keep track of what's going on.

**Comment by vezikon** [comment]
Hi @mateusgrb, we're working on automating updating the change log on the Repo at the moment so we don't miss updating it with every release. However, you find our updated change log on our dashboard.

**Comment by mzelzoghbi** [comment]
Hi @mateusgrb, currently we update the `Readme.md` , `CHANGELOG.md` and our releases with every release we do, So I'm closing this issue. Please feel free to reach out if you need anything else.
