### ISSUE TITLE
Instabug shaking is not working in samsung note8

### ISSUE THREAD

**Issue by AbdulrahmanGamal** [Instabug/Instabug-Android#156]
### Expected Behavior
Instabug feedback dialoge  shown when shaking 
### Actual Behavior
Instabug feedback dialoge not shown when shaking 

### SDK Version
SdkVersion 28
### Android Version
Android 8.0.0 API 26 
### Device Model
SM-N950F

**Comment by mzelzoghbi** [comment]
Hi @AbdulrahmanGamal, I’m closing this issue because it has been inactive for a month. 

Please reopen if you still encounter this issue with the latest version **8.0.16** 

Thank you! 😊
