### ISSUE TITLE
instabug leaking HandlerThreads

### ISSUE THREAD

**Issue by pjastrz** [Instabug/Instabug-Android#158]
### Steps to Reproduce the Problem
- go to some other application/open list of open applications
- go back to instabug enabled application
### Expected Behavior
no new HandlerThreads are created, or old ones are stopped and cleaned up
### Actual Behavior
A bunch of new HandlerThread are created, even though same already exist. For example:
`AnalyticsObserver, submit-surveys-handler, SessionProfilerHandlerThread, trimDbTablesThread`
Since `android.os.HandlerThread` have active looper it's never gc collected. Eventually after application is resumed enough times, we reach limit of file descriptors (1024), and app crashes with some variant of `unable to open database file (code 14)` or `android.system.ErrnoException: socket failed: EMFILE (Too many open files)` when we try to open database file, open socket etc.
### Instabug integration code
```
        new Instabug.Builder(application, BuildConfig.INSTABUG_TOKEN)
                .setInvocationEvents(NONE)
                .setCrashReportingState(ENABLED)
                .build();

        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
        BugReporting.setPromptOptionsEnabled(BUG, FEEDBACK);
        BugReporting.setInvocationOptions(COMMENT_FIELD_REQUIRED);
        Surveys.setThresholdForReshowingSurveyAfterDismiss(0, 0);
        BugReporting.setAttachmentTypesEnabled(true, false, false, false);
```
### SDK Version
8.0.13
### Android Version
23

**Comment by Muhammadyoussef** [comment]
Hey @pjastrz ,

We don’t have a specific date set yet but it should be released soon. We will keep you updated once it gets released, Thanks.
