### ISSUE TITLE
Screenshot feature not working with Android work profiles

### ISSUE THREAD

**Issue by ArneKoeckeritz** [Instabug/Instabug-Android#164]
Hey devs,

the screenshot invocation bug report feature is broken on some Huawei devices.
It works on my Pixel2 XL but not ony my Huawei Mate 9.

Please tell me if you need more information, help or coordinated work to find and fix the bug.

### Steps to Reproduce the Problem
Install your app with integrated instabug (configured for screenshot invocation) on a Huawei device Honor9 or a Huawei Mate 9.
Make a screenshot with hardware keys on device.

### Expected Behavior
Bug Report dialog should show up.

### Actual Behavior
Instabug report UI is not showing up.

### Instabug integration code
Instabug.Builder builder = new Instabug.Builder(pApplication, "<hidden>");
builder.setInvocationEvents(InstabugInvocationEvent.SCREENSHOT);
builder.setConsoleLogState(Feature.State.ENABLED);
builder.setInstabugLogState(Feature.State.ENABLED);
builder.setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS);
builder.setTrackingUserStepsState(Feature.State.DISABLED);
builder.build();

BugReporting.setInvocationOptions(InvocationOption.COMMENT_FIELD_REQUIRED);
BugReporting.setPromptOptionsEnabled(PromptOption.BUG);
BugReporting.setInvocationOptions(InvocationOption.EMAIL_FIELD_HIDDEN);

Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
Instabug.onReportSubmitHandler(pReport -> attachLogsAndAttributes());

Instabug.enable();

### SDK Version
8.0.16

### Android Version
Android 7.0

### Device Model
Huawei Mate 9 (MHA-L29)

**Comment by tinquoine** [comment]
I have a same issue.

**Comment by hanaamohamed** [comment]
Hello @ArneKoeckeritz, you can use this snapshot 
`implementation 'com.instabug.library:instabug:8.0.19.2-SNAPSHOT'`
Also don't forget to include the below code:
`repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}`

**Comment by ArneKoeckeritz** [comment]
I will check today.

**Comment by ArneKoeckeritz** [comment]
It's still not working with 8.0.19.2-SNAPSHOT

What is understand from the problem is that the screenshots are saved to the 'screenshot' directory of the **personal** profile even i use a app from the **work** profile. Looks like instabug cant access the personal directories, because of profile isolation.

**Comment by hanaamohamed** [comment]
Your admin need to allow sharing files across profiles, as instabug is trying to fetch the latest screenshot from your gallery or wherever your screenshot is, so if you didn't grant that permission instabug wouldn't detect any taken screenshot so it won't get invoked. 

Also is Pixel2 XL device doesn't have sharing files across profiles permission and invoke instabug anyway or it has the permission already?

**Comment by ArneKoeckeritz** [comment]
Thx. I will check and test it with my Admin.
