### ISSUE TITLE
Error in console - UserSteps with screenshots Mode is disabled error in logs

### ISSUE THREAD

**Issue by ZOlbrys** [Instabug/Instabug-Android#167]
### Steps to Reproduce the Problem
Setup Instabug and run the app

### Expected Behavior
No error reported in console

### Actual Behavior
Error reported in console
```
E/com.instabug.library.Instabug: UserSteps with screenshots Mode is disabled please contact support for further details.
```

### Instabug integration code
```
new Instabug.Builder(getApplication(), "API_TOKEN").setInvocationEvents(InstabugInvocationEvent.FLOATING_BUTTON).build();
```

### SDK Version
8.0.19

### Android Version
API 27 simulator

### Device Model
N/A

### [Optional] Project That Reproduces the Issue
https://github.com/ZOlbrys/InstabugProguardExample

**Comment by mzelzoghbi** [comment]
Hey @ZOlbrys,

Thanks for reaching out. We recently updated our terms and conditions to improve the privacy of the end users. In doing so, we disabled the visual logging features. We've also updated our SDKs to disable these particular features for the time being, which we always recommend using as it's the latest version. 

We're currently working on an updated version of the SDK that will re-enable these features while asking for users for a clear consent and acknowledgment. We expect this to be released in the next few weeks.

I’ll close this issue for now, please feel free to open it again if you need any help.
