### ISSUE TITLE
Cannot access '<init>': it is public/*package*/ in 'Builder' 

### ISSUE THREAD

**Issue by ellasaro** [Instabug/Instabug-Android#168]
Hi!

I've just added this line to my onCreate:

```
public override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        Instabug.Builder(this, "APP_TOKEN").build()
}
```

I've also tried:

```
Instabug.Builder(this, "APP_TOKEN")
                .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT_GESTURE,
                        InstabugInvocationEvent.FLOATING_BUTTON, InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT)
                .build()
```

I get this "Cannot access '<init>': it is public/*package*/ in 'Builder' "

I've added the corresponding lines to the gradle file:'

`implementation 'com.instabug.library:instabug:8+'`

Thanks!

**Comment by mzelzoghbi** [comment]
Hi @ellasaro, Thanks for reporting this. Seems that you are putting this code in the Activity, which will not work. You should put this code in your Application class. You try this and tell me if you encounter any issues.

**Comment by ellasaro** [comment]
Yes, that was it. Thank you for your prompt response.

**Comment by Ahmed-HS** [comment]
> Hi @ellasaro, Thanks for reporting this. Seems that you are putting this code in the Activity, which will not work. You should put this code in your Application class. You try this and tell me if you encounter any issues.

I have the same issue when trying to call the builder inside a dagger module is the instabug builder only a assessable from the application class 😅😆

**Comment by dstarchevskyy** [comment]
But when I try to divide my app modules and try to put Instabug config into separate module I face the same problem.
Could you please give me advice how to deal with it?
Thanks

**Comment by DiegoNovati** [comment]
> But when I try to divide my app into modules and try to put Instabug config into a separate module I face the same problem.
> 
> Cannot access '': it is package-private in 'Builder'
> 
> Could you please give me advice how to deal with it? Thanks

Same problem. We gave up using Instabug until the problem will be solved.

**Comment by mhashim6** [comment]
@dstarchevskyy, @DiegoNovati Hi!
A sample app/ code structure would be helpful to spot if there was a problem from our side.
Thanks!

**Comment by DiegoNovati** [comment]
Here is how to reproduce the problem:

1. Create a new App
2. Create a new module selecting 'Android Library'
3. Add the Instabug dependency in the gradle.build of the module
4. Create a class in the module and in the init method start Instabug (here is an example from our project):

class DataSourceAppSupport(
   private val applicationContext: Context,
) : IDataSourceAppSupport {

    init {
        Instabug.Builder(applicationContext, "xxxxxx")
            .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.FLOATING_BUTTON)
            .build()
    }
   ......
}

5. The project cannot compile with the 'package-private' error.

**Comment by mhashim6** [comment]
@DiegoNovati, @dstarchevskyy
Instead of calling `Instabug.Builder(applicationContext, "xxxxxx")`, use:
```
Instabug.Builder(application, "xxxxxx")
```

Pass the `Application` instance, not a `Context` instance. This will solve your problem. I'm closing this ticket for now, if you have further inquiries we'd be happy to help.
