### ISSUE TITLE
ERROR: Failed to resolve: com.instabug.library:instabug-survey:8.1.2.6-SNAPSHOT

### ISSUE THREAD

**Issue by paixols** [Instabug/Instabug-Android#170]
### Steps to Reproduce the Problem
Add Instabug latest version to project gradle 
Instabug Version: 8+
### Expected Behavior
Build Project
### Actual Behavior
Failed to resolve Instabug latest Snapshot
### Instabug integration code
```
implementation 'com.instabug.library:instabug:8+'
```
### SDK Version
8+

**Comment by paixols** [comment]
Currently using Version = "8.1.2" to be able to build the project.

**Comment by mzelzoghbi** [comment]
Hey @paixols , Thanks for reporting this. We updated our readme.md file with our latest version.
SNAPSHOTS always contains bug fixes made for specific cases. You should always use one of the versions that are on our [releases](https://github.com/Instabug/Instabug-Android/releases) page. 

If this SNAPSHOT was made for you so you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
    ...
}

I'll close this for now as it is not an issue, please feel free to open this thread again if you encounter this issue again.
