### ISSUE TITLE
java.lang.NoSuchMethodError on addOnTabSelectedListener

### ISSUE THREAD

**Issue by Axrorxoja** [Instabug/Instabug-Android#172]
```

Fatal Exception: java.lang.NoSuchMethodErrorNo virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in base.apk) Raw Text
--
  | com.instabug.featuresrequest.ui.d.b.e (FeaturesMainFragment.java:158)
  | com.instabug.featuresrequest.ui.custom.DynamicToolbarFragment.initViews (DynamicToolbarFragment.java:52)
  | com.instabug.library.core.ui.BaseFragment.onCreateView (BaseFragment.java:38)
  | android.support.v4.app.Fragment.performCreateView (Fragment.java:2439)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)


```
<img width="1357" alt="Screen Shot 2019-03-21 at 12 09 34 PM" src="https://user-images.githubusercontent.com/5182036/54737641-d4fbd500-4bd2-11e9-99aa-50ae91a10cc1.png">

**Comment by hanaamohamed** [comment]
Hello Axrorxoja, what android version are you using?

**Comment by Axrorxoja** [comment]
Assalom alaykum @hanaamohamed, please see the photo taken from the crashlitcs
this happens in the Android OS 26+

**Comment by hanaamohamed** [comment]
WS, Sorry i didn't mean that, I meant android support library version

**Comment by Axrorxoja** [comment]
@hanaamohamed I used android-28.0.0

**Comment by mzelzoghbi** [comment]
Hi @Axrorxoja, Would you be able to try this **SNAPSHOT** and let me know if the issue is fixed for you?

```
implementation 'com.instabug.library:instabug:8.2.0.7-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

**Comment by Axrorxoja** [comment]
okay @mzelzoghbi, thank you
