### ISSUE TITLE
Screen recording abruptly ends after 30 seconds

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#173]
I can record the screen for up to 30 seconds. After that, recording abruptly ends with no warning to the user, and takes me back to the bug reporting activity.

**Comment by msoliman** [comment]
@eygraber This is the current behavior of the screen recording. There's a limit on the recording length set at 30 seconds.

Is your concern about the fact that there's a length limit, or the experience of ending the screen recording?
