### ISSUE TITLE
Version 8.1.2 include libconstant.so to only 4 native platforms

### ISSUE THREAD

**Issue by thuutin** [Instabug/Instabug-Android#175]
### Steps to Reproduce the Problem
Build a project that depends on version 8.1.2 of the `instabug` and `instabug-with-okhttp-interceptor` artifacts. If you analyze the apk, you will see `libconstant.so` in only 4 native platforms.
<img width="526" alt="Screen Shot 2019-03-25 at 9 21 51 AM" src="https://user-images.githubusercontent.com/5516438/54891328-91111480-4edf-11e9-9bb9-3918ae77981a.png">
Version 8.0.13 does not include this library.
### Expected Behavior
If it needs to add a native library, then it would be good to support other native platforms.
### Actual Behavior
Native library is available to only 4 platforms.
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
AGP: 3.3.2
### Android Version
N/A
### Device Model
N/A

**Comment by mzelzoghbi** [comment]
Hi @thuutin, Thanks for reporting this. Looking in this [Official Documentation]( https://developer.android.com/ndk/guides/abis.html) we support 4 out of 5 ABIs & the last one's support was dropped in r17. Can you tell us what are the missing ABIs or your use-case?
