### ISSUE TITLE
crashed when using Instabug

### ISSUE THREAD

**Issue by dung90it** [Instabug/Instabug-Android#177]
### Expected Behavior
show screen Instagbug and submit issues
### Actual Behavior
crashed when open Instabug.

### Instabug integration code
  Instabug.Builder(this, WebServiceApi.INSTABUG_KEY)
                .setReproStepsState(State.DISABLED)
                .build()
        FeatureRequests.setEmailFieldRequired(false, ActionType.ADD_COMMENT_TO_FEATURE)
        BugReporting.setInvocationEvents(InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT)
        BugReporting.setOptions(Option.EMAIL_FIELD_OPTIONAL)
        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
        BugReporting.setReportTypes(BugReporting.ReportType.BUG)
        Instabug.setSessionProfilerState(Feature.State.ENABLED)
        Chats.setState(Feature.State.DISABLED)

**Comment by mzelzoghbi** [comment]
Hi @dung90it, Thanks for reporting this, can you provide us with the stack trace or a sample app with the issue?
