### ISSUE TITLE
have no record video option

### ISSUE THREAD

**Issue by hienao** [Instabug/Instabug-Android#178]
### Steps to Reproduce the Problem
After I use the sdk in my app,when I shake to report a bug,I can't see the option to choose picture or record a video ,I have invoke the code as document 
BugReporting.setAttachmentTypesEnabled(true, true, true, true);
### Expected Behavior
I can choose picture or record a video
### Instabug integration code
*Make sure to remove your app token.*
 Instabug.Builder(application, "token")
                .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)
                .build()
        Instabug.setLocale(Locale("zh", "CN"))
        CrashReporting.setState(Feature.State.DISABLED)
        BugReporting.setAttachmentTypesEnabled(true, true, true, true)
        BugReporting.setExtendedBugReportState(ExtendedBugReport.State.ENABLED_WITH_OPTIONAL_FIELDS)
### SDK Version
8.1.2
### Android Version
8.1.0
### Device Model
MI 6X
### [Optional] Project That Reproduces the Issue

**Comment by hienao** [comment]
And  some string the translation of zh_CN is error  example :instabug_str_bugreport_dismiss_cancel 
you used the Chinese Traditional ，it should be simplified Chinese

**Comment by mzelzoghbi** [comment]
Hey @hienao
Would you be able to reach out to our support team using contactus@instabug.com so that we can further investigate this issue?

**Comment by Lloyd0577** [comment]
seem problem
