### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#179]
Please update to use androidx dependencies. This library is the only thing preventing us from turning off jetifier.

**Comment by mzelzoghbi** [comment]
Hi @eygraber, Thanks for reaching out. Can you try excluding the support libraries from Instabug with turning off the jetifier and check if it will work or not?
```
implementation ('com.instabug.library:instabug:8.2.0')  {
       exclude module: 'support-v4'
}
```

**Comment by eygraber** [comment]
I had to do

```
implementation("com.instabug.library:instabug:8.5.0") {
  exclude group: "com.android.support"
}
```
