### ISSUE TITLE
Show touches in screen recording

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#180]
Is there any way to show screen touches while recording the screen (without the user needing to do anything)?

**Comment by Korazy** [comment]
Hey @eygraber 

Thanks for reaching out! While we currently don't support this particular feature, I'd love to know why this would be particularly useful as opposed to the user steps for example. Wouldn't the user steps feature fulfill the same use case?

**Comment by eygraber** [comment]
It's nice to be able to watch the video and see what's happening without having to also look at the user steps.

**Comment by Korazy** [comment]
Thank you very much for the feedback, I will definitely be communicating that with the product team to take into consideration for future releases :)
