### ISSUE TITLE
Shake Not Working on Certain Devices

### ISSUE THREAD

**Issue by StuStirling** [Instabug/Instabug-Android#185]
### Steps to Reproduce the Problem

Shake the device.

### Expected Behavior

The bug report dialog should display

### Actual Behavior

Nothing happens

### Instabug integration code

```
            if (!Instabug.isBuilt()) {
                Instabug.Builder(application, BuildConfig.INSTABUG_KEY)
                        .setInvocationEvents(InstabugInvocationEvent.SHAKE)
                        .build()
            }
            Instabug.setDebugEnabled(true)
            Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
            CrashReporting.setState(Feature.State.DISABLED)
```

### SDK Version

`8.2.2`

### Android Version

9.0 
Target SDK - 28
Compile SDK - 28

### Device Model

One Plus 6T
Huawei P20

### Other Info

Seems to work on a Samsung S8 Android 9.0

Adding the floating button invocation method works. It's just the shake isn't triggering the dialog. I have tried modifying the threshold but that doesn't work either and the default threshold has always been fine.

Nothing appears in the debug logs to indicate the shake is triggered. The debug logs remain empty when shaking the device.

**Comment by StuStirling** [comment]
This is similar to #156 but not limited to Samsung Note 8

**Comment by mzelzoghbi** [comment]
Hi @StuStirling, Thanks for reporting this.
Is the integration code written in the Application, or in Activity class?

**Comment by StuStirling** [comment]
Hi @mzelzoghbi this is being instantiated in the `Application`.

**Comment by mzelzoghbi** [comment]
Hi @StuStirling, we tested it on One Plus 6T Android 9 and it worked fine if you can reproduce the issue on a sample app, it will be great to share it with us.

**Comment by hanaamohamed** [comment]
@StuStirling, I'm closing this issue since it's been inactive for a month, also you can update to our latest version 8.4.0 and feel free to reopen it if you could reproduce it in a sample app
