### ISSUE TITLE
Memory leaked

### ISSUE THREAD

**Issue by gchouhan-systango** [Instabug/Instabug-Android#192]
Hi thanks for providing this great bug reporting library. I integrated in one of project and it leaks memory, Currently I am using this library version

>  implementation 'com.instabug.library:instabug:8.2.2'

Please check with screenshot and please let me know if any solution for this

![image](https://user-images.githubusercontent.com/48754695/56901542-07dc9700-6ab6-11e9-832a-18616469918c.png)

![image](https://user-images.githubusercontent.com/48754695/56901583-2347a200-6ab6-11e9-9703-eade4c3441b5.png)

**Comment by Muhammadyoussef** [comment]
Hi @gchouhan-systango 

Thanks for reaching out. We have a fix planned for release specifically for this issue. This fix should be released within the coming weeks.

Until then, I've created a snapshot for you to use with the fix. The snapshot version is: `8.2.2.14-SNAPSHOT`

Please feel free to reopen the issue if it still occurs :)

**Comment by gchouhan-systango** [comment]
Thanks @Muhammadyoussef , I will check with this new version, I will let you know if leak still occur
