### ISSUE TITLE
Welcome message is displayed despite it being disabled in code

### ISSUE THREAD

**Issue by mateusgrb** [Instabug/Instabug-Android#193]
### Steps to Reproduce the Problem
1. Disable Instabug welcome messages with `Instabug.showWelcomeMessage(WelcomeMessage.State.DISABLED)`
2. Run that app for the 1st time(or clear data before).

### Expected Behavior
No welcome message is displayed.

### Actual Behavior
Welcome message is displayed(`We are always happy to hear your thoughts...`)

### Instabug integration code
```
        new Instabug.Builder(this, TOKEN,
                InstabugInvocationEvent.SHAKE)
                .setConsoleLogState(Feature.State.ENABLED)
                .setTrackingUserStepsState(Feature.State.ENABLED)
                .setInstabugLogState(Feature.State.ENABLED)
                .setInAppMessagingState(Feature.State.DISABLED)
                .build();
        BugReporting.setShakingThreshold(400);
        Instabug.showWelcomeMessage(WelcomeMessage.State.DISABLED);
```

### SDK Version
8.3.0

### Android Version
8.1

### Device Model
Nexus 6P

**Comment by Muhammadyoussef** [comment]
Hi @mateusgrb , we are sorry for this inconvenience.
`Instabug.showWelcomeMessage(..)` is intended only for [showing welcome message manually](https://docs.instabug.com/docs/android-onboarding-experience#section-showing-the-welcome-message-manually) either in live or in beta. To [set welcome message mode](https://docs.instabug.com/docs/android-onboarding-experience#section-setting-the-welcome-message-mode) to disabled you should use `Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)`.

Please let me know if you still encounter this issue.

**Comment by mateusgrb** [comment]
@Muhammadyoussef thanks, that did it for me.
