### ISSUE TITLE
Surveys.getAvailableSurvey() returns unavailable surveys on Android.

### ISSUE THREAD

**Issue by tedcurrent** [Instabug/Instabug-Android#199]
Now I'm a bit unsure if this is due to `Instabug-React-Native` package or if it's an Instabug Android SDK issue. If it's an SDK issue, I would love a confirmation. This seems to work as expected on iOS.

### Steps to Reproduce the Problem
1. Create a single new survey with frequency set to "only once for each user"
2. Open survey with `Surveys.showSurveyIfAvailable()` if `Surveys.setAutoShowingEnabled(false)`
3. Dismiss survey without filling it in
4. Call `Surveys.getAvailableSurveys(surveys => console.log(surveys))`

#### Alternative
1. Create a single new survey with frequency set to "only once for each user"
2. Call `Surveys.getAvailableSurveys(surveys => console.log(surveys))`
3. Pause the survey from Instabug
4. Restart the app 
5. Call `Surveys.getAvailableSurveys(surveys => console.log(surveys))`

### Expected Behavior
Should return an empty array

### Actual Behavior
Returns an array with the unavailable survey

### Instabug integration code
```
const initInstabug = () => {
  Instabug.startWithToken(EnvConfig.INSTABUG_TOKEN, [
    EnvConfig.INSTABUG_SHOW_BUTTON
      ? Instabug.invocationEvent.floatingButton
      : Instabug.invocationEvent.none
  ])

  const deviceId = `${DeviceInfo.getUniqueID()}::${DeviceInfo.getModel()}`

  Instabug.setUserAttribute('Device Identifier', deviceId || 'unknown')

  Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled)

  if (!EnvConfig.INSTABUG_SHOW_BUTTON) {
    Instabug.setEnabledAttachmentTypes(false, false, false, false)
  }

  Chats.setEnabled(false)
  BugReporting.setEnabled(true)
  Replies.setEnabled(true)

  Surveys.setEnabled(true)
  Surveys.setAutoShowingEnabled(false)

  Surveys.getAvailableSurveys(surveys => {
    console.warn(surveys)
  })
}
```
### SDK Version

`"instabug-reactnative": "^8.4.0"`

### React Native, iOS and Android Versions
`Android 8.1.0`
`React Native 0.59.9`

**Comment by mzelzoghbi** [comment]
Hello @tedcurrent , This issue has been fixed in recent version 8.7.2, Please let us know if you encountered any other issues.

Thank You!
