### ISSUE TITLE
java.lang.IllegalArgumentException: the bind value at index 1 is null

### ISSUE THREAD

**Issue by dqtdev** [Instabug/Instabug-Android#200]
**Steps to Reproduce the Problem**
I've got this issue from Crashlytics report so there's no way to reproduce the problem

**Expected Behavior**
Show Instabug screen

**Actual Behavior**
App crashed

**Instabug integration code**
`Instabug.Builder(this,Constants.TOKEN_INSTABUG).setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT).build()
BugReporting.setShakingThreshold(300)
Chats.setState(Feature.State.DISABLED)
FeatureRequests.setState(Feature.State.DISABLED)
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
Instabug.setColorTheme(InstabugColorTheme.InstabugColorThemeDark)
Instabug.setPrimaryColor(resources.getColor(R.color.color_instabug))
Instabug.Builder(this, WebServiceApi.INSTABUG_KEY)
.setReproStepsState(State.DISABLED)
.build()
`

**SDK Version:** 8.2.2
**Android Version:** 8.0.0
**Device:** Samsung Galaxy S7

**Stack trace**
android.database.sqlite.SQLiteProgram.bindString + 192 (SQLiteProgram.java:192)
android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings + 228 (SQLiteProgram.java:228)
android.database.sqlite.SQLiteDirectCursorDriver.query + 47 (SQLiteDirectCursorDriver.java:47)
android.database.sqlite.SQLiteDatabase.rawQueryWithFactory + 1746 (SQLiteDatabase.java:1746)
android.database.sqlite.SQLiteDatabase.queryWithFactory + 1593 (SQLiteDatabase.java:1593)
android.database.sqlite.SQLiteDatabase.query + 1464 (SQLiteDatabase.java:1464)
android.database.sqlite.SQLiteDatabase.query + 1632 (SQLiteDatabase.java:1632)
**com.instabug.library.internal.storage.cache.db.SQLiteDatabaseWrapper.query + 129 (SQLiteDatabaseWrapper.java:129)
com.instabug.library.internal.storage.cache.user.a.a + 56 (UserDbHelper.java:56)
com.instabug.library.internal.storage.cache.user.UserCacheManager.getUserSessionCount + 15 (UserCacheManager.java:15)
com.instabug.library.user.b$3.run + 173 (UserManager.java:173)**
java.util.concurrent.ThreadPoolExecutor.runWorker + 1162 (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run + 636 (ThreadPoolExecutor.java:636)
**com.instabug.library.util.threading.b$1.run + 28 (PriorityThreadFactory.java:28)**
java.lang.Thread.run + 764 (Thread.java:764)

**Comment by amrbrkt** [comment]
Hi @dqtdev 
Thanks for reporting this.  
Would you please let me know if you are using any other Instabug APIs such as `identifyUser(Sting, String)`

Also, I've noticed in your **Instabug integration code** that you're Initializing Instabug through the builder twice;

```
Instabug.Builder(this, Constants.TOKEN_INSTABUG)
.setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)
.build()
```
and 
``` 
Instabug.Builder(this, WebServiceApi.INSTABUG_KEY) 
.setReproStepsState(State.DISABLED) 
.build()
```
Would you please share with me the use case that requires this implementation, that might help me to identify the rootcause of the issue. 
Thank you.

**Comment by dqtdev** [comment]
Hi @amrbrkt 

I've checked source code and found that `identifyUser(String, String)` is used. The guy implements the integration code has fixed the twice initialization. Is there any problems when using `identifyUser(String, String)`?

**Comment by amrbrkt** [comment]
@dqtdev 

Absolutely there is no problem using the `API`, just trying to get more insights about your implementation, that might help in tracking the issue. 

So, after fixing the initialization, still facing the same issue?

**Comment by raymondctc** [comment]
We have this issue too, SDK version 8.4.0
```
2019-07-04 10:20:51.167 23118-23195/? E/AndroidRuntime: FATAL EXCEPTION: Thread-9
    Process: com.ninegag.android.app, PID: 23118
    java.lang.IllegalArgumentException: the bind value at index 1 is null
        at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
        at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:49)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1255)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1126)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1294)
        at com.instabug.library.internal.storage.cache.db.SQLiteDatabaseWrapper.query(SourceFile:129)
        at jfg.a(SourceFile:56)
        at com.instabug.library.internal.storage.cache.user.UserCacheManager.getUserSessionCount(SourceFile:15)
        at jho$3.run(SourceFile:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at jhw$1.run(SourceFile:28)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by mzelzoghbi** [comment]
Hi @raymondctc, We tried to reproduce the issue but we couldn't, Is this happening on all devices/configurations or on a specific device?

**Comment by raymondctc** [comment]
I am not sure yet, but I found some crash logs in Crashlytics related to this.
![Screenshot 2019-07-31 at 10 34 52 AM](https://user-images.githubusercontent.com/13764117/62179363-e1f9b380-b37e-11e9-83fe-f81129631b70.png)

**Comment by amrbrkt** [comment]
Hi @raymondctc 
Please update to the recent version 8.6.3 and let'us know if the issue still exists. 
Thank You
