### ISSUE TITLE
Sends a black screen when trying to attach a screenshot

### ISSUE THREAD

**Issue by dimmetrius** [Instabug/Instabug-Android#204]
### Steps to Reproduce the Problem
When trying to attach a screenshot of flutter application sends a black screen

### Instabug integration code
android/app/build.gradle

```gradle
    defaultConfig {
        ...
        minSdkVersion 21
        targetSdkVersion 28
        multiDexEnabled true
        ...
    }
```

add to build.gradle
```gradle
implementation 'com.instabug.library:instabug:8.5.0'
```

created a new Java class that extends FlutterApplication and add it to AndroidManifest.xml.

```java
public class CustomFlutterApplication extends FlutterApplication {
    @Override
    public void onCreate() {
        super.onCreate();
        new Instabug.Builder(CustomFlutterApplication.this, "XXXXXX")
                .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)
                .build();
        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);

        CrashReporting.setState(Feature.State.DISABLED);
        BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK);
    }
}
```

### Android Version
Android 5.1 Lollipop
### Device Model
Meizu m3 Note,

**Comment by mzelzoghbi** [comment]
Hey @dimmetrius, Thanks for reporting this. Can you please try to use this API and tell us if everything worked?
```
BugReporting.setScreenshotByMediaProjectionEnabled(true);
```

**Comment by dimmetrius** [comment]
Hey @mzelzoghbi. The latest Instabug build doesn't have the black screen anymore. Instead it always attaches the first screenshot, even though user attaching different screenshots.

**Comment by amrbrkt** [comment]
Hi @dimmetrius, would you elaborate more? explain what exactly is happening? do you have reproducing steps? 
Also, would you enable Instabug debug-logs by calling `Instabug.setDebugEnabled(true)` after the initialization code, send us the logs.

**Comment by amrbrkt** [comment]
Hello @dimmetrius , 
I'll close this issue for now, please don't hesitate to get back to us if you still facing it in our recent version `8.6.3`
