### ISSUE TITLE
SQLiteDatabaseWrapper application fatal error

### ISSUE THREAD

**Issue by paixols** [Instabug/Instabug-Android#206]
### Steps to Reproduce the Problem
- Shown on Firebase Crashlytics logs

### Expected Behavior
- The application should not crash when submitting an Instabug Report

### Actual Behavior
- Application crashing when submitting Instabug Report

### Instabug integration code
- Instabug Internal Error

### SDK Version
com.instabug.library:instabug:8.5.0

### Android Version
 8.0.0

### Device Model
moto e5 play

### Error Logs
```

com.instabug.library.internal.storage.cache.db.SQLiteDatabaseWrapper.beginTransaction (SQLiteDatabaseWrapper.java:46)
com.instabug.library.logging.a.b (InstabugLogDbHelper.java:90)
com.instabug.library.logging.a.a (InstabugLogDbHelper.java:32)
com.instabug.library.logging.a$1.a (InstabugLogDbHelper.java:59)
com.instabug.library.logging.a$1.onNext (InstabugLogDbHelper.java:43)
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal (ObservableObserveOn.java:200)
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run (ObservableObserveOn.java:252)
io.reactivex.internal.schedulers.ScheduledRunnable.run (ScheduledRunnable.java:66)
io.reactivex.internal.schedulers.ScheduledRunnable.call (ScheduledRunnable.java:57)
```

**Comment by amrbrkt** [comment]
Thanks @paixols for reporting this, we will take care of it and come back to you ASAP.

**Comment by mzelzoghbi** [comment]
Hey @paixols We tried to reproduce the issue but we can't, Is this happening all the time or on a specific device? It will be also great to share with us a sample project if possible.

**Comment by falvick** [comment]
I also experienced that issue on two devices: HUAWEI/WAS-LX1 (API 28) and Xiaomi/Redmi 7 (API 24)

Steps to reproduce are as following:
Instabug is not opened. User puts app in background and resumes it multiple times.
