### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError Failed to allocate a 87085764 byte allocation with 16777216 free bytes and 41MB until OOM

### ISSUE THREAD

**Issue by markokatic0001** [Instabug/Instabug-Android#207]
### **Version of SDK**: 

- 'com.instabug.library:instabug:8.4.0'

### **Operating systems**: 

- 9, 

- 7

### **Device models:** 

- OnePlus A6000, 

- OnePlus 3T, 

- Xiaomi Redmi Note 4, 

- Samsung Galaxy S8

### **Crashlytics log:**
`
  java.lang.StringFactory.newStringFromBytes + 79 (StringFactory.java:79)
  | java.lang.StringFactory.newStringFromBytes + 207 (StringFactory.java:207)
  | okio.Buffer.readString + 631 (Buffer.java:631)
  | okio.Buffer.readString + 614 (Buffer.java:614)
  | com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.populateNetworkResponse + 260 (InstabugOkhttpInterceptor.java:260)
  | com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.intercept + 83 (InstabugOkhttpInterceptor.java:83)
  | okhttp3.internal.http.RealInterceptorChain.proceed + 147 (RealInterceptorChain.java:147)
  | okhttp3.internal.http.RealInterceptorChain.proceed + 121 (RealInterceptorChain.java:121)
  | okhttp3.logging.HttpLoggingInterceptor.intercept + 144 (HttpLoggingInterceptor.java:144)
  | okhttp3.internal.http.RealInterceptorChain.proceed + 147 (RealInterceptorChain.java:147)
  | okhttp3.internal.http.RealInterceptorChain.proceed + 121 (RealInterceptorChain.java:121)
  | okhttp3.RealCall.getResponseWithInterceptorChain + 200 (RealCall.java:200)
  | okhttp3.RealCall$AsyncCall.execute + 147 (RealCall.java:147)
  | okhttp3.internal.NamedRunnable.run + 32 (NamedRunnable.java:32)
  | java.util.concurrent.ThreadPoolExecutor.runWorker + 1133 (ThreadPoolExecutor.java:1133)
  | java.lang.Thread.run + 760 (Thread.java:760)
`

**Comment by amrbrkt** [comment]
Hi @markokatic0001, Thanks for sharing this with us, we will work on it and notify you once we are done. Thanks 🙏

**Comment by mzelzoghbi** [comment]
Hi @markokatic0001, This issue has been fixed in recent SDK versions. Please reopen if you still encounter this issue with the latest version **8.5.0**. Thank you! 😊

**Comment by markokatic0001** [comment]
@mzelzoghbi @amrbrkt Thank you very much!
