### ISSUE TITLE
Screen Recorder Crash in Android 9

### ISSUE THREAD

**Issue by jjnino** [Instabug/Instabug-Android#210]
Hello! Looking some help with this. Thanks in advance.
### Steps to Reproduce the Problem

Screen Recording on Android 9 crashes the app with `java.lang.IllegalAccessError
ScreenRecorder.java line 7 in f.<init>()`

### Expected Behavior

Screen recording should not crash the application.

### Actual Behavior

The whole app crashes.

com.instabug.library.internal.video.a.f.<init> | ScreenRecorder.java:7
1 | com.instabug.library.internal.video.q.<init> | ScreenRecordingSession.java:17
2 | com.instabug.library.internal.video.ScreenRecordingService.onStartCommand | ScreenRecordingService.java:7

MESSAGE
Illegal class access: 'com.instabug.library.internal.video.a.f' attempting to access 'com.instabug.library.internal.video.q$i' (declaration of 'com.instabug.library.internal.video.a.f' appears in xxxx.apk)

### Instabug integration code
Instabug.Builder(this, ******)
                    .setInvocationEvents(InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT)
                    .setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS)
                    .build()

Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
        BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK)
        BugReporting.setOptions(Option.EMAIL_FIELD_OPTIONAL, Option.EMAIL_FIELD_HIDDEN)
        Chats.setState(Feature.State.DISABLED)

### SDK Version

8.5.0.3-SNAPSHOT //needed for another issue but, happening on 8.5.0 as well

### Android Version
9
### Device Model
Pixel 2

**Comment by jjnino** [comment]
Seems to be addressed with 8.5.0.8-SNAPSHOT

**Comment by mzelzoghbi** [comment]
Hi @jjnino, Thanks for reporting this. We tried to reproduce the issue but we couldn't. We are happy to hear that your issue has been solved, but we didn't address the issue in **8.5.0.8-SNAPSHOT** it may be a caching issue with the dex files or android studio build files. Can you make a clean build on **8.5.0.3-SNAPSHOT** and let us know if the issue still persists? 

Thank You!

**Comment by jjnino** [comment]
Thanks for looking into it. We are going to investigate more then on our end. Going to close for now.
