### ISSUE TITLE
Welcome message screen - "Done" button is not focusable on TV

### ISSUE THREAD

**Issue by jimmy0251** [Instabug/Instabug-Android#213]
### Steps to Reproduce the Problem
- Initialize Instabug SDK and disable welcome message state to `DISABLED`.
- Show Instabug welcome message beta dialog later
```
Instabug.showWelcomeMessage(WelcomeMessage.State.BETA)
```
### Expected Behavior
Dialog is TV friendly and "Done" button can be focused
### Actual Behavior
"Done" button can not be focused
### Instabug integration code
```
Instabug.Builder()
        .setInvocationEvents(
                InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT)
        .build()
BugReporting.setOptions(Option.EMAIL_FIELD_OPTIONAL)
BugReporting.setOnInvokeCallback {
        Instabug.addFileAttachment(Uri.fromFile(logs), logs.name)
}
BugReporting.setExtendedBugReportState(ExtendedBugReport.State.ENABLED_WITH_OPTIONAL_FIELDS)
Chats.setState(Feature.State.DISABLED)
Instabug.setPrimaryColor(ContextCompat.getColor(context, R.color.colorPrimary))
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
CrashReporting.setState(Feature.State.DISABLED)
```
### SDK Version
8.5.0
### Android Version
ALL versions
### Device Model
ALL TV devices

**Comment by mzelzoghbi** [comment]
Hi @jimmy0251, Thanks for reporting this. We'll be looking into this issue.

**Comment by amrbrkt** [comment]
Hi @jimmy0251 
We don't support TVs officially yet, however, we tried to fix this issue and ship a snapshot for you. 

To use the snapshot, please add these to your app-level build.gradle: 

```
dependencies {
  compile 'com.instabug.library:instabug:8.6.1.4-SNAPSHOT'
}
```

```
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by amrbrkt** [comment]
I'll close this issue for now, please don't hesitate to get back to us if you still facing it in the snapshot. Also, this fix will be shipped in our next release in a couple of weeks.
