### ISSUE TITLE
Instabug is hanging the app on the first fresh load

### ISSUE THREAD

**Issue by e55o** [Instabug/Instabug-Android#221]
### Steps to Reproduce the Problem

We are currently using Instabug-reactnative v. 8.4.2
On android and when you freshly install the app for the first time, the instabug thread is hanging on `Allow <APP_NAME> to access you media`, if you do not click on `Allow` or `Deny` within 2 seconds, the main thread of the app is hanging, you need to kill the process and open the app again. (it stays on the launch screen, the bundle does not continue loading)

### Expected Behavior
The app should load normally from the first shot, after a fresh install.

### Actual Behavior
The app hangs on the launch screen and you need to kill it and open it again to run

### Instabug integration code

In  `App.js` `constructor`, thats what has been used
```
Instabug.startWithToken('<TOKEN>', [
      Instabug.invocationEvent.shake,
    ]);
```

### SDK Version

V.8.4.2

### React Native, iOS and Android Versions
Tested on Android version 8 & 9, on iOS there is no issues

### Device Model

This is happening on all android devices

**Comment by AliAbdelfattah** [comment]
Fixed in Android v8.6.2 and in React Native v8.6.2.
