### ISSUE TITLE
Swipe left does not work

### ISSUE THREAD

**Issue by Galiza** [Instabug/Instabug-Android#222]
### Steps to Reproduce the Problem
Just follow documentation.

### Expected Behavior
Swiping left with two finger should open the report popup.

### Actual Behavior
Shake works fine, but swiping left with two fingers **does** not open the popup.

### Instabug integration code
```
  @Override
    public void onCreate()
    {
        new Instabug.Builder(this, "APP_TOKEN")
        .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT)
        .build();
        BugReporting.setFloatingButtonEdge(InstabugFloatingButtonEdge.LEFT);
        BugReporting.setFloatingButtonOffset(250);
        Instabug.setPrimaryColor(Color.parseColor("#1D82DC"));
        super.onCreate();
    }
```

**Comment by mzelzoghbi** [comment]
Hey @Galiza , Thanks for reporting this, can you tell us which SDK version you are using?

**Comment by Galiza** [comment]
Hey @mzelzoghbi, thanks for the fast response!
We use the minSDK 21, and the targetSDK 26.

**Comment by mzelzoghbi** [comment]
@Galiza sorry i didn't clarify, Instabug SDK Version please?

**Comment by Galiza** [comment]
@mzelzoghbi Right, I'm using 8.2.1

**Comment by mzelzoghbi** [comment]
@Galiza please let me check that and get back to you

**Comment by Galiza** [comment]
@mzelzoghbi Ok! Thank you very much!

**Comment by AliAbdelfattah** [comment]
Hi @Galiza, this's been fixed in the latest Android version however we're still working on updating Cordova. For the meantime, here's how you can fix it:

In your `MainActivity` class, override the `dispatchTouchEvent` function as follows:
```
import android.view.MotionEvent;
import com.instabug.library.InstabugTrackingDelegate;
...
    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        InstabugTrackingDelegate.notifyActivityGotTouchEvent(ev, this);
        return super.dispatchTouchEvent(ev);
    }
```

I'll close the issue for now, but please feel free to reopen it if you need to discuss it further.

**Comment by Galiza** [comment]
@AliAbdelfattah Hi, thank you so very much for the help!
But as I stated, this might not work for us, since we use Cordova for both Android and iOS, so we don't really use `Activities` .

Why can't we use Android like the iOS for the Cordova version?
I mean like this:
```
cordova.plugins.instabug.activate(
    {
        ios: 'MY_IOS_TOKEN'
    },
    'shake',
    {
        commentRequired: true,
        colorTheme: 'dark'
    },
    function () {
        console.log('Instabug initialized.');
    },
    function (error) {
        console.log('Instabug could not be initialized - ' + error);
    }
);
```
But with Android, otherwise, we have to have one code in the TypeScript/JavaScript and the other with Java.
