### ISSUE TITLE
Instabug leaks Activity after device locked and unlocked quickly

### ISSUE THREAD

**Issue by AlexWih** [Instabug/Instabug-Android#223]
Issue is observed on Huawei P30 with Android 9.0 onboard.
We have an application with VOD streaming functionality: mobile app operates in portrait mode, but when user opens player screen - orientation is changed to LANDSCAPE.

### Steps to Reproduce the Problem
1. Start the app
2. Open the screen with player -> orientation changed to landscape
3. Lock the device and immediately unlock it -> memory leak occurs and LeakCanary reports it.

### Expected Behavior
No memory leak.

### Actual Behavior
Hosting Activity gets leaked.

### Instabug integration code
Actually I preparted demo app which allows to reproduce leak extremely esely - https://github.com/AlexWih/InstabugMemoryLeak

Here we have an `MainActivity` which gets leaked and `Fragment1` which mimics the behaviour of VOD streaming screen. 
The instabug integration code also can be found here - `InstabugConfiguration`.

### SDK Version
Api 29

### Android Version
Android 9.0 

### Device Model
Huawei P30

### [Optional] Project That Reproduces the Issue
https://github.com/AlexWih/InstabugMemoryLeak

### Additional info
Actially Android fraemwork behaves quite weird in this scenario as well, when user locks and unclocks device very quickly for some reason the `Fragment1` get re-created in default PORTRAIT orientation and then re-created once again in LANDSCAPE orientation.

If user locks the device and unlocks it with some delay the `Fragment1` is not re-created in PORTRAIT orientation and memory leak doesn't occur

**Comment by AlexWih** [comment]
Here is the screenshot from memory leak report for the demo app:
![image](https://user-images.githubusercontent.com/3289717/64014001-bc9cc880-cb29-11e9-9827-37e222a54959.png)

**Comment by AlexWih** [comment]
BTW, memory leak is also provable without Leak canary lib - the `finalize()` method is not called for Activity, but the Activity shouled be eligible for GCion.

**Comment by amrbrkt** [comment]
Hello @AlexWih 
I'd like to thank you very much for that report. We will take care of that and let you know once a fix is released.

**Comment by mzelzoghbi** [comment]
Hello @AlexWih,
This should be fixed on the latest release `9.0.3`, Please let us know if you faced any other issues.

Thank You
