### ISSUE TITLE
Attempt to invoke virtual method 'int com.instabug.bug.model.a.i()'

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/Instabug-Android#230]
```
java.lang.NullPointerException Attempt to invoke virtual method 'int com.instabug.bug.model.a.i()' on a null object reference 
    BaseReportingFragment.java:534 com.instabug.bug.view.reporting.b$15.run
    BaseReportingFragment.java:588 com.instabug.bug.view.reporting.b.a
    BaseReportingFragment.java:531 com.instabug.bug.view.reporting.b.onClick
    View.java:7356 android.view.View.performClick
    View.java:7322 android.view.View.performClickInternal
    View.java:849 android.view.View.access$3200
    View.java:27882 android.view.View$PerformClick.run
    Handler.java:873 android.os.Handler.handleCallback
    Handler.java:99 android.os.Handler.dispatchMessage
    Looper.java:216 android.os.Looper.loop
    ActivityThread.java:7263 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:494 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:975 com.android.internal.os.ZygoteInit.main
```

### Expected Behavior
No crashes
### Actual Behavior
Crash during app launch

### SDK Version
"instabug-reactnative": "^8.6.2",

### React Native, iOS and Android Versions
"react-native": "0.59.9",
Android 9 API LVL 28

### Device Model
Samsung SM-N975U (maybe happens on other devices too, but the crash report came from this device)

**Comment by SudoPlz** [comment]
Any news on that?

**Comment by SudoPlz** [comment]
Nope?

**Comment by alyezz** [comment]
@SudoPlz Sorry for the late reply, unfortunately we are unable to replicate the issue on our side. Do you mind updating to the latest version 8.7.2 and letting us know if the issue persists?

**Comment by SudoPlz** [comment]
It's supper hard to tell you wether that's fixed or not, this came from one of our users in production via a crash report, so to tell you that, I'll have to publish a new version, and wait for that crash to either happen or not happen at some point in the future.
