### ISSUE TITLE
ANR problem triggered by setUserAttribute 

### ISSUE THREAD

**Issue by fchicken** [Instabug/Instabug-Android#234]
Hi,

Many ANR occurred when setUserAttribute is called.

The following is the stack trace:
![Screen Shot 2019-10-01 at 11 57 52 AM](https://user-images.githubusercontent.com/10477535/65933600-ba899a80-e444-11e9-9e71-6d5db4b472fd.png)

### SDK Version
8.7.0

### Android Version
Occurs on lots of versions

### Device Model
Occurs on lots of devices

**Comment by hanaamohamed** [comment]
Hi @fchicken,

Sorry to hear that, here's a snapshot with the fix

`com.instabug.library:instabug:8.7.0.7-SNAPSHOT`

In order to consume this snapshot, you need to fetch it from the below repository
```
   maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
```

**Comment by fchicken** [comment]
Hi @hanaamohamed,

I'll try it in the new version of production and tell you the result after it's released.
Thanks for your prompt reply :)
