### ISSUE TITLE
SQLiteDatabaseWrapper.java – line 31

### ISSUE THREAD

**Issue by Axrorxoja** [Instabug/Instabug-Android#237]
<img width="951" alt="Screen Shot 2019-10-09 at 3 37 51 PM" src="https://user-images.githubusercontent.com/5182036/66474506-e5aa6480-eaaa-11e9-9793-d0e2510d13f3.png">

**Comment by mzelzoghbi** [comment]
@Axrorxoja Thanks for reporting this.
What is InstabugSDKVersion you are using and integration code?

**Comment by Axrorxoja** [comment]
Hi @mzelzoghbi at time instabug version 8.6.3 
what is the integration code?

**Comment by mzelzoghbi** [comment]
@Axrorxoja
The integration code is the code you used to Initialize the SDK.

Please Update to **8.7.2** and let us know if you faced this issue again.
