### ISSUE TITLE
Qt Android Application - Instabug integration fails

### ISSUE THREAD

**Issue by narayanan-t2s** [Instabug/Instabug-Android#238]
We created a sample Android project using Qt QML and trying to integrate Instabug into it. We observed that the Instabug is not being called from the application.

### Steps to Reproduce the Problem
1) Create a sample Qt Android application.
2) Integrate Instabug on onCreate Java code.

### Expected Behavior
1) Instabug dialog to be called on shaking or any invocation method.

### Actual Behavior

1) Instabug dialog is not invoked.

### Instabug integration code
package com.t2s.qtInstaBug;

import android.os.Bundle;
import android.util.Log;

import com.instabug.library.Instabug;
import com.instabug.library.invocation.InstabugInvocationEvent;

public class QtInsta extends org.qtproject.qt5.android.bindings.QtActivity{

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.e("QtInsta", "//STARTED//");
        System.out.println("///STARTED");
        Instabug instabug = new Instabug.Builder(getApplication(), "apikey")
                .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)
                .build();
//        Log.e("QtInsta", "instabug setup "+(instabug != null));

    }
}

### build.gradle

apply plugin: 'com.android.application'

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'

    }
}

allprojects {
    repositories {
        jcenter()
    }
}

android {
    compileSdkVersion androidCompileSdkVersion.toInteger()
    buildToolsVersion androidBuildToolsVersion

    defaultConfig {
        applicationId "com.t2s.qtInstabug"
        minSdkVersion 16
        targetSdkVersion 16
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        flavorDimensions "default"
        vectorDrawables.useSupportLibrary = true
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    lintOptions {
        abortOnError false
    }
        sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = [qt5AndroidDir + '/src', 'src', 'java']
            aidl.srcDirs = [qt5AndroidDir + '/src', 'src', 'aidl']
            res.srcDirs = [qt5AndroidDir + '/res', 'res']
            resources.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
       }
    }

}

repositories {
    maven {
        // TODO add this only if interested in getting SNAPSHOT releases
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
    google()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:multidex:1.0.3'
    implementation "com.android.support:design:28.0.0"
    implementation "com.android.support:appcompat-v7:28.0.0"
    
    implementation 'com.instabug.library:instabug:8.7.0'

    //TODO add the following 2 lines if you exclude io.reactivex from Instabug
    //implementation 'io.reactivex:rxjava:1.0.13'
    //implementation 'io.reactivex:rxandroid:1.0.1'
    implementation('com.instabug.library:instabug:8.7.0') {
        // TODO uncomment this line to exclude RxJava from Instabug and use your own version
        // exclude group: 'io.reactivex'

        // TODO uncomment next line if you're facing compilation issue in build.gradle about gms different versions
        //exclude group: 'com.android.support'
    }
    implementation 'petrov.kristiyan:colorpicker-library:1.1.8'
}

### SDK Version
Minimum SDK Version - API 16 Android 4.1
Target SDK Version - API 16 Android 4.1

### Android Version
Minimum SDK Version - API 16 Android 4.1
Target SDK Version - API 16 Android 4.1

### Device Model
Any Android mobile / tablet

**Comment by amrbrkt** [comment]
Hey @narayanan-t2s ,
Thanks for reaching out to us with that! We believe the issue stems from Instabug not supporting this framework at the moment, but what we'll do is that we'll share this with our product team so that they can consider support for it in future releases. In the meantime, if there's anything else you'd like to know, please don't hesitate to reach out.
