### ISSUE TITLE
InstaBug.SetStringToKey Instabug.strings.reportBug not working on android

### ISSUE THREAD

**Issue by tuannguyen041094** [Instabug/Instabug-Android#240]
I have Problem when set up  InstaBug.SetStringToKey with Instabug.strings.reportBug. On IOS it ok but in android it's not right . Please help me resolve this problem.
<img width="732" alt="Screen Shot 2019-10-10 at 11 08 24 AM" src="https://user-images.githubusercontent.com/39692275/66538407-6ec6a780-eb4e-11e9-87cb-eca226d05891.png">

**Comment by AliAbdelfattah** [comment]
@tuannguyen041094 here's a custom build with the fix till the next release.
```
npm install --save https://github.com/Instabug/Instabug-React-Native#custom/locales-android-8.7.0.3
```
