### ISSUE TITLE
2 issues after upgrading from 8.0.8 to 8.7.2

### ISSUE THREAD

**Issue by KarimFikani** [Instabug/Instabug-Android#248]
First Issue welcome page not showing even though the same code on 8.0.8 works fine but on 8.7.2 doesn't. Welcome page does not show up.

### Instabug integration code
```
// Initialize instabug
new Instabug.Builder(this, Constants.INSTANCE.getINSTA_BUG_API_KEY())
                .setInvocationEvents(InstabugInvocationEvent.NONE)
                .build();

        CrashReporting.setState(Feature.State.DISABLED);

        BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK);

        Instabug.setColorTheme(InstabugColorTheme.InstabugColorThemeLight);
        Instabug.setPrimaryColor(ContextCompat.getColor(this, R.color.cerulean));

        InstabugCustomTextPlaceHolder placeHolder = new InstabugCustomTextPlaceHolder();
        placeHolder.set(InstabugCustomTextPlaceHolder.Key.REPORT_FEEDBACK, getString(R.string.report_feedback));
        placeHolder.set(InstabugCustomTextPlaceHolder.Key.REPORT_BUG, getString(R.string.report_bug));
        Instabug.setCustomTextPlaceHolders(placeHolder);

// Called when the support screen shows up 
if (!applicationContext.isInstabugMessageShown()) {
            if (BuildConfig.isBetaBuild || BuildConfig.isTestingBuild) {
                Instabug.setWelcomeMessageState(WelcomeMessage.State.BETA) // For beta testers
                Instabug.showWelcomeMessage(WelcomeMessage.State.BETA)
            } else {
                Instabug.setWelcomeMessageState(WelcomeMessage.State.LIVE) // For live users
                Instabug.showWelcomeMessage(WelcomeMessage.State.LIVE)
            }

            applicationContext.saveInstabugMessageShown()
        }

```

Second issue is that the prompt options popup plays an exit animation that drops from top to the bottom of the screen. In 8.0.8 that screen used to just fade out and disappear. I find the new animation is not consistent with the animation of my screens. Is there a way I can change the animation?

**Comment by KarimFikani** [comment]
Hey @mzelzoghbi, I did clear the cache and even uninstalled the app and couldn't see it. I did split the code in the following way and still not showing:

```
override fun onCreateInitialized(savedInstanceState: Bundle?) {
    ...
    if (BuildConfig.isBetaBuild || BuildConfig.isTestingBuild) {
            Instabug.setWelcomeMessageState(WelcomeMessage.State.BETA) // For beta testers
        } else {
            Instabug.setWelcomeMessageState(WelcomeMessage.State.LIVE) // For live users
        }
}

override fun onResume() {
        super.onResume()

            if (BuildConfig.isBetaBuild || BuildConfig.isTestingBuild) {
                Instabug.showWelcomeMessage(WelcomeMessage.State.BETA)
            } else {
                Instabug.showWelcomeMessage(WelcomeMessage.State.LIVE)
            }
}
```

The showWelcomeMessage is being executed but nothing is showing. I tried multiple devices and emulators and I get the same behavior, no welcome page shows up.

As for the second issue, 

instabug_8.0.8:

![instabug_8 0 8](https://user-images.githubusercontent.com/2486075/67799171-18a89e00-fa42-11e9-994d-77bea41ea1d2.gif)

instabug_8.7.2:
![instabug_8 7 2](https://user-images.githubusercontent.com/2486075/67799172-18a89e00-fa42-11e9-8dc5-dbb79936a962.gif)

**Comment by mzelzoghbi** [comment]
@KarimFikani Sorry for the 1st issue I forgot to tell you that it will not gonna show with the **NONE** invocation event. You should change your invocation to any of the other invocation methods to be able to show the welcome message. Can you please give it a try and verify if it worked?

**Comment by KarimFikani** [comment]
@mzelzoghbi ok that worked thx!

**Comment by mzelzoghbi** [comment]
@KarimFikani Great, For the animation issue, We can confirm it is an issue from our side, however, we created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
```
implementation 'com.instabug.library:instabug:8.7.2.3-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

**Comment by KarimFikani** [comment]
yep works :)

**Comment by mzelzoghbi** [comment]
@KarimFikani Happy to hear that everything is working now. This will be included in our next official release planned to be in two weeks. 

Thank You.
