### ISSUE TITLE
com.instabug.library.PresentationManager.show throws NullPointerException

### ISSUE THREAD

**Issue by THEAccess** [Instabug/Instabug-Android#249]
I have a issue with Instabug. My crash reporting reports that about 8% of my users are experiencing a crash whose source is in the Instabug library.

### Steps to Reproduce the Problem
Can't reproduce on available test devices

### Instabug integration code
Application.kt: 
```
Instabug.Builder(this, getString(R.string.instabug_api_token))
            .setInvocationEvents(
                InstabugInvocationEvent.SHAKE,
                InstabugInvocationEvent.FLOATING_BUTTON

            )
            .build()

        `Instabug.setWelcomeMessageState(WelcomeMessage.State.BETA)
```

Stacktrace:
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
       at com.instabug.library.PresentationManager.show(PresentationManager.java:40)
       at com.instabug.library.b.b(b.java:496)
       at com.instabug.library.b.a(b.java:403)
       at com.instabug.library.b$7.run(b.java:344)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)`
### SDK Version
8.7.2

### Android Version
Reports include 6-9
### Device Model
(Excerpt) Galaxxy J8, Huawei P8 lite 201, Xiaomi Redmi 5A, Galaxy A30, Huawei 
Honor 7A

**Comment by THEAccess** [comment]
Seriously, my crash reporting is flooded with serveral crashes whose origin is in the Instabug library. About 8% of users are affected. If this doesn't get fixed i have to remove the Instabug library in order to not annoy users.

**Comment by mzelzoghbi** [comment]
Hi @THEAccess ,
Please accept our apologies for the inconveniences we may have caused. I completely understand how that can be frustrating. Please rest assured that we’re always working on improving the stability of our SDKs while introducing new helpful features. 

This issue has been fixed in 9.0.3, Please upgrade and let us know if this issue still happens.

Thank You

**Comment by imranMnts** [comment]
Hello @mzelzoghbi,

Can we have the fix in 8.0.x to use it into the project which not support androidX please?

**Comment by mzelzoghbi** [comment]
Yes Sure, HYG 

```
implementation 'com.instabug.library:instabug:8.7.2.7-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by imranMnts** [comment]
Awesome, thank you 🙂
