### ISSUE TITLE
Xamarin.Android  No resource found that matches the given name (at 'layout_toStartOf' with value '@id/ib_bug_repro_step_delete')

### ISSUE THREAD

**Issue by moreirawebmaster** [Instabug/Instabug-Android#253]
Erro new version in xamarin.android:

No resource found that matches the given name

### Expected Behavior
No resource found that matches
### Actual Behavior
resource found that matches
### Instabug integration code

No resource found that matches the given name (at 'layout_toStartOf' with value '@id/ib_bug_repro_step_delete'). |App.Android | C:\projects\app\app.Android\obj\Debug\90\lp\11\jl\res\layout\ib_bug_repro_steps_item.xml | 2 |   |  
Error |   | No resource found that matches the given name (at 'layout_toLeftOf' with value '@id/ib_bug_repro_step_delete'). |App.Android | C:\projects\app\app.Android\obj\Debug\90\lp\11\jl\res\layout\ib_bug_repro_steps_item.xml | 2 |   |  

### SDK Version
8.6.3

**Comment by mzelzoghbi** [comment]
Hey @moreirawebmaster Thanks for reporting this. Is this issue reproducible? If yes can you please provide a sample application with the issue? 

Thank You

**Comment by moreirawebmaster** [comment]
Hi @mzelzoghbi  any application xamarin.forms adding instabug-android in project android of Nuget.
Sorry, app installed instabug is commercialite.

**Comment by alyezz** [comment]
@moreirawebmaster From Visual Studio, open the Android project options. Under the “Build” header from the sidebar, select “Android Build” option. Check the option “Use incremental Android packaging system (aapt2)“.
<img width="969" alt="Screen Shot 2019-08-19 at 18 16 03" src="https://user-images.githubusercontent.com/10798072/69365596-5d200600-0c9d-11ea-8587-59a3ef149d63.png">

**Comment by moreirawebmaster** [comment]
@alyezz ohhhhhhhhhhhh very nice man! Working. Got it!!!!!
