### ISSUE TITLE
Network requests with custom Content-Type response header are not being reported

### ISSUE THREAD

**Issue by pwojnar** [Instabug/Instabug-Android#255]
### Steps to Reproduce the Problem
I use OkHttp3 library for networking with Instabug Interceptor.
In some network requests I use a custom Accept header and then the backend response containts a custom Content-Type header. Something like "application/abc-v2+json". 

### Expected Behavior

I expect all of those requests will be logged in Instabug reports.

### Actual Behavior

All requests with custom content-type response header are not reported. If I sent a request with a custom Accept header but it failes or gets No Response, so there is no response header "custom-type", then they are being reported.

### Instabug integration code
```
Instabug.Builder(this, BuildConfig.instabugKey).build()
if (BuildConfig.instabugReportCrashes) {
    CrashReporting.setState(Feature.State.ENABLED)
} else {
    CrashReporting.setState(Feature.State.DISABLED)
}
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
```

```
val httpBuilder = OkHttpClient.Builder()
httpBuilder.addInterceptor(InstabugOkhttpInterceptor())
retrofit = Retrofit.Builder()
            .baseUrl(backendUrl)
            .client(httpBuilder.build())
            .build()
```

### SDK Version
9.0.3 (it was also happening in 8.7.2)

### Android Version
Android 8.1 and 9

### Device Model
samsung SM-G960F, HUAWEI DUB-LX1

**Comment by Korazy** [comment]
Hi @pwojnar 
Thanks for reaching out to us over here and apologies for not getting back to you sooner!

While we don’t support this specific content type, what you can do as a workaround would be to implement your own interceptor and pass it to the Instabug methods as described [here](https://docs.instabug.com/docs/android-logging#section-logging-httpurlconnection-requests).

The content types supported by our HTTP Interceptor are the following:
```
application/json
application/protobuf
application/xml
text/xml
text/html
text/plain
```
If you need any other help here, please let us know.
