### ISSUE TITLE
Xamarin.Android Error inflating class com.instabug.library.view.viewgroup.IBPercentageRelativeLayout

### ISSUE THREAD

**Issue by moreirawebmaster** [Instabug/Instabug-Android#256]
Java.Lang.RuntimeException: 'Unable to start activity ComponentInfo{br.com.app.app/com.instabug.library.invocation.invocationdialog.InstabugDialogActivity}: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class com.instabug.library.view.viewgroup.IBPercentageRelativeLayout'

### Steps to Reproduce the Problem
Printscreen or Shake 

### SDK Version
8.7.2

### Android Version
6.0/8.0/9.0

### Device Model
Samsung S7/S8/S9

**Comment by AliAbdelfattah** [comment]
Hi @moreirawebmaster, sorry this has taken us a while to get back to you. The issue has been fixed in Xamarin v9.0.0.
