### ISSUE TITLE
The position of icons on buttons shift when pressed on Android 23

### ISSUE THREAD

**Issue by lyricaljourney** [Instabug/Instabug-Android#260]
### Steps to Reproduce the Problem

Launch our application, navigate to a screen where a button has an icon (such as a play triangle.

### Expected Behavior

The icon should be correctly centred in the button.

### Actual Behavior

Initially, the icon is correctly centred, but after pressing, the icon is no longer correcly centred. For some buttons, it jumps back to the centre by itself but for others it remains misaligned until the user leaves the screen.

### Instabug integration code

```
    new Instabug.Builder(AppContext.getGlobalApplication(), instabugToken)
        .setInvocationEvents(showInstabugButton ? InstabugInvocationEvent.FLOATING_BUTTON : InstabugInvocationEvent.NONE)
        .build();
    Surveys.setAutoShowingEnabled(showInstabugButton);

    StringBuilder userData = new StringBuilder();
    userData.append("App version: ").append(AppUtils.getVersionText(context, BuildConfig.versionBuildName)).append("\n");
    EBuildType clientBuildType = BuildHelper.getClientBuildType();
    userData.append("Build type: ").append(clientBuildType).append("\n");
    Instabug.setUserData(userData.toString());
```

### SDK Version

API level 28 revision 6

### Android Version

Android version 23

### Device Model

Trimble TD520

**Comment by lyricaljourney** [comment]
I should add that if we execute the Instabug integration code given above, we see this issue with Instabug 9.0.3 (and earlier versions that we have used) and if we launch the app and do not execute the Instabug integration code, then we do not see the issue. So we are confident this behaviour is some sort of side effect of Instabug.

**Comment by mzelzoghbi** [comment]
Hi @lyricaljourney 
Thanks for reporting this, Can you provide us with a GIF/Video for the issue? We will also need to know The view class of the view that is affected by Instabug and if it happens on this device only or on other devices.

Thank You

**Comment by lyricaljourney** [comment]
Attaching a video:
[EW2888.zip](https://github.com/Instabug/Instabug-Android/files/4028006/EW2888.zip)

This is an android.widget.ImageButton.

**Comment by lyricaljourney** [comment]
I have asked our testing team to investigate whether this happens on a non-Trimble device.

**Comment by lyricaljourney** [comment]
We have confirmed that we see the same behaviour on a Samsung Galaxy Tab S4 SM-T830.

**Comment by amrbrkt** [comment]
@lyricaljourney Thanks for the info you provided, we will look into this issue and come back to you ASAP.

**Comment by lyricaljourney** [comment]
We have a reproduction scenario if that helps. Source code for two apps, one of which enables Instabug and demonstrates this issue, one of which does not and does not.

[ImageButtonTest.zip](https://github.com/Instabug/Instabug-Android/files/4084274/ImageButtonTest.zip)

**Comment by amrbrkt** [comment]
Thanks @lyricaljourney, this is very helpful. I'll get back to you soon.

**Comment by lyricaljourney** [comment]
Do you have an update for us? We have important customers who are not willing to accept our product while it exhibits this behaviour.

**Comment by mzelzoghbi** [comment]
Hi @lyricaljourney , please accept our sincerest apologies for taking some time to come up with a fix for your issue. 

We created a **SNAPSHOT** that should fix the issue, Can you give it a try & let us know if it fixed the issue for you?
```
implementation 'com.instabug.library:instabug:9.0.5.4-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😊

**Comment by lyricaljourney** [comment]
Hi @mzelzoghbi, I have tried loading this snapshot but it looks like we need a version built for compileSdkVersion 28 since we are not yet using Android 10. Is that possible, please?

**Comment by Muhammadyoussef** [comment]
Hi @lyricaljourney,

Sure! Would you please let me know which Instabug SDK version are you using?

**Comment by lyricaljourney** [comment]
Thanks, we have the build that we need now. We are now working on updating our codebase so we can keep up with Android.
