### ISSUE TITLE
Fatal Exception java.lang.String com.instabug.library.model.State.toJson()

### ISSUE THREAD

**Issue by mahmoudElfeel67** [Instabug/Instabug-Android#261]
### Steps to Reproduce the Problem
I don't know how to produce
### Actual Behavior
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.instabug.library.model.State.toJson()' on a null object reference
       at com.instabug.bug.c$a.run + 21(c.java:21)
       at java.lang.Thread.run + 762(Thread.java:762)`
### Instabug integration code
*Make sure to remove your app token.*
new Instabug.Builder(this, "")
                    .setInvocationEvents(InstabugInvocationEvent.FLOATING_BUTTON)
                    .build();
### SDK Version
com.instabug.library:instabug:9.0.3
### Android Version
API level 28
### Device Model
Galaxy S9+

**Comment by mzelzoghbi** [comment]
Hello @mahmoudElfeel67, Thanks for reporting this. 
This should be fixed on the latest release `9.0.4`. Please let us know if you faced any other issues. 
Thank You

**Comment by libcg** [comment]
@mzelzoghbi when was this issue introduced? I'm able to reproduce it with all releases from 8.7.2 to 9.0.3.

**Comment by mzelzoghbi** [comment]
@libcg It was introduced in 8.7.2 and it is not happening consistently it only happens when the app is using the threads intensively.
