### ISSUE TITLE
Remove asking for phone number in a bug report

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#266]
I've had users complaining that I am asking for a phone number, and there doesn't seem to be a way to remove it from the form.

**Comment by mzelzoghbi** [comment]
Hello Eliezer,
Thank you so much for reaching out to us! We need to investigate into this further to help you. We recommend reaching out to our Customer Engineers team through this email: contactus@instabug.com. We'll be able to dig deeper into it by then and reach a solution.
Looking forward to hearing from you.
