### ISSUE TITLE
Vector resource on KitKat

### ISSUE THREAD

**Issue by jiriadamec** [Instabug/Instabug-Android#269]
```
android.content.res.Resources$NotFoundException: File res/drawable/ib_bug_ic_edit.xml from drawable resource ID #0x7f08010a. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
```

### Steps to Reproduce the Problem

Open bug report on Android 4.4

### Expected Behavior

Bug report screen opened

### Actual Behavior

Crash

### SDK Version

9.0.4

### Android Version

4.4 (API 19)

### Device Model

Emulator

**Comment by amrbrkt** [comment]
Thanks @jiriadamec for reporting this, we are sorry that you faced such issue. We will be looking into this and getting back to you ASAP.

**Comment by amrbrkt** [comment]
Hi @jiriadamec 
We've created a snapshot for you contains a fix for these warnings, please note this snapshot is totally safe to use and does not contain any debugging/ non-production code.
To use the snapshot:
Add these to your app-level `build.gradle` file to grab snapshots:
```
dependencies {
  implementation 'com.instabug.library:instabug:9.0.4.2433-SNAPSHOT'
}
```
```
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
} 
```
Please give it a try and let me know if you still facing the issue.
Thanks

**Comment by jiriadamec** [comment]
It's working, thanks for the fast fix. 👍

**Comment by amrbrkt** [comment]
Glad to hear that 👍
