### ISSUE TITLE
AndroidX Xamarin.Android

### ISSUE THREAD

**Issue by moreirawebmaster** [Instabug/Instabug-Android#271]
Instabug not working AndroidX Xamarin.Android

![image](https://user-images.githubusercontent.com/1142139/73204701-2b547100-411e-11ea-91e3-ca85fb210ed9.png)

**Comment by moreirawebmaster** [comment]
Java.Lang.ClassNotFoundException: 'Didn't find class "com.instabug.library.Instabug$Builder" on path: DexPathList[[zip file "/data/app/br.com.vitreo.dtvm-1/base.apk"],nativeLibraryDirectories=[/data/app/br.com.vitreo.dtvm-1/lib/arm64, /data/app/br.com.vitreo.dtvm-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]'

**Comment by mzelzoghbi** [comment]
Hello @moreirawebmaster , Thanks for reporting this. Is the issue reproducible on a sample app? it will help us to debug the issue faster and fix it.

**Comment by moreirawebmaster** [comment]
> Hello @moreirawebmaster , Thanks for reporting this. Is the issue reproducible on a sample app? it will help us to debug the issue faster and fix it.

To simples create one project Xamarin.Forms Include Libs AndroidX in Xamarin.Android and include instabug-for-android, build project and error:

Java.Lang.ClassNotFoundException: 'Didn't find class "com.instabug.library.Instabug$Builder" on path: DexPathList[[zip file "/data/app/br.com.vitreo.dtvm-1/base.apk"],nativeLibraryDirectories=[/data/app/br.com.vitreo.dtvm-1/lib/arm64, /data/app/br.com.vitreo.dtvm-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]'

**Comment by alyezz** [comment]
@moreirawebmaster Right click on your `project.Android` go into Options -> Android Build and change the Dex compiler to `d8` instead of `dx`

![Screen Shot 2020-01-28 at 3 04 11 PM](https://user-images.githubusercontent.com/10798072/73266623-e8f36880-41df-11ea-8974-09571229743d.png)

**Comment by moreirawebmaster** [comment]
> @moreirawebmaster Right click on your `project.Android` go into Options -> Android Build and change the Dex compiler to `d8` instead of `dx`. Save then clean/rebuild the error should disappear
> 
> ![Screen Shot 2020-01-28 at 3 04 11 PM](https://user-images.githubusercontent.com/10798072/73266623-e8f36880-41df-11ea-8974-09571229743d.png)

THANKSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS!
your save my day!!!!!!!!!
hugs....
