### ISSUE TITLE
VerifyError Crash on version 9.0.5

### ISSUE THREAD

**Issue by remerico** [Instabug/Instabug-Android#274]
### Steps to Reproduce the Problem
Compile the app using release build with Proguard

### Expected Behavior
Instabug should run

### Actual Behavior
Instabug crashes the app on initialization

### Instabug integration code
```
Instabug.Builder(application, apiKey)
    .setInvocationEvents(
            InstabugInvocationEvent.FLOATING_BUTTON,
            InstabugInvocationEvent.SHAKE)
    .build()
Instabug.setLocale(Locale("ru"))
BugReporting.setViewHierarchyState(Feature.State.ENABLED)
BugReporting.setShakingThreshold(SHAKE_THRESHOLD)
```

### SDK Version
9.0.5

### Android Version
API 29

### Device Model
Android emulator, Samsung Galaxy S9

### Stack Trace
```
java.lang.VerifyError: Verifier rejected class com.instabug.library.c: void com.instabug.library.c.a(java.lang.String) failed to verify: void com.instabug.library.c.a(java.lang.String): [0x2D] 'this' arg must be initialized (declaration of 'com.instabug.library.c' appears in base.apk!classes2.dex)
 	at com.instabug.library.Instabug$Builder.<init>(Instabug.java:10)
 	at com.instabug.library.Instabug$Builder.<init>(Instabug.java:2)
 	at com.instabug.library.Instabug$Builder.<init>(Instabug.java:1)
```

**Comment by mzelzoghbi** [comment]
Hi @remerico , Thanks for reporting this. Would you please let me know how frequent this crash is and if it happens in debug version or on released production version?

**Comment by remerico** [comment]
Hi @mzelzoghbi, thank you for responding. The crash always occurs on released builds, but not on debug. We have Proguard enabled on our release builds.

We have also tried adding the following Proguard rule `-keep class com.instabug.** { *; }` but the crash still occurs.

**Comment by mzelzoghbi** [comment]
Do u have any special configuration on your project for r8, excluding any dependencies ?or anything like these ?

**Comment by remerico** [comment]
We do not have R8 enabled right now, here is our gradle configuration:

gradle.properties:
```
android.useAndroidX=true
android.enableR8=false
android.enableJetifier=true
```

build.gradle (app)
```
android {
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            testProguardFile 'proguard-test-rules.pro'
        }
    }
}
```

**Comment by mzelzoghbi** [comment]
I guess disabling the R8 is causing the issue, I'll investigate from my side and get back to you ASAP. But can you also try enabling R8 and tell me if it worked?

**Comment by remerico** [comment]
Hello @mzelzoghbi, we found out the issue in our app, it is New Relic SDK 5.24.0 that is causing the crashes. Updating to New Relic 5.24.2 with Instabug 9.0.5 seemed to have fixed the crash issue.

I looked in New Relic's release notes and saw this specific entry, maybe this was the cause of conflicting issue with Instabug?
```
New Relic Android 5.24.2:

- Fixed a set of DEX failures that emerged when JSONObject(String) and JSONArray(String) 
  invocations were instrumented. Unfortunately, the time spent in instance construction 
  can no longer be reported as a result of the change.
```

**Comment by mzelzoghbi** [comment]
@remerico Seems that this was the issue, Happy to hear that everything worked now. 
Please feel free to reach out to us again if you encountered any issues. 
Thank You.
