### ISSUE TITLE
foregroundServiceType

### ISSUE THREAD

**Issue by KORuL** [Instabug/Instabug-Android#275]
### Steps to Reproduce the Problem

Compile the app using release build

### Expected Behavior

Instabug should run

### Actual Behavior

Compile Error

### Instabug integration code
```

        Instabug.Builder(this, "token")
            .setInvocationEvents(InstabugInvocationEvent.NONE)
            .build()
```

### SDK Version

9.0.5

### Android Version

all

### Device Model

all

### [Optional] Project That Reproduces the Issue

```
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\KORul\.gradle\caches\transforms-2\files-2.1\e50d21c5d9bdc13c68e4dfc88fdc4ac8\jetified-instabug-core-9.0.5\AndroidManifest.xml:40:9-44:63: AAPT: error: attribute android:foregroundServiceType not found.
```

**Comment by mzelzoghbi** [comment]
Hi @KORul, Thanks for reporting this, can you please change your compileSDKVersion to 29? This sould fix your issue. And please let us know if the issue is solved.

Thank You 😊

**Comment by KORuL** [comment]
Yes, it solved

**Comment by matir91** [comment]
Hi, it's a library, so I think it shouldn't use `compileSDKVersion` 29, you are removing support for users that cannot updated it. Furthermore, if you change it, you cannot update a patch version, at least a minor version and add a breaking change note in the release changelog.

**Comment by Korazy** [comment]
Hey @matir91 

Thank you for reaching out. I definitely understand your concern regarding this and we'll most definitely work on enhancing our communication with breaking changes such as this one. To further elaborate on why it must be set to 29, this is mainly in order to support screen recording, as well as some privacy updates, on Android 10 that would otherwise not work.

Apologies for the confusion on this. If you need any other clarification at all, feel free to let us know.

**Comment by carstenhag** [comment]
Hey, just stumbled upon this issue too. Breaking changes such as this should not be hidden in a minor release :). My team and I will now have to look at increasing the compile/target SDK version to 29. Of course if Instabug needs it, it's a good heads-up anyway.

**Comment by nchase** [comment]
In addition to what others have said, it would be great to have some mention of this in the react-native documentation as well.

**Comment by shreyvijayvargiya** [comment]
YES, It would be better for everyone if it was mentioned in documentation under SDK version dependency

**Comment by Korazy** [comment]
Thanks for the feedback! We'll make sure to add this particular information to our React Native documentation as well 😊

**Comment by TMcLoone** [comment]
Documentation still needs updated.

**Comment by mohadel92** [comment]
> Hi @KORuL, Thanks for reporting this, can you please change your compileSDKVersion to 29? This sould fix your issue. And please let us know if the issue is solved.
> 
> Thank You 😊

this fixed my issues
i was having trouble linking ZOOM SDK for android with my current android project 
Thanks  a lot
