### ISSUE TITLE
Misplaced icons in the main menu dialog

### ISSUE THREAD

**Issue by algrid** [Instabug/Instabug-Android#276]
There's no space between icons and text in the main menu dialog. It doesn't look good.

### Steps to Reproduce the Problem
Just call `Instabug.show()`

### Expected Behavior
There's a space between icons and text like here https://docs.instabug.com/docs/android-design

### Actual Behavior
![instabug_misp](https://user-images.githubusercontent.com/6792526/74286024-ac6f5300-4d2f-11ea-9fd3-e1a5d76cb3ff.png)

### Instabug integration code
```
        new Instabug.Builder(MyApplication.this, "...")
           .setInvocationEvents(InstabugInvocationEvent.NONE).build();

        Surveys.setAutoShowingEnabled(false);
```

### SDK Version
9.0.5

### Android Version
10

### Device Model
Google Pixel 1st gen

**Comment by mzelzoghbi** [comment]
Hello @algrid, Thanks for reporting this.
We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
``` 
implementation 'com.instabug.library:instabug:9.0.5.9-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😃

**Comment by algrid** [comment]
@mzelzoghbi Thank you, it fixed the problem! 😀
