### ISSUE TITLE
Follow system dark/light mode settings.

### ISSUE THREAD

**Issue by algrid** [Instabug/Instabug-Android#277]
This is a feature request, not a bug report.

It would be really nice if Instabug could follow current app mode with regards to light/dark theme.

For example a new option can probably be added to the `InstabugColorTheme` enum. Something like `InstabugColorThemeFollowApp` or `InstabugColorThemeFollowSystem`. This option could be a good choice as default.

Also it would be really useful to be able to set two different primary colors (`Instabug.setPrimaryColor`): one for the dark theme, another one for the light theme. This way one-time setup will be enough for all cases.

**Comment by Korazy** [comment]
Hey @algrid 
Thanks for reaching out! Your feedback definitely makes sense to me. We'll definitely be adding it to our product discussion and if it's added to our backlog in the future, you'll be the first to know.

In the meantime, if you have any other feedback at all, we'd love to hear it :)

**Comment by algrid** [comment]
@Korazy Cool, thank you, I'll be looking forward for new updates!

**Comment by Muhammadyoussef** [comment]
Hi @algrid,

I'm glad to let you know that this feature has finally made it to beta!

Now you can use the following APIs 

- **[New API] `Instabug.setColorTheme(@InstabugTheme int)`**
   - **InstabugTheme.LIGHT:** Sets Instabug theme to light
   - **InstabugTheme.DARK:** Sets Instabug theme to dark
   - **InstabugTheme.AUTO:** Let's Instabug follow the system's theme (set to auto by default)
- **[New API] `Instabug.getInstabugTheme()`**
   Returns the same value set using `Instabug.setColorTheme(..)`. Default value is `AUTO`
- **[New API] `Instabug.getAppliedInstabugTheme()`**
   A handy method to get the applied theme in case of setting Instabug theme color to `AUTO`

I created a SNAPSHOT for you that has the new APIs. Please give it a try & let me know if you face any issue.

```
implementation 'com.instabug.library:instabug:9.1.1.3-SNAPSHOT'
```

To consume the SNAPSHOT you will need to add the following to your app `build.gradle`
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This SNAPSHOT is completely safe to use and has no debug code at all.

**Comment by Muhammadyoussef** [comment]
Hi @algrid, did you get the chance to test this out? 😊

**Comment by algrid** [comment]
@Muhammadyoussef Hi! Sorry for delay, will try to test it next week. Thank you!

**Comment by algrid** [comment]
I finally had a chance to test it. Looks like it works, thank you!
One small note: if you call `Instabug.setPrimaryColor` first and then `Instabug.setColorTheme`, then your color is overwritten by the defaults, but that's probably ok.

**Comment by algrid** [comment]
@Muhammadyoussef Hi! Could you please tell me when this change will be included in the main release? Or maybe you can provide an updated snapshot?

We're affected by this bug https://github.com/Instabug/Instabug-Android/issues/293 and can't use 9.1.1.3-SNAPSHOT because of that.
