### ISSUE TITLE
 CRASH : com.instabug.bug.view.reporting.b$a.run 

### ISSUE THREAD

**Issue by mahmoudElfeel67** [Instabug/Instabug-Android#280]
### Steps to Reproduce the Problem
I cant reproduce
### Expected Behavior
Should not crash
### Actual Behavior
Crashes with error
 com.instabug.bug.view.reporting.b$a.run 

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference

in BaseReportingFragment.java:1
com.instabug.bug.view.reporting.b$a.run (b.java:1)

### Instabug integration code
new Instabug.Builder(this, "")
                    .setInvocationEvents(InstabugInvocationEvent.FLOATING_BUTTON)
                    .setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS)
                    .build();

### SDK Version
9.0.5
### Android Version
8.1.0
### Device Model
HUAWEI Y5 lite
### [Optional] Project That Reproduces the Issue
Cant provide that

**Comment by mahmoudElfeel67** [comment]
@mzelzoghbi Why is this not being answered ?

**Comment by mzelzoghbi** [comment]
Hi Mahmoud,

First of all, please accept our sincerest apologies for taking some time to come up with a fix for your issue. 

We created a **SNAPSHOT** that should fix the issue, Can you give it a try & let us know if it fixed the issue for you?
```
implementation 'com.instabug.library:instabug:9.0.5.14-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😊

**Comment by mahmoudElfeel67** [comment]
@mzelzoghbi  okay thanks 
will use and let you know if it happens again

**Comment by mahmoudElfeel67** [comment]
@mzelzoghbi this has not happened again thank you !
