### ISSUE TITLE
Shake gesture does not work on Pixel 2 XL

### ISSUE THREAD

**Issue by dohyeonio** [Instabug/Instabug-Android#281]
### Steps to Reproduce the Problem
1. Open the app
2. Shake the device

### Expected Behavior
- Bug reporting screen pops up

### Actual Behavior
- Bug reporting screen does not pop up
- Tapping the bubble icon works

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
9.0.5

### Android Version
10
Build number: QQ1A.200205.002

### Device Model
Pixel 2 XL

### [Optional] Project That Reproduces the Issue
https://www.dropbox.com/s/93bs2g7ob01s8wd/InstabugTest.zip?dl=0

**Comment by mzelzoghbi** [comment]
Hi @dohyeonio, 
Thanks for reporting this. We noticed from the sample project that you use the initialization code in your Activity & not in your **Application** class, this sometimes makes unexpected behavior, we recommend moving this builder block to the **Application** Class, You can also try to decrease the **Shaking threshold** using the API
```
BugReporting.setShakingThreshold(200);
```
Please let us know if this didn't solve the issue.

Thank You

**Comment by dohyeonio** [comment]
Hi @mzelzoghbi, setting the threshold to 200, or even 350 helped. 

When I set the value to 500, it was almost impossible to make it work no matter how hard you shake, and the default value is `650` in the code, so it was a bit weird, though.

Thank you for your help!
