### ISSUE TITLE
Can't get message from fcm when chat replies

### ISSUE THREAD

**Issue by Stractor** [Instabug/Instabug-Android#283]
### Steps to Reproduce the Problem

I want to push notification when we reply to user by chat, so I follow steps by [DOCUMENT](https://docs.instabug.com/docs/android-managing-notifications). I set the firebase api_key and it's api_token, but it doesn't work. I can receive message by firebase console.
    The message send by instabug dashboard is invalid in it:

``` JAVA
//code 1
public void onMessageReceived(RemoteMessage remoteMessage) {
        Logger.i(TAG, "From: " + remoteMessage.getFrom());
        if(Replies.isInstabugNotification(remoteMessage.getData())){
            // Send the data map.
            Logger.d(TAG, "message instabug");
            Replies.showNotification(remoteMessage.getData());
        }
}
```
I have set token in app, and register in Manifest.xml.
```JAVA
Replies.setPushNotificationRegistrationToken(token);
```
```JAVA
<service android:name=".service.MyFirebaseMessagingService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
                <!--I copy it in your code-->
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
```
### Expected Behavior
When replying to the user, I want to be able to handle it with code1, but the code does not run to this place. Although there will be in-app popups, notifications cannot be sent. When the app is in the background, there is no prompt.
### Actual Behavior
The message didn't go through the onMessageReceived. How could I fix it?
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
'com.instabug.library:instabug:8.4.0'
"com.instabug.library:instabug-with-okhttp-interceptor:8.4.0"

### Android Version
8.0
### Device Model
Samsung

**Comment by ramiimagdi** [comment]
Hey there,

Rami from Instabug is here, thank you for reaching out to us, please send us an email on contactus@instabug.com so we can gather up more information and help you out on this issue.

Looking forward to hearing back from you.
