### ISSUE TITLE
InstabugAnnouncementSubmitterService crashing on some devices

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#284]
I'm getting reports of crashes of InstabugAnnouncementSubmitterService because of a DeadSystemException. I don't think there's anything to do about that exception, but I'm more concerned about the fact that InstabugAnnouncementSubmitterService is running even though I don't use it.

I'm on 9.0.5.

**Comment by mzelzoghbi** [comment]
Hi Eliezer, Thanks for reporting this. 

For the exception, Unfortunately, we have nothing to do about it as you said. 

For `InstabugAnnouncementSubmitterService` it runs to check if there are any pending announcements sync events that need to be submitted. It makes sense to make the check before starting the service. 
We will work on a fix and will get back to you ASAP.

Thank You!

**Comment by mzelzoghbi** [comment]
Hi @eygraber 
We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
``` 
implementation 'com.instabug.library:instabug:9.0.5.2477-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😃

**Comment by eygraber** [comment]
Since I can't repro it and only rarely see reports of it in production, I'm not sure if I can actually conclude that it's been fixed in the short to medium term.

**Comment by mzelzoghbi** [comment]
Let's close it for now, and feel free to open it if it happened again.
