### ISSUE TITLE
IllegalStateException in FeatureRequestsDetailsFragment on version 8.7.2

### ISSUE THREAD

**Issue by do-current** [Instabug/Instabug-Android#285]
### Steps to Reproduce the Problem
I'm getting the crash report in Crashlytics but I can't reproduce this issue
### Expected Behavior
App doesn't crash
### Actual Behavior
App crashes with log:

```
Fatal Exception: java.lang.IllegalStateException: Fragment a{5a41f42} not attached to a context.
       at androidx.fragment.app.Fragment.requireContext + 696(Fragment.java:696)
       at androidx.fragment.app.Fragment.getResources + 760(Fragment.java:760)
       at androidx.fragment.app.Fragment.getString + 795(Fragment.java:795)
       at com.instabug.featuresrequest.ui.c.a$4.run + 202(FeatureRequestsDetailsFragment.java:202)
       at android.os.Handler.handleCallback + 790(Handler.java:790)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 198(Looper.java:198)
       at android.app.ActivityThread.main + 7055(ActivityThread.java:7055)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 523(RuntimeInit.java:523)
       at com.android.internal.os.ZygoteInit.main + 836(ZygoteInit.java:836)
```
### Instabug integration code
```
    public void showFeatureRequest() {
        FeatureRequests.show();
    }
```

### SDK Version
8.7.2
### Android Version & Device Model
![image](https://user-images.githubusercontent.com/56651169/75873980-7d866180-5e43-11ea-9219-460ed7f92a6d.png)

![image](https://user-images.githubusercontent.com/56651169/75874904-44e78780-5e45-11ea-8d77-fc00a221ce31.png)

**Comment by MahmoudAmin39** [comment]
@do-current Thanks for reporting this issue.
Please let me if your application is supporting `AndroidX` or the `Support Library`?

**Comment by do-current** [comment]
@MahmoudAmin39 , we fully migrated to AndroidX already.

**Comment by MahmoudAmin39** [comment]
@do-current I see,
Here is a snapshot containing the fix to the Exception `9.0.5.2480-SNAPSHOT`
## To use the snapshot: 
Add these to your app-level `build.gradle` file to grab snapshots:

```gradle
dependencies {
  implementation 'com.instabug.library:instabug:9.0.5.2480-SNAPSHOT'
}
```

```gradle
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by do-current** [comment]
Hi @MahmoudAmin39, thanks for your support.
I tried the snapshot above but I got this error:
```
Android resource linking failed
/Users/donguyen/.gradle/caches/transforms-2/files-2.1/e2eed9b658d26633c59be14714388ff3/jetified-instabug-core-9.0.5.2480-SNAPSHOT/AndroidManifest.xml:40:9-44:63: AAPT: error: attribute android:foregroundServiceType not found.
```
I know the solution is change  the `compileSdkVersion` to 29, but currently our app can't officially support API 29 immediately. Do you have any idea for our case?

**Comment by MahmoudAmin39** [comment]
@do-current Thanks for your feedback,
I will see what can I do from my side and feedback you ASAP

**Comment by do-current** [comment]
@MahmoudAmin39, it's 28

**Comment by MahmoudAmin39** [comment]
@do-current Thanks for your feedback,
Here is a snapshot containing the fix to the Exception `8.7.2.2481-SNAPSHOT`, Can you please try it and tell us if it fixed the issue for you?
## To use the snapshot: 
Add these to your app-level `build.gradle` file to grab snapshots:

```gradle
dependencies {
  implementation 'com.instabug.library:instabug:8.7.2.2481-SNAPSHOT'
}
```

```gradle
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by do-current** [comment]
@MahmoudAmin39 , many thanks! I will let you know if it happens again.

**Comment by do-current** [comment]
Hi @MahmoudAmin39 , just want to confirm, is this safe to use this SNAPSHOT in production?

**Comment by MahmoudAmin39** [comment]
Hi @do-current , Of course it is safe, as long as, it is working fine in `debug`.

**Comment by do-current** [comment]
Yeah, and I guess this issue will be also fixed in the next SDK version of Instabug, isn't it?

**Comment by MahmoudAmin39** [comment]
Hi @do-current, 
Unfortunately, it will not catch the next release as it should be out in the next couple of days, but probably it will catch the one after it.

**Comment by do-current** [comment]
@MahmoudAmin39 , I see. Can you let me know the fixed version when it releases?

**Comment by MahmoudAmin39** [comment]
@do-current, Sure.
