### ISSUE TITLE
How to show Instabug by two-finger swipe from right to left in dialog with custom layout?

### ISSUE THREAD

**Issue by dung90it** [Instabug/Instabug-Android#288]
### Expected Behavior
two-finger swipe from right to left showing Instabug

### Actual Behavior
Instabug isn't showing

### Instabug integration code
Instabug.Builder(this, INSTABUG_KEY)
                        .setInvocationEvents(InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT)
                        .setReproStepsState(State.ENABLED)
                        .setConsoleLogState(Feature.State.ENABLED)
                        .build()

### SDK Version
9.0.4

### Android Version
28

### Device Model
pixel 2

**Comment by Muhammadyoussef** [comment]
Hi @dung90it,

Please accept our apologies for the inconvenience this may have caused you. I completely understand how this can be frustrating. 

Right now we don't support working with dialogs. But we are working on a fix that will be rolled out within the next quarter. 

You can use one of the other [invocation events](https://docs.instabug.com/docs/android-invocation#section-invocation-events) as a workaround until w fully support working with dialogs. 

For now, you can watch [our releases](https://github.com/instabug/instabug-android/releases) to get notified whenever we support this feature.

Thanks for understanding 😊
