### ISSUE TITLE
android.content.res.Resources$NotFoundException on Dynamic Delivery

### ISSUE THREAD

**Issue by mrhabibi** [Instabug/Instabug-Android#291]
Hi,

I have a huge android project that uses instabug library, and we're going to implement dynamic delivery to reduce its size as well, started from separating our features and then libraries we're using, one of our medium sized library is instabug and we're going to separate it as on demand feature, but we faced a problem as follow:

### Steps to Reproduce the Problem
- Make a dynamic feature module and mark it as on demand module
- Implement instabug library there
- Upload to Play Store as AAB
- Download from Play Store
- Open app and download the dynamic feature module
- Show instabug popup

### Expected Behavior
- Instabug popup shown

### Actual Behavior
- Crash with stack trace:
```
Caused by android.content.res.Resources$NotFoundException
String resource ID #0x790f0001

  | android.content.res.Resources.getText + 379 (Resources.java:379)
  | android.content.Context.getText + 635 (Context.java:635)
  | com.instabug.library.util.LocaleUtils.getLocalizedStringResNewAPI + 4 (LocaleUtils.java:4)
  | com.instabug.library.util.LocaleUtils.getLocaleStringResource + 2 (LocaleUtils.java:2)
  | com.instabug.bug.i.c.c + 3 (c.java:3)
  | com.instabug.bug.i.c.a + 6 (c.java:6)
  | com.instabug.bug.e.b + 5 (e.java:5)
  | com.instabug.bug.BugPlugin.getPromptOptions + 1 (BugPlugin.java:1)
  | com.instabug.library.core.plugin.a.c + 5 (a.java:5)
  | com.instabug.library.invocation.InvocationManager.getAvailablePromptOptions + 1 (InvocationManager.java:1)
  | com.instabug.library.invocation.InvocationManager.isPromptOptionsAvailable + 1 (InvocationManager.java:1)
  | com.instabug.library.invocation.InvocationManager.notifyInvocationOptionChanged + 1 (InvocationManager.java:1)
  | com.instabug.chat.d.b + 11 (d.java:11)
  | com.instabug.chat.Replies.setState + 8 (Replies.java:8)
  | com.instabug.chat.a.b + 2 (a.java:2)
  | com.instabug.chat.ChatPlugin.initDefaultPromptOptionAvailabilityState + 1 (ChatPlugin.java:1)
  | com.instabug.library.core.plugin.a.d + 2 (a.java:2)
  | com.instabug.library.c.q + 3 (c.java:3)
  | com.instabug.library.c.h + 9 (c.java:9)
  | com.instabug.library.Instabug$Builder.build + 32 (Instabug.java:32)
  | com.instabug.library.Instabug$Builder.build + 62 (Instabug.java:62)
```

### Instabug integration code
```
class MyApplication : Application() {
  override fun onCreate() {
    Instabug.Builder(application, apiKey)
      .setInvocationEvents(InstabugInvocationEvent.NONE)
      .setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS)
      .build()
    Instabug.enable()
  }
}
```

### SDK Version
9.1.0

### Android Version
Varies versions from Lollipop to Q

### Device Model
Varies model like Samsung, Xiaomi, OPPO, etc

I've traced your library code and found out how instabug fetched String resources, it used Application context instead of Activity context, right? And I assumed it broke the resource fetcher because when using Application context, resource fetcher would assume that the resource was provided by base module instead of dynamic feature module, that's why Resources$NotFoundException was thrown.

Any thought?

**Comment by Muhammadyoussef** [comment]
Hi @mrhabibi,

Please make your Application class extends `SplitCompatApplication` and let us know whether or not this issue is still happening.

**Comment by mrhabibi** [comment]
Yeah, I've done something similar by inserting `SplitCompat.install(this)` in `Application.attachBaseContext()`. I always got this issue for my own code too when retrieving dynamic feature module resources using application context, but it solved by changing it to its own activity context.

**Comment by mrhabibi** [comment]
Hi @Muhammadyoussef,

Any update about this? :)

**Comment by Muhammadyoussef** [comment]
Hi @mrhabibi, 

So far, we weren't able to reproduce this issue on our end. Would you mind giving our latest major release `10.0.0` a go and let us know whether or not this issue is still happening. 

Thank you for understanding 🙏
