### ISSUE TITLE
App crashing when trying to close FeatureRequest Popup after setting App to background

### ISSUE THREAD

**Issue by FloriJann** [Instabug/Instabug-Android#292]
### Steps to Reproduce the Problem
1. Open the Feature Request Popup
2. Set App in Background
3. Open App again
4. Close Feature Request Popup by clicking the "X"
### Expected Behavior
Activity/Fragment comes back in foreground and Popup disappears
### Actual Behavior
App crashes
### Instabug integration code
??

### SDK Version
9.0.3
### Android Version
tested with API 28
### Device Model
Pixel 2

**Comment by Muhammadyoussef** [comment]
Hi @FloriJann,

Just to make sure we are on the same page, would you please confirm the following:
- [ ] You are [integrating Instabug](https://docs.instabug.com/docs/android-integration#section-using-instabug) in your Application class
- [ ] You are [showing Feature Requests list](https://docs.instabug.com/docs/android-showing-feature-requests#section-showing-feature-requests-list) with the following API: `FeatureRequests.show()`

Also, it will be very helpful if you can provide us with the following:
- Stacktrace
- Instabug integration code
- Whether or not the app was sent to the background for a relatively long period of time
- Instabug debug logs (From app start to crashing). 
To do this you will need to add the following line of code to your application class right after building Instabug:
`Instabug.setDebugEnabled(true);`

**Comment by FloriJann** [comment]
Hi @Muhammadyoussef, 
yes we are integrating Instabug in the Application class and yes we are showing the Feature Requests list with the API call. 
We are also calling `Instabug.show()` and `Instabug.logUserEvent()` in the App and everything works fine.

What exactly do you mean with "Instabug integration code"? I have no clue where to find such a thing in our app.

The Problem appears when I put the app to the background and get it back immediately.

I think I have to correct myself, the app doesn't really crash. When I follow the steps described above the app returns to the background instead of showing my Activity/Fragment. When I get it back in the front, I see the Feature Request Popup again.

Sorry for not sharing the stacktrace at the moment, it has been too much effort to filter it and I hadn't had the time for it till now.

**Comment by Muhammadyoussef** [comment]
@FloriJann Just to make sure I understand you correctly:

1. Launch the app
2. Open Instabug FeatureRequests page
3. Send app to background
4. Open the app again from the recent apps menu
5. Attempt to dismiss FeatureRequests page
6. Instead of going back to your activity, the app terminates itself
7. Open the app again from the recent apps menu
8. Instabug FeatureRequests page is displayed again

Is that the case?

**Comment by FloriJann** [comment]
@Muhammadyoussef Yes that's correct!

**Comment by Muhammadyoussef** [comment]
@FloriJann So, the issues seems to be that your app is failing to keep the activity in the background. This can happen for multiple reasons:

- You call `activity.finish()` right after or before `FeatureRequests.show()`
- The System limits background activities. Either for battery optimization or "Don't keep activities" is checked in your developers' options

The reason Instabug FeatureRequests gets resumed after you open the app again from the recent apps menu is that the system keeps a snapshot of your last activity. So, it might seem that it's resuming our activity but it's actually attempting to re-create it. 
To validate this, try launching your app from the app drawer. It should restart your application.

Would you please validate that this is the case? 🙏

**Comment by Muhammadyoussef** [comment]
Hi @FloriJann, do you have any updates on this? 🙏

**Comment by Muhammadyoussef** [comment]
Hi @FloriJann,

I'll close this ticket due to inactivity. Please feel free to re-open it if you are still facing this issue.
