### ISSUE TITLE
Activity finish after showing Instant dialog again

### ISSUE THREAD

**Issue by EdwarDDay** [Instabug/Instabug-Android#295]
### Steps to Reproduce the Problem
1. Click in one activity on the Instabug bubble
2. Instabug dialog is shown
3. The activity starts another activity because of an external event
4. The other activity is shown
5. Click again on Instabug bubble
6. Current activity finishes and Instabug dialog is shown on last activity (or over launcher, if the first activity has `noHistory`)

### Expected Behavior
The 2nd activity should not finish

### Actual Behavior
The 2nd activity finishes

### Instabug integration code
```kotlin
Instabug.Builder(this, appToken)
    .setInvocationEvents(InstabugInvocationEvent.FLOATING_BUTTON)
    .setInstabugLogState(Feature.State.ENABLED)
    .setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS)
    .setViewHierarchyState(Feature.State.ENABLED)
    .setTrackingUserStepsState(Feature.State.ENABLED)
    .setUserDataState(Feature.State.ENABLED)
    .build()
```
### SDK Version
9.1.3
### Android Version
7.1.1; 9
### Device Model
Samsung SM-T395; Samsung SM-A405FN

**Comment by Muhammadyoussef** [comment]
Hi @EdwarDDay,

Just to make sure we are on the same page:

1. App launches
2. `ActivityA` is launched
3. Invoke Instabug by the floating action button
4. While Instabug prompt options dialog is displayed `ActivityA` receives an event to start another activity
5. `ActivityB` is launched
6. Invoke Instabug by the floating action button
7.  While Instabug prompt options dialog is displayed `ActivityB` receives and event to finish
8. Instabug prompt options dialog is displayed above `ActivityA` (or above the launcher if `ActivityA` was destroyed)

Is that the correct scenario?

**Comment by EdwarDDay** [comment]
Point 7 is a little bit wrong or misunderstanding. `ActivityB` finishes because of the Instabug dialog and not because of an external finish event.
The rest is correct.

**Comment by Muhammadyoussef** [comment]
@EdwarDDay Instabug prompt options are supposed to be displayed above your current activity. We don't kill or destroy any displayed activities. 
This might be happening because the system is trying to limit activities running in the background. Either for battery optimization or "*Don't keep activities*" is checked in your developers' options. 

Can we confirm that this is not the case? 🙏

**Comment by EdwarDDay** [comment]
"Don't keep activities" is not checked and the phone is not in battery optimization mode. I thought, that instabug keeps the previous activity and then maybe a crash happens, and the app restarts with the last activity.

**Comment by Muhammadyoussef** [comment]
@EdwarDDay Would you mind sending us a sample app with the issue?

**Comment by EdwarDDay** [comment]
Sorry for letting you wait. Here is the Sample App: [Sample App](https://github.com/EdwarDDay/InstabugTest)
After starting the app, you have 10 seconds to click on the bubble. Afterwards the main activity is opened and you need to click again on the bubble.

**Comment by mzelzoghbi** [comment]
@EdwarDDay Thank for the sample app this is very helpful. We will investigate the issue and will get back to you ASAP.

**Comment by EdwarDDay** [comment]
Is there any update?

**Comment by robertoestivill** [comment]
@mzelzoghbi @Muhammadyoussef I noticed the issue has `pending-feedback` but the latest status is that you will investigate in. 
Is there anything missing ?

**Comment by amrbrkt** [comment]
Hi @EdwarDDay, 
Sorry for being late in replies, If you still have the issue would you please record a video of it?

**Comment by EdwarDDay** [comment]
Hi @amrbrkt, here comes a video with the [sample app](https://github.com/EdwarDDay/InstabugTest).

https://user-images.githubusercontent.com/4127904/105848560-6ca48880-5fdf-11eb-8b68-c602eed3e3d3.mp4

**Comment by amrbrkt** [comment]
Hi @EdwarDDay 
This issue has been fixed and is coming to our next release within couple of weeks, However you can use the following snapshot immediately
• Snapshot version: 10.9.0.3360-SNAPSHOT
Add these to your app-level `build.gradle` file to grab snapshot:
```gradle
dependencies {
  implementation 'com.instabug.library:instabug:10.9.0.3360-SNAPSHOT'
}
```
```gradle
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

I'm closing this issue now, but please, don't hesitate to reopen it if you have any further enquiries.
