### ISSUE TITLE
Prefix Instabug resources so they do not override accidentally app resources.

### ISSUE THREAD

**Issue by dmarin** [Instabug/Instabug-Android#306]
### Steps to Reproduce the Problem
In any sample app using Instabug
Create a resource called `ic_close.xml` and use it

### Expected Behavior
The custom ic_close icon should be displayed in the app

### Actual Behavior
The Instabug ic_close is used.

As per
https://developer.android.com/studio/projects/android-library#Considerations
Android libraries ideally should have a custom prefix to avoid these sort of issues.
Note: The resource is not overridden by the app since in Instabug is defined as a png and the app defines it as an android vector

Gradle version 6.4
Android Gradle plugin: 3.6.3

**Comment by mzelzoghbi** [comment]
Hello @dmarin  Thanks for reporting this.
We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
``` 
implementation 'com.instabug.library:instabug:9.1.4.9-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😃

**Comment by dmarin** [comment]
That was quick :). Thanks a lot @mzelzoghbi I can confirm I can not reproduce this issue with the Snapshot.

**Comment by carstenhag** [comment]
Hello, so is this already merged/released?

**Comment by Muhammadyoussef** [comment]
Hello @carstenhag,

Not yet. This will be included in the next release. 

For now, you can watch our [releases page](https://github.com/instabug/instabug-android/releases) to get notified whenever this fix makes it to a stable release.

**Comment by carstenhag** [comment]
Thanks! Interestingly for us it's also not overridden, as we also use an ic_close **.xml**.
