### ISSUE TITLE
FATAL ERROR 2

### ISSUE THREAD

**Issue by KORuL** [Instabug/Instabug-Android#309]
### Actual Behavior
Crash then start
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
implementation 'com.instabug.library:instabug:9.1.5'
### Android Version
all
### Device Model
all
### [Optional] Project That Reproduces the Issue
![image](https://user-images.githubusercontent.com/19871487/82575093-ad1a4f80-9b90-11ea-9563-f0daab2ec573.png)

**Comment by mzelzoghbi** [comment]
closing this as it duplicates #308
