### ISSUE TITLE
Instabug not triggering on screenshot 

### ISSUE THREAD

**Issue by ghost** [Instabug/Instabug-Android#310]
### Steps to Reproduce the Problem

Add instabug to react native project.

### Expected Behavior

On Asus Zenfone 4 Max running Android 8.1.0, the instabug trigger for screenshot should work.

### Actual Behavior

On Asus Zenfone 4 Max running Android 8.1.0, the instabug trigger for screenshot does not work. The shake trigger works though.

### Instabug integration code

```
RNInstabugReactnativePackage instabug =  new RNInstabugReactnativePackage.Builder(INSTABUG_BETA_TOKEN, MainApplication.this)
                             .setInvocationEvent("screenshot", "shake")
                             .setPrimaryColor("#1D82DC")
                             .setFloatingEdge("left")
                             .setFloatingButtonOffsetFromTop(250)
                             .build();
```

### SDK Version

9.0.7

### React Native, iOS and Android Versions

React Native: 0.59.9
Android: 8.1.0

### Device Model

Asus Zenfone 4 Max - ASUS_X00ID

**Comment by AliAbdelfattah** [comment]
@arindam-heynugget @KevinNugget are you still encountering the issue in the latest version? If so could you verify the other invocation methods are working on that device please?

**Comment by amrbrkt** [comment]
We are closing this issue, please feel free to reopen it.
