### ISSUE TITLE
Swipe left gesture not working 

### ISSUE THREAD

**Issue by ValeriiMamo** [Instabug/Instabug-Android#312]
I develop a fragment-based app with Google's navigation component. 

### Steps to Reproduce the Problem
1. Start the app, the first fragment is shown.
2. Check left swipe gesture - works.
3. Navigate to another fragment (`NavController.navigate(...)` is called).
4. Try left swipe gesture.

### Expected Behavior
Instabug alert dialog is shown.

### Actual Behavior
No Instabug alert dialog is shown.
P.S. When onStart is called for a fragment again then Instabug alert dialog became working again till the navigation to another fragment. 

### Instabug integration code
Performed inside Application's 'onCreate` method.
```
Instabug.Builder(application, "TOKEN")
          .setInvocationEvents(TWO_FINGER_SWIPE_LEFT)
          .build()
Instabug.setWelcomeMessageState(DISABLED)
Instabug.setDebugEnabled(true)
```

### SDK Version
9.1.5

### Android Version
Android 10

### Device Model
Google Pixel 2

**Comment by mzelzoghbi** [comment]
Hello @ValeriiMamo, Thanks for reporting this.
We tried to reproduce the issue but unfortunately, we couldn't. Can you provide us with a sample app with the issue to help us debug the issue faster?

Thanks

**Comment by MahmoudAmin39** [comment]
Hi @ValeriiMamo 
I will close this issue for now for long inactivity. Please feel free to re-open it.
Thanks for understanding 🙏
