### ISSUE TITLE
[Request] Builder with Context parameter instead of Application

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [Instabug/Instabug-Android#314]
### Steps to Reproduce the Problem

Right now, we only have `Instabug` constructors which receives `Application`. On my company, we follow a good practice of wrapping third party SDK into its own module.

When working on the `Instabug` wrapper, I realized it only have constructors which receives `Application` (`Instabug.Builder`), but then calls a local constructor which receives the `Context`.

Could we have a public constructor which receives `Context` and, if necessary, you guys could check if it is an `Application Context`?

### SDK Version

9.1.5

**Comment by Muhammadyoussef** [comment]
Hello @guilherme-pereira-ifood,

Right now, Instabug is designed to be initialized only once and that should happen as early as possible. One of the reasons of having an `Application` class as a parameter is to ensure early initialization and to apply some stability measures. This might change in the future but right now this is step is essential.

**Comment by amrbrkt** [comment]
Hello @guilherme-pereira-ifood 

We are considering your request and will let you know if there are any updates. 
Closing this for now.
