### ISSUE TITLE
ANR on "com.instabug.library.internal.storage.cache.user.a.a(UserDbHelper.java:40)"

### ISSUE THREAD

**Issue by raymondctc** [Instabug/Instabug-Android#316]
### Steps to Reproduce the Problem
App frozen randomly

### Expected Behavior
No freeze

### Actual Behavior
App frozen sometimes

### Instabug integration code
```
    private fun initInstaBug(application: Application) {
        if (TestUtils.isRunningTest()) return
        Instabug.Builder(application, application.getString(R.string.instabug_app_id))
                .setInvocationEvents(InstabugInvocationEvent.NONE)
                .build()
        Replies.setPushNotificationState(Feature.State.ENABLED)
        Instabug.setDebugEnabled(!AppBuildConfig.App.IS_RELEASE)
        Instabug.setPrimaryColor(ResourcesCompat.getColor(resources, R.color.under9_theme_black, null))
        // Arguments:initialScreenshot, extraScreenshot, galleryImage & ScreenRecording
        BugReporting.setAttachmentTypesEnabled(false, true, true, true)
        Surveys.setShouldShowWelcomeScreen(true)
        Chats.setState(Feature.State.DISABLED)
        CrashReporting.setState(Feature.State.DISABLED)
    }
```

### SDK Version
9.1.5

### Android Version
Android 10

### Device Model
Nokia 7 Plus

### [Optional] Project That Reproduces the Issue

ANR Log
[anr_2020-06-18-21-59-50-998.txt](https://github.com/Instabug/Instabug-Android/files/4799089/anr_2020-06-18-21-59-50-998.txt)

**Comment by carstenhag** [comment]
Fixed according to https://github.com/Instabug/Instabug-Android/releases/tag/9.1.6 :D.

**Comment by MahmoudAmin39** [comment]
Hi @raymondctc ,
Thank you for reporting this issue. Please accept our apologies for facing it.
If possible, please upgrade to our Sdk latest version `9.1.6` and and let us know whether or not this issue is still happening. 🙏

**Comment by MahmoudAmin39** [comment]
Hi @raymondctc,
I will close the issue for now. Please feel free to reopen this issue if you encountered this again.
Thank You :blush:
