### ISSUE TITLE
Invoke bug reporting multiple times within a specific time

### ISSUE THREAD

**Issue by zsoltbakos** [Instabug/Instabug-Android#318]
Hello,

We have integrated Instabug with our Android app quite a while ago, and recently we noticed that the Bug Reporting screen is shown only once within ~15 seconds. If we unintentionally close the screen and try to invoke it again, nothing happens, if it was closed in less than ~15 seconds. It works fine on iOS, so I believe it is rather a bug than a feature.

### Steps to Reproduce the Problem
Invoke bug reporting screen multiple times within 15 seconds

### Expected Behavior
Show bug reporting screen every time when the above code is called

### Actual Behavior
Bug reporting screen is shown only if it is closed at least 15 seconds ago (or never shown since app has started)

### Instabug integration code
`
    public void invokeBugReporter() {
        BugReporting.show(BugReporting.ReportType.BUG);
    }
`

### SDK Version
9.1.0, 9.1.5

### Device Model
Samsung Galaxy Tab Active2, Nokia 7 Plus

### Android Version
Android 8.1.0 (Samsung), Android 10 (Nokia)

**Comment by mzelzoghbi** [comment]
Hi  @zsoltbakos , 
We tried the above scenario and everything worked fine, Can you share with us a sample project with the issue? or try to reproduce the issue on our sample app.

Thank You!

**Comment by MahmoudAmin39** [comment]
Hi @zsoltbakos ,
I will close this issue for now for long inactivity. Please feel free to re-open it.
Thanks for understanding 🙏
