### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.instabug.library.internal.storage.cache.InMemoryCache.getValues()' on a null object reference

### ISSUE THREAD

**Issue by wegileShashankRawat** [Instabug/Instabug-Android#325]
Hi,
Instabug integration code

Gradle;

implementation 'com.instabug.library:instabug:9.1.4'

Java:

try {
            new Instabug.Builder(this, getResources().getString(R.string.instabug_app_token))
                    .setInvocationEvents(isShake ? InstabugInvocationEvent.SHAKE : InstabugInvocationEvent.NONE)
                    .setInstabugLogState(DISABLED) // Disbale crash reporting, as we have Google Analytics.
                    .build();

            BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK);

            Instabug.enable();
            CrashReporting.setState(DISABLED);
        }catch (Exception e){
            e.printStackTrace();
        }

SDK Version : 29

Device version : Android P, Android Q

Device Model : samsung Galaxy S10, S10e, Note9, Note10+, S9, S9+, S8, A51,
                         LG G6, V35 ThinQ, Q7+, G7 ThinQ,
                         HUAWEI Mate 20 Pro,
                         OnePlus 7 Pro

Log:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.instabug.library.internal.storage.cache.InMemoryCache.getValues()' on a null object reference
       at com.instabug.survey.cache.SurveysCacheManager.migrateOldCacheToDb(SurveysCacheManager.java:4)
       at com.instabug.survey.SurveyPlugin$e.run(SurveyPlugin.java:9)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.instabug.library.util.threading.b$a.run(PriorityThreadFactory.java:8)
       at java.lang.Thread.run(Thread.java:919)

Kindly let me know how to fix this issue? I am getting this crash for almost all my app's users

**Comment by MahmoudAmin39** [comment]
Hi @wegileShashankRawat ,
Thank you for reporting this issue. Please accept our apologies.
We have this issue fixed on our latest SDK version `9.1.6`
Thanks 🙏

**Comment by MahmoudAmin39** [comment]
Hi @wegileShashankRawat,
I will close this issue for now. Please feel free to re-open it if you encountered this again.
Thank you 😊
