### ISSUE TITLE
Add "Feature Requests" window to the instabug shake window

### ISSUE THREAD

**Issue by carstenhag** [Instabug/Instabug-Android#326]
### Expected Behavior
1. User shakes phone to create an improvement
2. Optionally,
     1. we can either transmit private improvements to the Feature Requests 
     2. **we can make "Improvement" open the Feature Requests page of Instabug!**
3. We have a great overview!

We would prefer the second solution. Seems to be the easiest to integrate.

### Actual Behavior
1. User shakes phone to create an improvement
2. They think that it's a public feature request, but it's private
3. We have a problem there, because we can't transmit these to the feature requests.

(We have a button opening the FeatureRequests on one screen.)

### Instabug integration code

```kotlin
        Instabug.Builder(this, ResourcesHelper.getString(R.string.INSTABUG_SECRET))
                .setInvocationEvents(
                    InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT
                )
                .build()


        FeatureRequests.show()

```

### SDK Version
9.1.6

### Android Version
not relevant

### Device Model
not relevant

**Comment by carstenhag** [comment]
We would also like to have this on iOS :D Should I also post the same ticket there?

**Comment by Korazy** [comment]
Hey @carstenhag 
Thanks for reaching out with this! No need to open a separate ticket for iOS, but your feedback is very much so appreciated here. 

I’ll be forwarding this to our product team, and if there are any changes here, you’ll be the first to know :)
