### ISSUE TITLE
What's the alternative to Crashlytics.logException ?

### ISSUE THREAD

**Issue by valeriyo** [Instabug/Instabug-Android#328]
I'm migrating from Crashlytics, and can't find a way to programmatically log an error to Instabug - equivalent to `Crashlytics.logException`, or newer `FirebaseCrashlytics.recordException` -- https://firebase.google.com/docs/reference/android/com/google/firebase/crashlytics/FirebaseCrashlytics#recordException(java.lang.Throwable) 

What am I missing?

**Comment by valeriyo** [comment]
There is also `Bugsnag.notify` https://docs.bugsnag.com/platforms/android/reporting-handled-exceptions that does what I need.

**Comment by mzelzoghbi** [comment]
Hi @valeriyo, You can check out our [docs](https://docs.instabug.com/docs/android-reporting-crashes#manual-crash-reporting) for manual crash/error reporting APIs.

Please let us know if you need any further help.

Thank You!

**Comment by valeriyo** [comment]
My advice - improve your docs. Why did you put "non-fatal error" or "handled exception" reporting inside the "Crash Reporting" section - by definition, that's not a crash if it's handled. Bye.
