### ISSUE TITLE
[Feature Request] Initialize instabug latter

### ISSUE THREAD

**Issue by rlinoz** [Instabug/Instabug-Android#331]
### Steps to Reproduce the Problem
Integrate Instabug using the screenshot invocation event.

### Expected Behavior
I want to be able to postpone instabug initalization in order to ask the permission latter.

### Actual Behavior
When using screenshot invocation event the permission dialog pops-up immediately when the user opens the app.

### Instabug integration code
```
 Instabug.Builder(this, INSTABUG_APP_TOKEN)
            .setInvocationEvents(InstabugInvocationEvent.SCREENSHOT)
            .build()
```

### SDK Version
9.1.6

### Android Version
Any version

### Device Model
Any model

**Comment by MahmoudAmin39** [comment]
Hi @rlinoz,
Unfortunately, We currently don't support late Sdk Initialization. To serve your case, you can do the following:

1. Initialize Instabug as usual in `Application.onCreate()` in a disabled state using `Instabug.Builder(context, "appToken").setInvocationEvents(InstabugInvocationEvent.NONE).build(Feature.State.DISABLED)`
2. Ask the user for Permission
3. If permission granted, then call `Instabug.enable()`

Please let us know if you have any further feedback or query 🙏 
Thank you

**Comment by rlinoz** [comment]
Hi @MahmoudAmin39 ,

I didn't find a way to set invocation events after instabug is built.

What invocation events will be set when I call `Instabug.enable()`?

**Comment by MahmoudAmin39** [comment]
Hi @rlinoz, 
Thank you for reaching out.
After enabling Instabug via `Instabug.enable()` you can use `BugReporting.setInvocationEvents()`

Please let us know if you have any further feedback or query 🙏
Thank you
