### ISSUE TITLE
NullPointerException on java.lang.String com.instabug.library.internal.storage.cache.Cache.getId()

### ISSUE THREAD

**Issue by IgorMaineti** [Instabug/Instabug-Android#335]
### Steps to Reproduce the Problem

No specific steps to reproduce this issue.

### Expected Behavior

The app shouldn't crash.

### Actual Behavior

The app is crashing with the following stack trace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.instabug.library.internal.storage.cache.Cache.getId()' on a null object reference
       at com.instabug.survey.cache.SurveysCacheManager.migrateOldCacheToDb(SurveysCacheManager.java:16)
       at com.instabug.survey.SurveyPlugin$e.run(SurveyPlugin.java:9)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.instabug.library.util.threading.b$a.run(b.java:8)
       at java.lang.Thread.run(Thread.java:764)
```

### Instabug integration code
``` 
       Instabug.Builder(this, INSTABUG_APP_TOKEN)
            .setInvocationEvents(InstabugInvocationEvent.NONE)
            .build(Feature.State.DISABLED)

        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
```

### SDK Version

9.1.7

### Android Version

9

### Device Model

 Brand: samsung
Model: Galaxy S9
Orientation: Portrait

**Comment by MahmoudAmin39** [comment]
Hi @IgorMaineti,
Thank you for reporting this issue. We will on it and get back to you ASAP 🙏

**Comment by MahmoudAmin39** [comment]
Hi @IgorMaineti,
We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
```
implementation 'com.instabug.library:instabug:9.1.8.2816-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.
Thank You :smiley:
