### ISSUE TITLE
Instabug logs occupying 440 MB of app storage

### ISSUE THREAD

**Issue by carstenhag** [Instabug/Instabug-Android#338]
### Steps to Reproduce the Problem
1. Use app with instabug integration, do some InstabugLog.d() calls, etc
2. Look at `/storage/emulated/0/Android/data/com.xyz.packagename/files/instabug/logs/`, there's a text file in there that seems to grow larger and larger. It seems to be reset sometime, but in my case the file was modified last 10 days ago and was about 440 MB in size. 

### Expected Behavior
Logs are sent to Instabug, if anything it should only store InstabugLog.d logs and not everything (440MB?!) or the logs should be limited to some MB. 

### Actual Behavior
User may delete the app as it used nearly 600 MB, with only 130 MB occupied on our side. 

### Instabug integration code
*Make sure to remove your app token.*
Don't have it at hand currently, but normal instabug integration + 3 InstabugLog.d calls. The instabug logs only get called like 5 times per app usage, so it's not getting called thousands of times. 

### SDK Version
That app version likely used 9.1.5 or 9.1.6.

### Android Version
10

### Device Model
OnePlus 5

**Comment by AndrewMorsillo** [comment]
I think this has affected my app as well. I've had users complain that the app uses 2+ gigabytes of storage but I've never been able to track it down (the app is only 30mb). This sounds like the same issue.

**Comment by carstenhag** [comment]
I have now extracted 14MB of logs (seems like it does get reset from time to time) from the device.  
It seems encoded or encrypted in some way.

**Comment by MahmoudAmin39** [comment]
Hi @carstenhag and @AndrewMorsillo 
Thanks for reporting this issue. Please accept our apologies for any inconvenience that you encounter using our Sdk.
Please note that this issue will be fixed in our next release.
Thanks for your understanding 🙏

**Comment by carstenhag** [comment]
@MahmoudAmin39 thanks for the update :). Can you please tell us whether this bug is fixed with `10.0.0`?

**Comment by mzelzoghbi** [comment]
@carstenhag yes, this issue has been fixed on 10.0.0.
Please give it a try and let us know if you faced any further issues.

Thank You!
