### ISSUE TITLE
Crash at BitmapUtils.java line 7

### ISSUE THREAD

**Issue by pish11010** [Instabug/Instabug-Android#342]
got crash report after version up to 10.0.0 (from 9.1.8).

```
BitmapUtils.java line 7
com.instabug.library.util.BitmapUtils$b.run
```

```
Fatal Exception: java.lang.IllegalStateException: Can't compress a recycled bitmap
       at android.graphics.Bitmap.checkRecycled(Bitmap.java:383)
       at android.graphics.Bitmap.compress(Bitmap.java:1504)
       at com.instabug.library.util.BitmapUtils$b.run(BitmapUtils.java:7)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.instabug.library.util.threading.b$a.run(b.java:8)
       at java.lang.Thread.run(Thread.java:764)
```

### Steps to Reproduce the Problem
Run App

### Expected Behavior
Run without crash

### Actual Behavior
Crash

### Instabug integration code
MultiDexApplication::onCreate
```
Instabug.Builder(this, token)
      .setInvocationEvents(InstabugInvocationEvent.NONE)
      .build()
    Instabug.setUserAttribute("UUID", uuid)
    Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
```

Gradle
```
def instabug = [:]
instabug.version = '10.0.0'
instabug.runtime = "com.instabug.library:instabug:${instabug.version}"
deps.instabug = instabug
```
```
implementation deps.instabug.runtime
```

### SDK Version
10.0.0

### Android Version
Android 8, 9, 10

### Device Model
Any Android device

**Comment by Muhammadyoussef** [comment]
Hi @pish11010,

That is quite unfortunate to hear, and I highly apologize for any sort of inconvenience you are running into. I created a snapshot for you that has the fix; please give it a try and let me know if you still face any issues.
```
implementation 'com.instabug.library:instabug:10.0.0.4899-SNAPSHOT'
```
To consume the snapshot you will need to add the following to your app `build.gradle` as well
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This snapshot is completely safe to use and has no debug code at all.

**Comment by pish11010** [comment]
Hello @Muhammadyoussef 
I will try the snapshot in next release.
Thanks.

**Comment by Muhammadyoussef** [comment]
@pish11010 Awesome! For now, you can watch our [releases page](https://github.com/instabug/instabug-android/releases) to get notified whenever this fix makes it to a stable release. **ETA:** Within the coming 2 weeks.
