### ISSUE TITLE
crash at com.instabug.library.core.ui.BaseFragmentActivity.onCreate  line 7

### ISSUE THREAD

**Issue by aligamal-dev** [Instabug/Instabug-Android#344]
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.a64bit.simswitcher/com.instabug.survey.ui.SurveyActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.instabug.survey.ui.i.h.c.a: could not find Fragment constructor
android.app.ActivityThread.performLaunchActivity

Caused by java.lang.NoSuchMethodException
init []
com.instabug.library.core.ui.BaseFragmentActivity.onCreate

### Steps to Reproduce the Problem

when showing survey 

### Expected Behavior
The app should not crash

### Actual Behavior
App crashes randomly on Production 
### Instabug integration code

implementation 'com.instabug.library:instabug:9.1.7'

 new Instabug.Builder(this, "token")
                .setInvocationEvents(InstabugInvocationEvent.NONE)
                .build();

### SDK Version

9.1.7

### Android Version
all versions

**Comment by Muhammadyoussef** [comment]
Hi @aligamal-dev 

I highly apologize for any sort of inconvenience you are running into. Would you be able to provide a sample project that reproduces the issue? Also, the list of dependencies you have in both your app-level and project-level `build.gradle`

**Comment by amrbrkt** [comment]
Hi @aligamal-dev , 
I'm closing this issue, please don't hesitate to reopen and help us to reproduce it if you still facing it.
