### ISSUE TITLE
IllegalStateException on instabug sqlite database when running tests - RxJava 2 edition

### ISSUE THREAD

**Issue by carstenhag** [Instabug/Instabug-Android#347]
*This ticket is very similar to #340*. 

### Steps to Reproduce the Problem
Enable unit tests to run RxJava 2 TestSchedulers

### Expected Behavior
No exceptions from Instabug

### Actual Behavior
Thousands of exceptions caused by instabug, causing out of memory issues on pipeline

Logs, see https://gist.github.com/carstenhag/aef18f7f18cd2f0680c6b0bf57e26bef or 
[instabuglogs.log](https://github.com/Instabug/Instabug-Android/files/5429012/instabuglogs.log)

### SDK Version
Instabug 10.0.1

### Android Version
target & compile sdk 30

**Comment by carstenhag** [comment]
Ping @Muhammadyoussef as you had fixed it the last time I think :D

**Comment by Muhammadyoussef** [comment]
Hello @carstenhag, unfortunately this [fix](https://github.com/Instabug/Instabug-Android/issues/340#issuecomment-705645781) did not make it to `10.0.1` as it was a hotfix. It's currently in our release pipeline and is expected to be released within this coming week.

Until then, I've created an updated snapshot for you. please give it a try and let me know if you still face any issues.

```
implementation 'com.instabug.library:instabug:10.0.1.3074-SNAPSHOT'
```

To consume the snapshot you will need to add the following to your app `build.gradle` as well
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This snapshot is completely safe to use and has no debug code at all.

**Comment by carstenhag** [comment]
Thanks, this issue is also fixed (tried out at `com.instabug.library:instabug:10.0.1.6487-SNAPSHOT`)
