### ISSUE TITLE
Can't disable FeatureRequests

### ISSUE THREAD

**Issue by maras93** [Instabug/Instabug-Android#348]
Disabling "**Request a feature**" option by `setState` doesn't work. 

### Steps to Reproduce the Problem
Shake device

### Expected Behavior
"**Request a feature**" shouldn't be displayed

### Actual Behavior
"**Request a feature**" is displayed

### Instabug integration code
```
Instabug.Builder(application, token, InstabugInvocationEvent.SHAKE).build()
BugReporting.setReportTypes(BugReporting.ReportType.FEEDBACK, BugReporting.ReportType.BUG)
FeatureRequests.setState(Feature.State.DISABLED)
```
### SDK Version
10.0.1, 9.1.6 - doesn't work
9.1.4 - works

### Android Version
11

### Device Model
Google Pixel 3a XL

### Screenshot
![request a feature x](https://user-images.githubusercontent.com/12697488/98574017-b66eb400-22b7-11eb-8dc1-92e30e441fc7.png)

**Comment by Muhammadyoussef** [comment]
Hi @maras93,

That is quite unfortunate to hear, and I highly apologize for any sort of inconvenience you are running into. 

I tried reproducing the issue but everything seems to work as expected. Would you be able to provide a sample project that reproduces the issue?

**Comment by maras93** [comment]
I'm back with more findings 😄 
I've created fresh empty project with one empty Activity and Application class, nothing more.
```
class InstabugApp : Application() {

    override fun onCreate() {
        super.onCreate()
        Instabug.Builder(this, "token", InstabugInvocationEvent.SHAKE).build()
        FeatureRequests.setState(Feature.State.DISABLED)
    }
}
```

Using version **9.1.4**, after shake I've received the following result, "**Request a feature**" is not present but on **9.1.6** it is. 
Following result can be achieved only after fresh install of the app. Firstly I installed app with 9.1.4 version, afterwards I installed app with 9.1.6 version (without any uninstall/clear cache in between) and "**Request a feature**" wasn't presented, that suggest it works correctly but after uninstall and fresh install with 9.1.6 unwanted entry was presented. Looks like an issue with caching? 
<table style="width:100%">
  <tr>
    <th>9.1.4</th>
    <th>9.1.6</th> 
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/12697488/99558758-5917e880-29c4-11eb-80fc-e042722050d7.png" width="200"></td>
    <td><img src="https://user-images.githubusercontent.com/12697488/99558614-34237580-29c4-11eb-88d0-d183cb56980b.png" width="200"></td>
  </tr>
</table>

I was able to reproduce it on: 
- Google Pixel 3x XL, Android 11,
- Samsung Galaxy S8, Android 8.0.0, 
- Samsung Galaxy S10+, Android 10. 

On Huawei P8 Lite with Android 8 it works correctly even after fresh install so not all devices are affected.

**Comment by maras93** [comment]
@Muhammadyoussef Please let me know if provided details are sufficient.

**Comment by amrbrkt** [comment]
Hello @maras93 
Would you please enable the SDK logs using `Instabug.setDebugEnabled(true)`, reproduce the issue and share the logs with us? 🙏

**Comment by IslamMohamady** [comment]
Hi @maras93 
I will close the issue for now as there are no interactions for awhile. But i strongly recommend using the latest SDK version which is 10.8.1. If you need more help, Feel free to reopen the issue or open a new one
