### ISSUE TITLE
Refactoring the screenshot annotation view

### ISSUE THREAD

**Issue by 2x2xplz** [Instabug/Instabug-Android#35]
Any chance you would make available the more basic, v.2 annotation tools? I find that everything added in v.4 -- zoom tool, blur tool, and the ability to zoom and move drawings -- lessens the user experience. The new "features" add unnecessary complexity and confusion, and some users give up on submitting a bug report. Perhaps some app developers find them useful, I am not saying to eliminate the new tools, just to make the simpler, v.2 interface -- just a pen, color choice and undo -- available, something like `setBasicAnnotationScreen(boolean)`. (you can even drop the color chooser, and allow devs to set the pen color in code). Thank you.

**Comment by DevHossamHassan** [comment]
Hello @2x2xplz,
Thank you so much for your suggestion, Actually, we added those features to enhance the user experience as an example:
Blur sensitive data
```
Blur the parts of the screen that have sensitive data when reporting any bugs. This will enable you to send only what you want to work on without worrying about any shared information.
```
<img src="https://cloud.githubusercontent.com/assets/6613841/26662388/d788fa56-4683-11e7-9440-049127f7e481.png" width="160">

Magnify and Zoom
```
Zoom on the bug reported before even sending it to make sure that what's reported is the most focused on from the other side.
```
<img src="https://cloud.githubusercontent.com/assets/6613841/26662413/fd2e905e-4683-11e7-9f34-63ac916eb94e.png" width="160">


Just to fully understand what you're trying to do, why do you need the more basic, v.2 annotation tools?

**Comment by 2x2xplz** [comment]
These are nice, useful options. But some applications have many very inexperienced users, and these extra buttons confuse them. Not every app has sensitive data to be blurred, or needs magnification. I'm seeking the EASIEST way for users to send a screenshot -- and every additional button or feature is a distraction. Think about a point-and-shoot camera vs a manual SLR, sure the SLR has more features and options but if you aren't a professional photographer, the point-and-shoot with just 1 button, in auto mode, is the better choice.

**Comment by DevHossamHassan** [comment]
Thank you so much for your suggestion @2x2xplz I got what you mean. I really appreciate it. 🙏 
I forwarded your suggestion to our `Product` team 
They might need to get in touch with you if you don't mind this.

**Comment by NadineMansour** [comment]
@2x2xplz I renamed the issue to help everyone catch its topic easily. 
We’ll disable the automatic shape detection and the users will have the freedom to pick if they want to stick to the free hand drawn shapes or the ones detected by Instabug. It should be ready and released in a month.

**Comment by 2x2xplz** [comment]
I appreciate you working on this... however giving the user an additional option (choose between free hand shapes or pre-detected) is the opposite of what I am requesting. Ideally, the developer should choose what options/features to give the users. Some people want to let the users do lots of stuff, but others (like myself) want fewer features, like with v.2.

**Comment by NadineMansour** [comment]
@2x2xplz The team is working on some new changes in the bug reporting UI and experience. We would really appreciate opening an email thread with you to share our plans and take your feedback including the annotation step.
Can you please email us at support@instabug.com and reference this issue?
