### ISSUE TITLE
Disable audio record permission

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#350]
Is there any way to disable the audio recording feature, so that we don't have to ask for audio recording permission?

**Comment by mzelzoghbi** [comment]
Hi @eygraber 
Thanks for reporting this, You can add the following snippet to your AndroidManifest file and it will remove the audio permission for your
```
    <uses-permission
        android:name="android.permission.RECORD_AUDIO"
        tools:node="remove" />
```
I will close this for now Please feel free to re-open it again if you need any further help.
