### ISSUE TITLE
Receiving iOS style push notifications on Android for the Replies feature

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#351]
When I send a message to a user through a bug report, the device receives an iOS push notification, and no notification is displayed on the device. The device receives:

```
{"aps":{"alert":"You have an unread message from App team"},"IBGHost":true}
```

**Comment by Muhammadyoussef** [comment]
Hi @eygraber,

I highly apologize for any sort of inconvenience you are running into. I can see you already have a ticket open with our support team, we'll be working with them to have this resolved for you. It may take some time, so we suggest to keep an eye on the support thread you have opened and we'll update you through there. Our support team will keep you updated
