### ISSUE TITLE
Replies are not reset after logging out the user

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#352]
I identify my users using an Id with `Instabug.identifyUser(id, "")` when they log in. If my user has reply conversations, and then logs out, I call `Instabug.logoutUser()`.

If another user logs in (calling `Instabug.identifyUser(otherId, "")` and then calls `Replies.show()`, the first users conversations are shown.

**Comment by Muhammadyoussef** [comment]
Hi @eygraber,

I can see you already have a ticket open with our support team. I'll close this issue for now and our support team will keep you updated through the support thread you have opened.

Thanks for understanding :)
