### ISSUE TITLE
Reply Conversations timestamp is 24 hour time

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#353]
Chat message's timestamps are showing in 24 hour time, even if the device is set to 12 hour time.

Also the list of conversations should really show the timestamp of the most recent message for a conversation; not just the date.

**Comment by Muhammadyoussef** [comment]
Hi @eygraber,

I can see you already have a ticket open with our support team. I'll close this issue for now and our support team will keep you updated through the support thread you have opened.

Thanks for understanding :)
