### ISSUE TITLE
Package names are obfuscated in 10.1.0, causing collisions

### ISSUE THREAD

**Issue by joost-klitsie** [Instabug/Instabug-Android#356]
### Steps to Reproduce the Problem
Have a project that includes Instabug 10.1.0 and another project, e.g. Here maps 3.17

### Expected Behavior
Project compiles just fine

### Actual Behavior
Getting a compile error:
```
Duplicate class a.a.a.a found in modules jetified-HERE-sdk-runtime (:HERE-sdk:) and jetified-instabug-crash-10.1.0-runtime (com.instabug.library:instabug-crash:10.1.0)
Duplicate class a.a.a.b found in modules jetified-HERE-sdk-runtime (:HERE-sdk:) and jetified-instabug-crash-10.1.0-runtime (com.instabug.library:instabug-crash:10.1.0)
```

### SDK Version
10.1.0
(9.1.8 compiles just fine)

### Android Version
--

### Device Model
--

If I am correct, the problem lies in instabug-crash:10.1.0 if I look at that. In the classes.jar I see the regular `com.instabug.*` but also `a.a.a.*` . Libraries should not have their package names obfuscated exactly because of this issue, and I will also file a bug at HERE maps for the same reason.

**Comment by mzelzoghbi** [comment]
Hello @joost-klitsie 
Thanks for reporting this, 

We created a **SNAPSHOT** that should fix the issue.
``` 
 implmentation 'com.instabug.library:instabug:10.1.0.1-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all and this fix will be included in our next official release that should come out in the next few days.

I will close this issue for now, please feel free to reopen it again if you have any further issues.

Thank You 😃

**Comment by joost-klitsie** [comment]
@mzelzoghbi that was fast!!! Thanks a lot! :)
