### ISSUE TITLE
Screen recording alert - Android

### ISSUE THREAD

**Issue by guykogus** [Instabug/Instabug-Android#361]
Whenever triggering Instabug, whether by calling `Instabug.show()` or any of the invocation events, the first thing that pops up is some disclaimer about recording the screen. It doesn't matter if you dismiss the popup or press Start recording, afterwards you get the correct popup that offers to either report a bug or send a suggestion.
Is there any way to avoid this initial popup appearing?

### Steps to Reproduce the Problem
Shake the device.

### Expected Behavior
The popup offering to report a bug or send a suggestion appears.

### Actual Behavior
The screen recording popup is displayed. Once it's dismissed the correct popup appears.

### Instabug integration code
```Kotlin
InstabugFlutterPlugin().start(
    this,
    BuildConfig.INSTABUG_TOKEN,
    arrayListOf(InstabugFlutterPlugin.INVOCATION_EVENT_SHAKE)
)
```

### SDK Version
`instabug_flutter: ^9.1.6`

### Android Version
30

### Device Model
Google Pixel 3A

**Comment by IslamMohamady** [comment]
Hi @guykogus
Please try again on the latest release. I will close this issue now and if you need more help, Feel free to reopen the issue or create a new one
