### ISSUE TITLE
Screenshot invocation does not work on the first app launch

### ISSUE THREAD

**Issue by ArneKoeckeritz** [Instabug/Instabug-Android#365]
Hello
I have the problem that the invocation by Screenshot of Instabug does not work directly on the first app start after a clean install.

### Steps to Reproduce the Problem

0. Have a app which is configured...
- Invocation by screenshot

1. Start your app after a clean install.
- No Permission granted
- No data stored

2. Show the Storage Permission Dialog and let the user grant the permission.

3. Take a screenshot
- Nothing happens

4. Kill the app and restart it.

5. Take a screenshot
- Instabug reporting dialog gets invoked

### Expected Behavior

Instabug reporting Dialog gets invoked when doing a screenshot.

### Actual Behavior

Nothing happens.

### Instabug integration code

```
Instabug.Builder builder = new Instabug.Builder((Application) pApplication.getApplicationContext(), "secret");
builder.setInvocationEvents(InstabugInvocationEvent.SCREENSHOT);
builder.setConsoleLogState(Feature.State.ENABLED);
builder.setInstabugLogState(Feature.State.ENABLED);
builder.setReproStepsState(State.ENABLED);
builder.setTrackingUserStepsState(Feature.State.ENABLED);
mInstance = builder.build(Feature.State.ENABLED);

BugReporting.setOptions(Option.COMMENT_FIELD_REQUIRED, Option.EMAIL_FIELD_HIDDEN);
BugReporting.setReportTypes(BugReporting.ReportType.BUG);
BugReporting.setScreenshotByMediaProjectionEnabled(true);

Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
Instabug.onReportSubmitHandler(pReport -> attachLogsAndAttributes(pApplication));

if (BuildConfig.BETA)
{
	Instabug.setUserAttribute("build-type", "DEV");
}
else if (BuildConfig.IS_QA_BUILD)
{
	Instabug.setUserAttribute("build-type", "QA");
}
else
{
	Instabug.setUserAttribute("build-type", "LIVE");
}
```

### SDK Version

10.4.1

### Android Version

Android 11, API level 30

### Device Model

Google Pixel 2 XL

**Comment by amrbrkt** [comment]
Thanks s for your report @ArneKoeckeritz, 
We are looking into it, but in the meanwhile, would you please confirm that: 
1. You are initializing the SDK in the application class's `onCreate()` method.
2. You have allowed the storage permission that popped-up in the first app launch. _(An alternative is to allow this permission from the app info/settings)_.

**Comment by amrbrkt** [comment]
Thanks s for your report @ArneKoeckeritz,
We are looking into it, but in the meanwhile, would you please confirm that you are initializing the SDK in the application class's `onCreate()` method.

**Comment by ArneKoeckeritz** [comment]
Hi @amrbrkt 
Thx for your reply.

In or production App we didn't initialized the SDK in the Applications onCreate(). This we did since years because we do not want to have SDK's initializing which are not needed for the user. Unfortunately at some point or version in time we noticed this bug which is annoying our QA team.

After changing the implementation to initialize the SDK in Applications onCreate everything works fine, no bugs.

But this is not the way it can work for use because of four concerns.

1. We don't know if our app will pass the Google Play review in this configuration.
2. We don't want an SDK increase the apps cold boot time and eating memory which is not used by normal user and only used by QA team.
3. We don't if any user data will be collected by the SDK. We have to be safe for european GDPR.
4. We don't know if the SDK's DISABLE configuration will solve any of our three previous concerns.

Can you please give a statement for these concerns.
We need to find a solution which either solves all concerns or create a feature request for the Instabug SDK to support lazy initialization.

**Comment by amrbrkt** [comment]
Hi @ArneKoeckeritz 
Thanks for sharing these concerns with us, we do appreciate your input and we love to clear all of them. 

First of all, we are Google Play review safe, we are used in thousands of live apps with no reviewing issues, and we are super fast resolving them if any appeared. 

Second, in our latest releases, the SDK is not initialized in the application main thread, which means that we have the minimal impact on the application's cold startups. 

Third, to avoid that you can initialize the SDK in a disabled state first, then enable it in the runtime whenever needed. 
Please pass `Feature.State.DISABLED` to the builder as follow while the initialization 
```
        Instabug.Builder(this, "APP_TOKEN_KEY")
            .build(Feature.State.DISABLED)
            ```
And use the API `Instabug.enable()` to enable the SDK. 

I hope this answer has cleared all of your concerns, and we still love to receive any further enquiries, please don't hesitate getting back to us and reopen the thread.
