### ISSUE TITLE
Instabug is not responding to show() 

### ISSUE THREAD

**Issue by Kaushl** [Instabug/Instabug-Android#369]
### Steps to Reproduce the Problem
Integrate the Instabug SDK and initialize the SDK in the application class's onCreate() method.
As well in Activity but in both case the dialog never shows up 

This is the error log  :
2021-03-17 15:51:53.308 15305-15305/com.example.instabug E/API Checker: Instabug API {BugReporting.show} was called while the SDK is disabled. To enable it, please call Instabug.enable().
 Tried the Sample app too that too didn't work for me 
Link for sample app : https://github.com/Instabug/Instabug-Android

### Expected Behavior
Instabug reporting dialog should display 
### Actual Behavior
Nothing happens.
### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
Tested in 10.4.1, probably this happens in all
### Android Version
Tested in Android 9
### Device Model
One Plus 6T and onePLus 7 pro

**Comment by yaraabdelhakiim** [comment]
Hi @Kaushl 

Thanks for reaching out, we're looking into it.
But in the meanwhile can you please confirm that you're using a valid app token while initializing our SDK.

**Comment by Kaushl** [comment]
Hi Instabug/Instabug-Android,

There was some issue with decrypting the API key once I figure it out it
works fine
Thanks for the pointer, But still I want to move this initialization part
to activity instead of Application OnCreate
Have a call with the Instabug team tomorrow.

Regards
Kaushal

**Comment by yaraabdelhakiim** [comment]
Hi @Kaushl 

By design, the SDK works only when you initialize it in the Application class however you can disable the SDK and re-enable it in your activity using `Instabug.disable()` and `Instabug.enable()`.
