### ISSUE TITLE
Broad Storage Access and requestLegacyExternalStorage

### ISSUE THREAD

**Issue by MikkelHJorgensen** [Instabug/Instabug-Android#371]
Google has begun issuing warnings in Play Console for apps using the `requestLegacyExternalStorage` flag. This is a cause of great concern, as it _may_ affect the ability to be listed on and/or updating apps in Play Store, though these types of messages are fairly cryptic as usual, unfortunately. Here's a few helpful references:
[Google Support - Use of All File Access](https://support.google.com/googleplay/android-developer/answer/10467955)
[Reddit Discussion on said message](https://www.reddit.com/r/androiddev/comments/mqzls8/ominous_scoped_storage_warning_messages/)

Our app itself has no direct use of the `requestLegacyExternalStorage` flag, and seemingly it only emerges from the Instabug library.

### From Google Play Console
> **Starting 5 May, you must let us know why your app requires broad storage access**
> 
> We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of one or more of your app bundles or APKs.
> 
> Developers with apps on devices running Android 11+ must use scoped storage to give users better access control over their device storage. To release your app on Android 11 or newer after 5 May, you must either:
> 
> - Update your app to use more privacy-friendly best practices, such as the storage access framework or Media Store API
> - Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from 5 May
> - Remove the All files access permission from your app entirely
> 
> For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.
> 
> Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.

### Perspective on Options
- _Update your app to use more privacy-friendly best practices, such as the storage access framework or Media Store API_

By far the preferred approach.

- _Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from 5 May_

This is a road we do not want to go down. That would greatly decrease the value of using the Instabug library.

- _Remove the All files access permission from your app entirely_

I'm gonna take a wild guess and say this is probably not possible.

What can we expect from the Instabug Library going forward in terms of the above and on a related note, scoped storage in relation to the Android 11 requirements coming up in November 2021?

**Comment by mzelzoghbi** [comment]
Hi @MikkelHJorgensen 
Thanks for reporting this, We are aware of this issue and we started working on a fix that will be shipped ASAP, however, as a workaround you can add this to your application's manifest file as a temp work around then revert it when our fix is out.
```
 android:requestLegacyExternalStorage="false"
        tools:replace="requestLegacyExternalStorage"
```

We will keep you updated once the fix is ready. 

Thank You

**Comment by MikkelHJorgensen** [comment]
Thank you @mzelzoghbi 

I considered using that workaround as well. However, that would mean we're opting in to using scoped storage. Will that not cause issues with some functionality in the Instabug library on some Android versions? Maybe you have some insight on that as well?

**Comment by mzelzoghbi** [comment]
@MikkelHJorgensen if you are targetting android 11 it won't cause any issues for now.

**Comment by MikkelHJorgensen** [comment]
We are currently targeting Android 10. For reference, this is the documentation I'm looking at:
[Android storage use cases and best practices](https://developer.android.com/training/data-storage/use-cases)

**Comment by mzelzoghbi** [comment]
we request the `requestLegacyExternalStorage` to capture the changes in the screenshot directory to be able to invoke the SDK using the SCREENSHOT gesture, However targeting android 11 and removing this line should work without issues.

If you are not ready yet to target android 11 and not using the SCREENSHOT gesture, you could keep targeting android 10 and use the work around and all features will work as expected.

**Comment by MikkelHJorgensen** [comment]
Thank you for the clarification on this @mzelzoghbi. I'll dig into whether we can begin targeting Android 11, alternatively disabling the screenshot gesture for now.

**Comment by timc-mediamonks** [comment]
@mzelzoghbi can you give an estimation of when the fix will be shipped?

**Comment by mzelzoghbi** [comment]
@timc-mediamonks the fix will make it to production early next Week.

**Comment by timc-mediamonks** [comment]
@mzelzoghbi can you give an updated estimation?

**Comment by mzelzoghbi** [comment]
@timc-mediamonks We are in the middle of the release process, it should be available in a couple of hours, I will update you once it is out.

**Comment by mzelzoghbi** [comment]
@timc-mediamonks 10.5.0 has been release, please give it a try and let us know if you faced any further issues.

Thanks

**Comment by nickithompson** [comment]
hi @mzelzoghbi was wondering if you could elaborate on the changes that were taken in 10.5.0 to resolve? is the screenshot feature usable without this permission?

**Comment by mzelzoghbi** [comment]
We changed some of our logic to depend on native APIs to get the needed SDK files mainly the screenshot and removed the legacy storage permissions for Android versions greater than 28. 

So answering your question the Screenshot should be usable on all SDK versions without any issues.
