### ISSUE TITLE
NullPointerException Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference com.instabug.anr.c.a

### ISSUE THREAD

**Issue by wangyangkeCeler** [Instabug/Instabug-Android#373]
At present, 70 times of online users have crash, affecting 47 users. Please help me solve the problem as soon as possible. Thank you!
### Steps to Reproduce the Problem
no 
### Expected Behavior 
APP doesn't crash
### Actual Behavior
APP   crash
 Instabug.Builder(application, "b************8")
            .setInvocationEvents(InstabugInvocationEvent.SHAKE)
            .setReproStepsState(State.ENABLED_WITH_NO_SCREENSHOTS)
            .setInstabugLogState(Feature.State.ENABLED)
            .setTrackingUserStepsState(Feature.State.ENABLED)
            .build()
*Make sure to remove your app token.*

### SDK Version
10.4.3
### Android Version
android 7,android 8,android 9(30%),android 10,android 11
### [Optional] Project That Reproduces the Issue
error Log:
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
com.instabug.anr.c.a (c.java:8)
com.instabug.anr.b.run (b.java:6)

**Comment by mzelzoghbi** [comment]
Hello @wangyangkeCeler  Thanks for reporting this.
We created a **SNAPSHOT** that should fix the issue
``` 
implementation 'com.instabug.library:instabug:10.4.3.3112-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

And the fix will be included in our next official release coming in few days.
Thank You 😃

**Comment by wangyangkeCeler** [comment]
Thank you for your reply and help. After team discussion, we still decide to return to the stable version of 10.3.0 first, and we will replace it after the release of the official version of the fix pack

**Comment by wangyangkeCeler** [comment]
> Hello @wangyangkeCeler Thanks for reporting this.
> We created a **SNAPSHOT** that should fix the issue
> 
> ```
> implementation 'com.instabug.library:instabug:10.4.3.3112-SNAPSHOT'
> ```
> 
> you will need to add these lines to your app **build.gradle** before your dependencies
> 
> ```
> repositories {
>     ....
>     maven {
>         url "https://oss.sonatype.org/content/repositories/snapshots"
>     }
> }
> ```
> 
> This **SNAPSHOT** is completely safe to use and has no debug code at all.
> 
> And the fix will be included in our next official release coming in few days.
> Thank You 😃
