### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by RazibKani** [Instabug/Instabug-Android#374]
Hi, I have issue when integrating Instabug APM on my project.

When I apply `apply plugin: 'instabug-apm'`, I got this error when build project:
`> javassist.CannotCompileException: [source error] no such class: com.instabug.library.apmokhttplogger.InstabugAPMOkhttpInterceptor
`

I'm using Instabug version `10.4.3`

Any suggestion to solve this issue?
Thank you

**Comment by mzelzoghbi** [comment]
Hi @RazibKani 
Thanks for reporting this, 
Can you try to add our APM interceptor manually to your app's `build.gradle` file
```
implementation 'com.instabug.library:instabug-apm-okhttp-interceptor:10.4.3'
```

Let us know if it solved the issue 🙏🏻 

Thank you

**Comment by RazibKani** [comment]
Hi @mzelzoghbi,

Thank you for your reply, and that's solve my problem.

But, I want to ask something.
What is the different between
`com.instabug.library:instabug-apm-okhttp-interceptor` and `com.instabug.library:instabug-with-okhttp-interceptor`?

Am I need add both of them? or enough with `com.instabug.library:instabug-apm-okhttp-interceptor`?

**Comment by mzelzoghbi** [comment]
@RazibKani 
`com.instabug.library:instabug-apm-okhttp-interceptor` is used for the network calls to be captured by our APM product. 

`com.instabug.library:instabug-with-okhttp-interceptor` is used for capturing network calls and attaching them to our CrashReporting / BugReporting products.

If you want to capture all your network logs in the 3 Products, you will need to add both dependencies.

I hope that answered your questions.

**Comment by RazibKani** [comment]
@mzelzoghbi Noted and Thank you..
