### ISSUE TITLE
java.lang.ClassNotFoundException: com.instabug.ndkcrash.NDKCrashPlugin

### ISSUE THREAD

**Issue by VincentJoshuaET** [Instabug/Instabug-Android#382]
What dependency am I missing?

**Comment by iadcialim** [comment]
Encountering the same thing using
`implementation 'com.instabug.library:instabug:10.7.1'`

**Comment by VincentJoshuaET** [comment]
> Encountering the same thing using
> `implementation 'com.instabug.library:instabug:10.7.1'`

You need `implementation("com.instabug.library:instabug-ndk-crash:10.7.1")`
