### ISSUE TITLE
Crash with "Don't keep activities mode"

### ISSUE THREAD

**Issue by ihor-bezeka** [Instabug/Instabug-Android#384]
*java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sixt.leasing.sl.debug/com.instabug.survey.ui.SurveyActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.instabug.survey.ui.i.k.b.a: could not find Fragment constructor*

### Steps to Reproduce the Problem
1. Turn on "Don't keep activities" mode in the "Developer options"
2. Show survey
3. Close app with "Home" button
4. Open the app again

### Expected Behavior
Should not crash happen

### Actual Behavior
Crash happens

### Instabug integration code
*Instabug.Builder(androidApplication(), token)
            .setInvocationEvents(InstabugInvocationEvent.NONE)
            .setInAppMessagingState(Feature.State.ENABLED)
            .build().also {
                Instabug.setPrimaryColor(androidContext().getColor(R.color.orange))
            }*

### SDK Version
10.0.1

### Android Version
All versions versions

### Device Model
All devices

**Comment by MShannan** [comment]
@ihor-bezeka Thanks for reporting this.
I highly recommend updating to our latest version 10.5.1 , as it has the fix for this issue.
I'm closing this for now, but please feel free to reopen it if you still facing the same issue.

**Comment by ihor-bezeka** [comment]
@MShannan thanks for the reply.
