### ISSUE TITLE
Failed to use legacy storage on Android 12 after upgrading to version 10.5.1

### ISSUE THREAD

**Issue by raymondctc** [Instabug/Instabug-Android#386]
### Steps to Reproduce the Problem
- Upgraded from 10.4.2 to 10.5.1

### Expected Behavior
- `WRITER_EXTERNAL_STORAGE` should not have the attribute `android:maxSdkVersion=28` appended. 

### Actual Behavior
- `WRITER_EXTERNAL_STORAGE` has the attribute `android:maxSdkVersion=28` appended, which causes our app not functioning and it's not expected.

Left is the `AndroidManifest.xml` after upgrading to 10.5.1, right is the `AndroidManifest.xml` from 10.4.2. (Decompiled from our APK)
![image](https://user-images.githubusercontent.com/13764117/121623463-5127af00-caa2-11eb-8b88-51e5087843a1.png)

### Instabug integration code
- N/A

### SDK Version
- 10.5.1

### Android Version
- Android 12

### Device Model
- N/A

**Comment by MShannan** [comment]
Hello @raymondctc 
Thanks for reporting this, according to recent Google / Android privacy changes, they [restricts](https://support.google.com/googleplay/android-developer/answer/10467955) the use of [All files access](https://developer.android.com/preview/privacy/storage#all-files-access) to apps that target Android 11 (API level 30) and above. 
We recommend using the [privacy friendly alternatives](https://developer.android.com/about/versions/11/privacy/storage) (e.g., [MediaStore API](https://developer.android.com/training/data-storage/shared/media), or [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider)) and if you think these apis are not sufficient for your app to provide its core functionality, you can use this snippet 
```
<uses-permission
    android:name="android.permission.WRITE_EXTERNAL_STORAGE"
    tools:remove="android:maxSdkVersion"/>
```
to override `WRITE_EXTERNAL_STORAGE` permission in your AndroidManifest.xml and Google Play may provide a temporary exception for your app according to [this](https://support.google.com/googleplay/android-developer/answer/10467955#intended&exceptions&invalid&alternatives&).

Let us know if that worked for you or you have any concerns,
Thanks.

**Comment by amrbrkt** [comment]
We are closing this issue for now, please don't hesitate to get back to us if you still have any problem.

**Comment by SudoPlz** [comment]
@MShannan Hey there,
we just found out that created problems with our file picker in our app.
I'm wondering why are you declaring `maxSdkVersion` at all?
Are there any plans to implement those Android privacy changes to your library and remove `maxSdkVersion`?

This looks major to me.

Thank you

**Comment by vegerot12** [comment]
> Hello @raymondctc Thanks for reporting this, according to recent Google / Android privacy changes, they [restricts](https://support.google.com/googleplay/android-developer/answer/10467955) the use of [All files access](https://developer.android.com/preview/privacy/storage#all-files-access) to apps that target Android 11 (API level 30) and above. We recommend using the [privacy friendly alternatives](https://developer.android.com/about/versions/11/privacy/storage) (e.g., [MediaStore API](https://developer.android.com/training/data-storage/shared/media), or [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider)) and if you think these apis are not sufficient for your app to provide its core functionality, you can use this snippet
> 
> ```
> <uses-permission
>     android:name="android.permission.WRITE_EXTERNAL_STORAGE"
>     tools:remove="android:maxSdkVersion"/>
> ```
> 
> to override `WRITE_EXTERNAL_STORAGE` permission in your AndroidManifest.xml and Google Play may provide a temporary exception for your app according to [this](https://support.google.com/googleplay/android-developer/answer/10467955#intended&exceptions&invalid&alternatives&).
> 
> Let us know if that worked for you or you have any concerns, Thanks.

Upon adding that line. Remove Android max version. I'm not able to generate release build. Getting this error. "The prefix tools for attribute tools:remove associated with an element type uses-permission is not bound". Can someone help. Anyone faced this issue. ?
