### ISSUE TITLE
How to find YOUR_APP_TOKEN?

### ISSUE THREAD

**Issue by AhmadullahSaikat** [Instabug/Instabug-Android#390]
### Instabug integration code
*Make sure to remove your app token.*

**Comment by amrbrkt** [comment]
Hello @AhmadullahSaikat, 
You can easily find your application token in your dashboard settings > SDK integration page. 
Please check the following screenshot. 
![image](https://user-images.githubusercontent.com/7738296/127464454-920afb71-dab3-43fd-a0a2-5f2653f95174.png)

**Comment by amrbrkt** [comment]
I'll close this issue for now, please don't hesitate to get back to us if you have any more enquires.
