### ISSUE TITLE
Screen recording icon disappear after screen recording starts

### ISSUE THREAD

**Issue by haidersyed** [Instabug/Instabug-Android#395]
### Steps to Reproduce the Problem
1. Shake the device, tap on suggest improvement / bug report
2. Tap on screen recording,  pop up disappears and screen recording(red icon) appears.
3. Tap that record icon instantly after pop up disappears.
4. it will start recording for couple of seconds like 0 to 7 and red icon disappears.
5. if we background and foreground the app, red icon becomes visible but with stopped recording.
6. This is happening continuously.

###Note
There is a case when we start recording after 14 seconds with dismissal of pop up it works.(as expected)

### Expected Behavior
it should record screen normally without the weird behaviour.
### Actual Behavior
recording disappears.

### SDK Version
10.8.0 (xamarin nauget)

### Android Version
Android 10

### Device Model
S9+, S10+

**Comment by amrbrkt** [comment]
Hi @haidersyed 

Thanks for reporting that. 
May I ask you for a screen recording of the issue showing the both cases? Also is it happening on any other Android versions?

**Comment by haidersyed** [comment]
@amrbrkt I cannot expose the screen recording right now due to company policy. Currently i have Samsung s9+ , s10+ with android 10

**Comment by amrbrkt** [comment]
@haidersyed 
This will be very helpful, also would you enable the SDK debug logs using the API `Instabug.setDebugEnabled(true)` and share the logs too?

**Comment by haidersyed** [comment]
@amrbrkt if you follow the above mentioned steps with the devices, i am sure you will be able to reproduce the issue.

**Comment by amrbrkt** [comment]
@haidersyed, 
I'm not able to reproduce this issue on my side, were you able to prepare the sample app?
