### ISSUE TITLE
Can't disable FeatureRequests

### ISSUE THREAD

**Issue by VEndymionV** [Instabug/Instabug-Android#396]
Disabling "Request a feature" option by `FeatureRequests.setState(Feature.State.DISABLED)` doesn't work in Instabug SDK version `10.1.1`, and also is not working when app is updated to version with latest Instabug SDK `10.8.1`.

It is the same issue as in: https://github.com/Instabug/Instabug-Android/issues/348

### Steps to Reproduce the Problem

1. Install app with Instabug SKD version `10.1.1` and disabled FeatureRequests by `FeatureRequests.setState(Feature.State.DISABLED)`,
2. FeatureRequest is enabled,
3. Bump SDK version to latest one `10.8.1`, update the app with latest Instabug SDK,
4. FeatureReuqest is still enabled, all configuration options like primary color are also not set correctly.

Note1: Sometimes even after the app update everything is working fine, there is no 100% repro, but I've attached logs with repro.
Note2: When the app is clean installed (the previous version uninstalled) with Instabug SDK `10.8.1` everything seems working fine.

### Expected Behavior

FeatureRequest feature should be disabled on both versions (`10.1.1` and `10.8.1`).

### Actual Behavior

FeatureRequest is enabled.

### Instabug integration code

```
Instabug.Builder(application, config.token, InstabugInvocationEvent.SHAKE)
Instabug.setPrimaryColor(config.themeColor)
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
Instabug.setCustomTextPlaceHolders(config.textPlaceholders.toInstabugCustomTextPlaceHolder())
BugReporting.setOptions(Option.COMMENT_FIELD_REQUIRED)
BugReporting.setReportTypes(BugReporting.ReportType.FEEDBACK, BugReporting.ReportType.BUG)
FeatureRequests.setState(Feature.State.DISABLED)
BugReporting.setState(Feature.State.DISABLED)
```

### SDK Version

`10.8.1`

### Android Version

10

### Device Model

Huawei P30 Pro

### Logs

SDK version `10.1.1`, fresh install, repro steps 1-2:
[logs_10.1.1_fresh_install.txt](https://github.com/Instabug/Instabug-Android/files/6974898/logs_10.1.1_fresh_install.txt)

SDK version `10.8.1`, after an app update, repro steps 3-4:
[logs_10.8.1_update.txt](https://github.com/Instabug/Instabug-Android/files/6974900/logs_10.8.1_update.txt)

SDK version `10.8.1`, fresh install, working fine:
[logs_10.8.1_fresh_install.txt](https://github.com/Instabug/Instabug-Android/files/6974901/logs_10.8.1_fresh_install.txt)

**Comment by lucas-csmotion** [comment]
Just want to bump for visibility. We've found the exact same issue in `10.8.1` where after an update to this version all of the same configuration errors come out in the logs and none of the config for colors are working. We can't downgrade either since we need this version of Instabug for Android 12 support for the exported flag fix in the manifest

**Comment by amrbrkt** [comment]
Hi @lucas-csmotion 
We are very sorry for that, would you please reach out our support team through intercom chat bubble on the dashboard, And I'll ensure I'll handle this issue immediately by myself.

**Comment by VEndymionV** [comment]
@amrbrkt Why did you close this issue?

**Comment by amrbrkt** [comment]
@VEndymionV would you please reach out to our support team through the intercom chat bubble on the dashboard? 
To go further with this issue we need to know more about the circumstances and I'd advise doing so through a private channel, such as Intercom.  

Thanks in advance and sorry for any inconvenience.

**Comment by VEndymionV** [comment]
There are no special circumstances. Everything is described and it's easy to reproduce it even on a fresh project with only Instabug SDK. I've also attached logs.

**Comment by amrbrkt** [comment]
@VEndymionV 
I see that and I thank you for the shared details, however, we may need to check your application token, pricing plan .. etc. 
Kindly reach out to the support or feel free to share this info with me directly on `abarakat@instabug.com`
