### ISSUE TITLE
Take a screenshot results in a blank screen

### ISSUE THREAD

**Issue by josancamon19** [Instabug/Instabug-Android#400]
Hi, it's Joan from @conchalabs. 

### Steps to Reproduce the Problem
- Open the ConchaLabs app (please share an email so that I can add you to the firebase distribution list) 
- Bug reporting - take a screenshot, before and during the login screens it works. But after that, You get a blank screen.
- Sign up through Gmail or manual
- Sign in
- Try to report a bug and try to take a screenshot
### Expected Behavior
- A miniature of the screenshot taken
### Actual Behavior
- A blank screen - [https://cln.sh/j24LNn](video)
### Instabug integration code

```kotlin
 Instabug.Builder(this, "")
            .setViewHierarchyState(Feature.State.ENABLED)
            .setInvocationEvents(InstabugInvocationEvent.FLOATING_BUTTON)
            .setReproStepsState(State.ENABLED)
            .setUserDataState(Feature.State.ENABLED)
            .setUserEventsState(Feature.State.ENABLED)
            .setConsoleLogState(Feature.State.ENABLED)
            .setInAppMessagingState(Feature.State.ENABLED)
            .setTrackingUserStepsState(Feature.State.ENABLED)
            .build()

        Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
        BugReporting.setScreenshotByMediaProjectionEnabled(false)

        BugReporting.show(BugReporting.ReportType.BUG)
        BugReporting.show(BugReporting.ReportType.FEEDBACK)
        BugReporting.show(BugReporting.ReportType.QUESTION)
```
### SDK Version
- 10.9.0
### Android Version
Android version: 10
Current version: QSBS30.62-17-17-10
### Device Model
Motorola One Action
### [Optional] Project That Reproduces the Issue
Please share your email so that I can add you to the beta firebase distribution project.

**Comment by josancamon19** [comment]
The simplest integration code fails too.
```kotlin
Instabug.Builder(this, "")
    .setInvocationEvents(InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT)
    .build()
```

**Comment by josancamon19** [comment]
Tried most 10.x versions and 9.1.8, same for all of them.

**Comment by amrbrkt** [comment]
@josancamon19 
Thanks for reaching out to us, and for the details report. 
Do you use any HW accelerated views in the screens after the login? If yes, we won't be able to capture the screenshots unless you enable the media projection screenshot by 
```kotlin 
        BugReporting.setScreenshotByMediaProjectionEnabled(true)
```

Also, feel free to add me for the distribution list by the email: abarakat@instabug.com if still needed.

**Comment by josancamon19** [comment]
Hi, No, we don't use HW views, anyways I tried with ```BugReporting.setScreenshotByMediaProjectionEnabled(true)``` and the same blank screen.

Thanks, @amrbrkt  just added you to the distribution list.

**Comment by amrbrkt** [comment]
@josancamon19 
I've got the invite and I downloaded, signed up the app and see your issue now. 
I'd ask you to re-share a debug build after enabling the SDK logs and allowing screenshot attachment to bug reporting using the following APIs: 
```kotlin 
Instabug.setDebugEnabled(true)
BugReporting.setAttachmentTypesEnabled(true, true, false, false)
```

**Comment by josancamon19** [comment]
Thanks, @amrbrkt just sent you a new version.

**Comment by amrbrkt** [comment]
@josancamon19 
I can't see the new build on the Firebase App Tester, the existing is the first one you shared.

**Comment by josancamon19** [comment]
Sorry, it should be available now

**Comment by amrbrkt** [comment]
@josancamon19 
Would you be able to reproduce it on a sample app? 
Try to simulate your UI implementation as much as you can, and share the source code it with us.

**Comment by Bashayer-reda** [comment]
Hello @josancamon19 , I hope you have a lovely day. We will close this one, but if you still encounter any issues, please feel free to reopen it anytime. Thank you.
