### ISSUE TITLE
NullPointerException: java.lang.String java.lang.String.trim()

### ISSUE THREAD

**Issue by asamoylenko** [Instabug/Instabug-Android#409]
### Steps to Reproduce the Problem

We haven't been able to reproduce it so far, but we are keep seeing this crash in different production releases of our app. We've tried several versions of the SDK and all of them have this issue. It is TOP 1 crash in our Android app at the moment.

### Expected Behavior

No crash

### Actual Behavior

Crash:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	 at com.instabug.library.user.a.v(SourceFile:1)
	 at com.instabug.library.model.State$Builder.getUserName(SourceFile:1)
	 at com.instabug.library.model.State$Builder.build(SourceFile:30)
	 at com.instabug.library.model.State.getState(SourceFile:2)
	 at m7.a.<init>(SourceFile:2)
	 at m7.a$a.a(SourceFile:5)
	 at com.instabug.anr.b.run(SourceFile:7)
```

### Instabug integration code

Initializing Instabug
```
        new Instabug.Builder(this, BuildConfig.INSTABUG_APP_TOKEN)
                .setInvocationEvents(InstabugInvocationEvent.NONE)
                .build();
```
and setting user id once we have it
```
Instabug.setUserAttribute(USER_ID_KEY, id.toString())
```

### SDK Version

10.10.0

### Android Version

- Android 10
- Android 11
- Android 12

### Device Model

- Motorola motorola one action
- Samsung Galaxy Z Fold3 5G (SM-F926U)
- Samsung Galaxy S21 Ultra 5G (SM-G998U)
- Samsung Galaxy S9+ (SM-G965U)
- LGE G8X ThinQ (LM-G850)
- LGE LG G7 ThinQ (LM-G710)
- LGE LG Stylo 5+ (LM-Q720)
- Motorola moto g power (2021)
- Motorola motorola edge plus
- Samsung Galaxy A02s (SM-A025V)
- Samsung Galaxy A10e (SM-A102U)
- Samsung Galaxy A11 (SM-A115A)
- Samsung Galaxy A21 (SM-A215U)
- Samsung Galaxy A32 5G (SM-A326U)
- Samsung Galaxy A51 5G (SM-A516U)
- Samsung Galaxy Note10+ (SM-N975U1)
- Samsung Galaxy S10e (SM-G970U)
- Samsung Galaxy S20 FE 5G (SM-G781U)
- Samsung Galaxy S20 FE 5G (SM-G781W)
- Samsung Galaxy S20+ 5G (SM-G986U)
- Wingtech REVVL V+ 5G

**Comment by MShannan** [comment]
@asamoylenko Thanks for reporting this, We're looking into it.

**Comment by asamoylenko** [comment]
Hey @MShannan, any updates on this? This is still a big issue for us

**Comment by MShannan** [comment]
@asamoylenko Please accept our apologies for the inconvenience we may have caused. We are currently working on a fix for this and I'll make sure to notify you whenever its done :)

**Comment by MShannan** [comment]
@asamoylenko We are sorry for the late reply. 
We created a SNAPSHOT that should fix the issue.
`implmentation 'com.instabug.library:instabug:10.11.0.3594-SNAPSHOT'`

you will need to add these lines to your app build.gradle before your dependencies

repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
This fix will be included in our next official release.
I will close this issue for now, please feel free to reopen it again if you have any further issues.
Thank You 🙂

**Comment by asamoylenko** [comment]
Thanks @MShannan!
