### ISSUE TITLE
Android 12 - Pending Intent missing FLAG_IMMUTABLE or FLAG_MUTABLE

### ISSUE THREAD

**Issue by lucas-csmotion** [Instabug/Instabug-Android#410]
### Steps to Reproduce the Problem
This is a bug in production being logged from Instabug Chats with Pending Intents without the required mutable/immutable flags set for Android 12

```
Fatal Exception: java.lang.IllegalArgumentException
au.com.csmotion.placie: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

android.app.PendingIntent.checkFlags (PendingIntent.java:375)
android.app.PendingIntent.getActivity (PendingIntent.java:408)
com.instabug.chat.g.b.a (b.java:119)
com.instabug.chat.g.b.a (b.java:39)
com.instabug.chat.ChatPlugin$b.run (ChatPlugin.java:1)
com.instabug.library.util.threading.PoolProvider$e.run (PoolProvider.java:3)
android.os.Handler.handleCallback (Handler.java:938)
```

### Expected Behavior
Instabug does not crash

### Actual Behavior
Instabug crashes

### SDK Version
Occurs on 10.9.1, and 10.10.0

### Android Version
Android 12 (31)

### Device Model
Pixel 5, Pixel 4

This is not the first compatibility issue with Android 12 we've come across with Instabug, it would be good to get some support for this new version or we may have to end up disabling the service on this version of Android to avoid further crashes

**Comment by yaraabdelhakiim** [comment]
@lucas-csmotion Thanks for reporting this, we're looking into it.

**Comment by yaraabdelhakiim** [comment]
@lucas-csmotion We are sorry for the inconvenience,
We created a SNAPSHOT that should fix the issue.
`implmentation 'com.instabug.library:instabug:10.11.0.3619460-SNAPSHOT'`

you will need to add these lines to your app build.gradle before your dependencies

```
repositories {
....
maven {
url "https://oss.sonatype.org/content/repositories/snapshots"
}
}
```
Also this fix will be included in our next official release.
I am closing this issue for now, please feel free to reopen it again if you have any further issues.
Thank You 🙏

**Comment by lucas-csmotion** [comment]
@yaraabdelhakiim Love your work, thanks for getting on this so quickly. Will add the snapshot for out next update 👍

**Comment by lucas-csmotion** [comment]
@yaraabdelhakiim sorry if I'm missing something- I can't find `10.11.0.3619460-SNAPSHOT` on sonatype. There are some similar snapshots there, `10.11.0.1.3622-SNAPSHOT`, `10.11.0.3579-SNAPSHOT`, `10.11.0.3594-SNAPSHOT`, `10.11.0.3615-SNAPSHOT`, but nothing with a build number as high as `3619460`. Can you point me in the right direction of the intended snapshot build for this issue please?

**Comment by yaraabdelhakiim** [comment]
@lucas-csmotion We are very sorry for the inconvenience, please use `0.11.0.6305-SNAPSHOT`

**Comment by lucas-csmotion** [comment]
@yaraabdelhakiim No stress at all, that's working for us. Thanks again for that 👍

**Comment by Suboforme** [comment]
> @lucas-csmotion We are very sorry for the inconvenience, please use `10.11.0.6305-SNAPSHOT`

i am sorry that i can not implmentation  "com.instabug.library:instabug:10.11.0.6305-SNAPSHOT",

A problem occurred evaluating project ':app'.
> Could not find method implmentation() for arguments [com.instabug.library:instabug:10.11.0.6305-SNAPSHOT] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by Ric17101** [comment]
<img width="1183" alt="Screen Shot 2022-03-04 at 5 19 28 PM" src="https://user-images.githubusercontent.com/10458685/156735442-406a9802-d4e6-4251-bb67-ce3a1777f379.png">

I am getting this Gradle Sync issues
```
Could not GET 'https://repo.gradle.org/artifactory/jcenter/com/instabug/library/instabug/10.11.0.6305-SNAPSHOT/instabug-10.11.0.6305-SNAPSHOT.pom'. Received status code 409 from server: Conflict
Disable Gradle 'offline mode' and sync project
```
