### ISSUE TITLE
Android screenshots/vids are black

### ISSUE THREAD

**Issue by baku-apps** [Instabug/Instabug-Android#413]
### Steps to Reproduce the Problem
Create screen shot with Android

### Expected Behavior
Should see screenshot

### Actual Behavior
Seeing black screen

### Instabug integration code
```
public class CustomFlutterApplication extends FlutterApplication {
  @Override
  public void onCreate() {
    super.onCreate();
    ArrayList<String> invocation_events = new ArrayList<>();
    invocation_events.add(InstabugFlutterPlugin.INVOCATION_EVENT_FLOATING_BUTTON);
    invocation_events.add(InstabugFlutterPlugin.INVOCATION_EVENT_SCREENSHOT);
    InstabugFlutterPlugin instabug = new InstabugFlutterPlugin();
    instabug.start(CustomFlutterApplication.this, "...", invocation_events);
    instabug.setWelcomeMessageMode("WelcomeMessageMode.disabled");
  }
}
```

### SDK Version
v10.11.0

### Flutter, iOS and Android Versions
only Android version

### Device Model
Galaxy 10 plus (but also other models)

**Comment by adamszewe** [comment]
Check if you are disabling the screenshots in your activity/fragment with something similar to:
```
window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
```

as Instabug cannot circumvent this setting on its own.

**Comment by khalid-3lnagar** [comment]
can you please provide a sample app with the issue becauase we can’t reproduce it with the steps provided

**Comment by Bashayer-reda** [comment]
Hello @baku-apps I hope you have a lovely day. We will close this one, but if you still have any issues, please don't hesitate to reopen it anytime. Thank you.
