### ISSUE TITLE
Instabug should provide information/CSV for Google Play Data Safety Form declaration

### ISSUE THREAD

**Issue by dirkam** [Instabug/Instabug-Android#418]
Hi,

Instabug SDK collects and potentially shares lots of data that is/might be considered sensitive.
Google Play requires apps to submit the Data Safety Form that includes data handling of third-party SDKs as well.
**The deadline for this is April, 2022.**

It would be immensely helpful for your customers if you provided the relevant information. Or even better, if you could provide this in the supported CSV format.
It's almost impossible for the developers to fully understand what data Instabug collects, stores and shares.

Here are some links for more information:
[Provide information for Google Play's Data safety section](https://support.google.com/googleplay/android-developer/answer/10787469?hl=en) - Google Play Help Article about the Data Safety Form
[Google Maps SDK guidelines](https://developers.google.com/maps/documentation/android-sdk/play-data-disclosure) - An example of how an SDK can provide this information
[SDK-Privacy-Report](https://github.com/Privado-Inc/SDK-Privacy-Report) - initiative to collect this in CSV format for commonly used third-party SDKs

Thank you

**Comment by mzelzoghbi** [comment]
Hi @dirkam 
Thanks for reporting this, We will give this our top priority and will get back to you ASAP

Thanks 🙏🏻

**Comment by BorysChajdas** [comment]
Yeah, it will be very helpful. We as developers using Instabug SDK don't know which data is collected or shared by your SDK.

**Comment by mzelzoghbi** [comment]
Hi @dirkam @BorysChajdas,
The team has been working on updating the docs to add all the privacy details requested by Google Play and I'm happy to share the details for this can now be found [here](https://docs.instabug.com/docs/play-store-privacy-details)

I'll be closing this ticket, If you have any questions at all regarding it, please re-open it and let us know.

Thanks.

**Comment by dirkam** [comment]
@mzelzoghbi 
Haven't checked it thoroughly but at first it seems to be a decent list. Good job guys, thank you.
