### ISSUE TITLE
Lint check - DataExtractionRules: Missing data extraction rules (10.13.0)

### ISSUE THREAD

**Issue by ZOlbrys** [Instabug/Instabug-Android#419]
### Steps to Reproduce the Problem
Run lint on Android app using Instabug 10.13.0

### Expected Behavior
No checks failed

### Actual Behavior
2 checks failed

Missing <full-backup-content> resource
`<application android:fullBackupContent="@xml/instabug_backup_exclusion" >  `

The attribute android:fullBackupContent is deprecated from Android 12 and higher and may be removed in future versions. Consider adding the attribute android:dataExtractionRules specifying an @xml resource which configures cloud backups and device transfers on Android 12 and higher.
`<application android:fullBackupContent="@xml/instabug_backup_exclusion" >   `

### Instabug integration code
N/A

### SDK Version
10.13.0

### Android Version
N/A

### Device Model
N/A

### [Optional] Project That Reproduces the Issue
N/A

<img width="891" alt="Screen Shot 2022-03-04 at 3 50 31 PM" src="https://user-images.githubusercontent.com/2875924/156839872-459dc4b4-1275-4c38-add6-88e98b604001.png">

**Comment by kareem-waleed** [comment]
@ZOlbrys Sorry for the inconvenience, will check that and get back to you shortly 🙏

**Comment by ZOlbrys** [comment]
Hi @kareem-waleed - any updates on this?  It's still an issue on 11.0.0

**Comment by IslamMohamady** [comment]
Hi @ZOlbrys - This is still not fixed on SDK version 11.0.0. However we will make sure to include it in the next release. I will close the issue for now. If the issue still persists in upcoming releases, feel free to reopen it or open a new one

**Comment by ZOlbrys** [comment]
@IslamMohamady @kareem-waleed this hasn't been addressed in the newest release (11.1.0).  I'll create a new task per the feedback.
