### ISSUE TITLE
How to simulate instabug popup for android if application is using instabug shake event to show popup

### ISSUE THREAD

**Issue by amitkumar3-qa** [Instabug/Instabug-Android#421]
Hi Team,

Our android application uses instabug shake event for android app to show popup to submit feedback. So whenever user shake the android device, a popup will appear in the application for a feedback to submit. From android ui automation testing point of view any idea how this shake feature testing can be automated without manually shaking the device. Any clue for shake events simulation?

Looking forward to hearing from you soon.

Cheers
Amit

**Comment by ZOlbrys** [comment]
Could you inject the method of interaction needed when doing automation testing?  Maybe change it to be done via a button click on the FAB, or some other method?

**Comment by Bashayer-reda** [comment]
hello @amitkumar3-qa We will close this one, but if you still have any issues, please don't hesitate to reopen it anytime. Thank you.
