### ISSUE TITLE
Crash com.instabug.library.networkv2.request

### ISSUE THREAD

**Issue by dung90it** [Instabug/Instabug-Android#424]
### Steps to Reproduce the Problem
i don't know

### Expected Behavior
don't crash

### Actual Behavior
crashes with stack traces :
(Console Logs) 30-03 21:11:22.083  I/System.out( 9425): (HTTPLog)-Static: isSBSettingEnabled false
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at java.lang.Thread.run(Thread.java:923)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.q9$a.run(PriorityThreadFactory.java:5)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.util.threading.b$b.run(PoolProvider.java:2)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.t6$a.run(SessionsSyncManager.java:2)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.x5.a(SessionsRemoteDataSource.java:7)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(NetworkManager.java:5)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(NetworkManager.java:1)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.networkv2.NetworkManager.handleRequest(NetworkManager.java:32)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.x5$a.onFailed(SessionsRemoteDataSource.java:1)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.x5$a.a(SessionsRemoteDataSource.java:4)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.x5.a(SessionsRemoteDataSource.java:7)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(NetworkManager.java:5)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(NetworkManager.java:1)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.networkv2.NetworkManager.handleRequest(NetworkManager.java:32)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.x5$a.onFailed(SessionsRemoteDataSource.java:1)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.x5$a.a(SessionsRemoteDataSource.java:4)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.x5.a(SessionsRemoteDataSource.java:7)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(NetworkManager.java:5)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.networkv2.NetworkManager.doRequestOnSameThread(NetworkManager.java:1)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.networkv2.NetworkManager.handleRequest(NetworkManager.java:32)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.x5$a.onFailed(SessionsRemoteDataSource.java:1)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.x5$a.a(SessionsRemoteDataSource.java:4)
(Console Logs) 30-03 21:11:22.020  E/AndroidRuntime( 9425): 	at com.instabug.library.x5.a(SessionsRemoteDataSource.java:7)

### Instabug integration code
 Instabug.Builder(this@SkynetApp, WebServiceApi.INSTABUG_KEY)
                            .setReproStepsState(State.ENABLED)
                            .setConsoleLogState(Feature.State.ENABLED)
                            .build()
                    BugReporting.setInvocationEvents(InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT)
                    Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)
                    FeatureRequests.setEmailFieldRequired(true, ActionType.REQUEST_NEW_FEATURE)
                    BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK, BugReporting.ReportType.QUESTION)
                    Instabug.setSessionProfilerState(Feature.State.ENABLED)
                    Instabug.setUserAttribute("App Name", "FUELCLOUD")
                    Instabug.setUserAttribute("app_uuid", appId)

### SDK Version
instabug:10.12.0

### Android Version
Android11 (v11)(Level 30)

### Device Model
Samsung Galaxy A51 (SM-A515F),OnePlus ONEPLUS A6013

**Comment by mzelzoghbi** [comment]
Hey @dung90it , Thanks for reporting this.
This issue has been resolved in latest SDK versions, pleaae ugrade to 10.13.0 and feel free to reach out to us if you encounted any further issues.

Thanks.
