### ISSUE TITLE
InstabugNetworkLog Error: "Response body exceeded limit"

### ISSUE THREAD

**Issue by angelina-andronova-xapo** [Instabug/Instabug-Android#426]
### Steps to Reproduce the Problem
Shake the device and check logs.

### Expected Behavior
The Istabug Network log will show Request Body

### Actual Behavior
The Istabug Network log does not show Request Body.
Instead there is an error `InstabugNetworkLog Error: "Response body exceeded limit"` even for empty JSON body and for GET requests.
Response body is shown correctly.
![image](https://user-images.githubusercontent.com/76939802/162949753-019352b3-5297-467a-8bd3-1c15e80daeea.png)

### Instabug integration code
```
    Instabug.Builder(application, KEY_INSTABUG)
            .setViewHierarchyState(Feature.State.ENABLED)
            .setInvocationEvents(reportingGesture)
            .setConsoleLogState(Feature.State.ENABLED)
            .build()
```

### SDK Version
Android SDK version 11.0.0
Dependencies: 
```
com.instabug.library:instabug:$versions.instabug
com.instabug.library:instabug-with-okhttp-interceptor:$versions.instabug
```

### Android Version
OS Level 30

### Device Model
Samsung Galaxy A71 (SM-A715F)

**Comment by MohamedHefny** [comment]
Thanks for reporting this, we will check it and reply back ASAP.

**Comment by MohamedHefny** [comment]
Hey @angelina-andronova-xapo,
Thanks for reporting this, we will check it and reply back ASAP.

**Comment by angelina-andronova-xapo** [comment]
@MohamedHefny Thanks! I forgot to mention that we recently moved BE calls to KMM/Ktor, so maybe it is related to this. Is Instabug KMM-compatible?

**Comment by nguyentuonglong** [comment]
hi @angelina-andronova-xapo I'm am using `InstabugOkhttpInterceptor` in KMM too, I did follow the document here: https://docs.instabug.com/docs/android-logging#logging-okhttp-requests, but no Network Logs have been posted

**Comment by marcorighini** [comment]
@MohamedHefny Do you have some updates? This is impacting the usefulness of the product

**Comment by IslamMohamady** [comment]
Hi @angelina-andronova-xapo Can you please send all the details you mentioned to [contactus@instabug.com](mailto:contactus@instabug.com) so that we can efficiently assist you with this issue? Thanks 🙏
