### ISSUE TITLE
ClassNotFoundException crash

### ISSUE THREAD

**Issue by cathychi** [Instabug/Instabug-Android#429]
Seeing this crash in the latest version of our Android app after adding the Instabug library.

<img width="914" alt="Screen Shot 2022-07-26 at 6 42 20 PM" src="https://user-images.githubusercontent.com/22667502/181142214-2039005d-02e9-4a0d-b837-f9011fa2720d.png">

### Steps to Reproduce the Problem
Unclear

### Expected Behavior
No crash

### Actual Behavior
Crashing

### Instabug integration code
```
private var initializedInstabug = false

override fun start(
    application: Application,
    isDarkTheme: Boolean,
    isInternalBuild: Boolean,
  ) {
    if (!initializedInstabug) {
      // creating Instabug and setting invocation method as shake
      Instabug.Builder(application, instabug_key)
        .setInvocationEvents(InstabugInvocationEvent.SHAKE)
        .build()

      // optional email field. by default email is required
      BugReporting.setOptions(Option.EMAIL_FIELD_OPTIONAL)

      // enable the following attachments types: initialScreenshot, extraScreenshot, galleryImage & ScreenRecording
      BugReporting.setAttachmentTypesEnabled(true, true, true, true)

      // Only enable bug reporting as the prompt option
      BugReporting.setReportTypes(BugReporting.ReportType.BUG)

      //  Disable all non bug reporting features
      CrashReporting.setState(Feature.State.DISABLED)
      APM.setEnabled(false)
      Replies.setState(Feature.State.DISABLED)
      Surveys.setState(Feature.State.DISABLED)
      FeatureRequests.setState(Feature.State.DISABLED)
      Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)

      // UI
      if (isDarkTheme) {
        Instabug.setColorTheme(InstabugColorTheme.InstabugColorThemeDark)
      } else {
        Instabug.setColorTheme(InstabugColorTheme.InstabugColorThemeLight)
      }

      initializedInstabug = true
    }
    Instabug.enable()
  }

  override fun stop() {
    if (initializedInstabug) {
      Instabug.disable()
    }
  }
```

### SDK Version
11.2.0

### Android Version
11

### Device Model
vivo V2102

**Comment by mhashim6** [comment]
Hi, could you provide the integration code as requested?

**Comment by cathychi** [comment]
override fun start(
    application: Application,
    isDarkTheme: Boolean,
    isInternalBuild: Boolean,
  ) {
    if (!initializedInstabug) {
      // creating Instabug and setting invocation method as screenshot
      Instabug.Builder(application, instabug_key)
        .setInvocationEvents(InstabugInvocationEvent.SHAKE)
        .build()

      // optional email field. by default email is required
      BugReporting.setOptions(Option.EMAIL_FIELD_OPTIONAL)

      // enable the following attachments types: initialScreenshot, extraScreenshot, galleryImage & ScreenRecording
      BugReporting.setAttachmentTypesEnabled(true, true, true, true)

      // Only enable bug reporting as the prompt option
      BugReporting.setReportTypes(BugReporting.ReportType.BUG)

      //  Disable all non bug reporting features
      CrashReporting.setState(Feature.State.DISABLED)
      APM.setEnabled(false)
      Replies.setState(Feature.State.DISABLED)
      Surveys.setState(Feature.State.DISABLED)
      FeatureRequests.setState(Feature.State.DISABLED)
      Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED)

      // UI
      if (isDarkTheme) {
        Instabug.setColorTheme(InstabugColorTheme.InstabugColorThemeDark)
      } else {
        Instabug.setColorTheme(InstabugColorTheme.InstabugColorThemeLight)
      }

      initializedInstabug = true
    }
    Instabug.enable()
  }

  override fun stop() {
    if (initializedInstabug) {
      Instabug.disable()
    }
  }

**Comment by mhashim6** [comment]
Hi @cathychi, I see you opened an internal support ticket. Closing this one for now.
