### ISSUE TITLE
Upload a log file

### ISSUE THREAD

**Issue by proxcesumit** [Instabug/Instabug-Android#430]
### Expected Behavior
Is there any way to upload a log file with the UI feedback so in the dashboard we can check that log file also?
Any method to upload file or any workaround.

### Instabug integration code
*Make sure to remove your app token.*

**Comment by mzelzoghbi** [comment]
Hi @proxcesumit, 
Thanks for reaching out. Yes, this is doable by either listening on a callback and [adds the file](https://docs.instabug.com/docs/android-bug-reporting-callbacks#before-sending-a-report) to be sent right before submitting the BugReport/CrashReport or you can use [this](https://docs.instabug.com/docs/android-bug-report-content#extra-attachments) API if it is the file is ready from the beginning of the session and It doesn't require to be collected right before sending the report.

I hope that helps. and feel free to reach out again if you need further help.

Thank you.
