### ISSUE TITLE
InstabugOkhttpInterceptor + Proguard breaks a network request 

### ISSUE THREAD

**Issue by stevie-patreon** [Instabug/Instabug-Android#431]
Our app uses Instabug and OKHttp/AndroidNetworking. Including the `InstabugOkhttpInterceptor` as an `Interceptor` causes one of our image upload requests to fail with `java.net.ProtocolException: unexpected end of stream`

The issue doesn't occur in our build that's not minified. The network request looks like:

```
AndroidNetworking.upload(media.uploadUrl)
            .setTag(requestTag)
            .addMultipartParameter(media.uploadParametersMap)
            .addMultipartFile("file", imageFile)
            .build()
            .setUploadProgressListener(uploadProgressListener)
```

Is Instabug in any way modifying the requests it's intercepting?

### Versions

Instabug: 11.4.1
OkHttp: 4.9.3
AndroidNetworking: 1.0.2

**Comment by Bashayer-reda** [comment]
hello @stevie-patreon We will close this one, but if you still have any issues, please don't hesitate to reopen it anytime. Thank you.
