### ISSUE TITLE
Bug reporting by screenshot invocation isn't working for apps targeting Android 13

### ISSUE THREAD

**Issue by coreywjohnson** [Instabug/Instabug-Android#434]
### Steps to Reproduce the Problem
Integrate Instabug into a project targeting sdkVersion 33
Enable bug reporting invocation by screenshots
Take a screenshot

### Expected Behavior
The bug reporting flow should be invoked when the user takes a screenshot

### Actual Behavior
The flow is not invoked for users on Android 13 when the targetSdkVersion for the project is 33
Likely related to READ_EXTERNAL_STORAGE permission changes 
https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

### Instabug integration code
BugReporting.setInvocationEvents(InstabugInvocationEvent.SCREENSHOT)

### SDK Version
11.5.0

### Android Version
13

### Device Model
Pixel 6 Pro

**Comment by mhashim6** [comment]
Hi @coreywjohnson, thanks a lot for reporting this. We're working on supporting the new granular permissions. I'll update this issue when the fix is released.

**Comment by stevie-patreon** [comment]
Any update on this?

**Comment by mhashim6** [comment]
@stevie-patreon Yes; it’s scheduled to be on the next release. Will update the issue when the release is out.

**Comment by stevie-patreon** [comment]
Great, thanks for the update!

**Comment by friederikewild** [comment]
@mhashim6 Also looking forward to this fix. I just saw there was an update 11.6.0 on Nov 22nd 2022, which was after your message. Is the fix included already in there?

**Comment by mhashim6** [comment]
@friederikewild Hi, It's not included in `11.6.0` I'm afraid. 

There was a blocker on our side. I'll try my best to update you with a date when we have it.

Thanks!

**Comment by friederikewild** [comment]
Thanks for the update @mhashim6. Looking forward to it and good luck

**Comment by pimentones** [comment]
hi @mhashim6 this is negatively impacting our testing process as we need to test on Android 13 due to the number of users adopting that Android version, do you have a timeframe for when you will deliver a fix for this?

**Comment by pimentones** [comment]
@mhashim6 any chance to release a fix before since the main functionality of the app is broken on Android 13?

**Comment by mhashim6** [comment]
@pimentones Feel free to open an internal support ticket; There we can generate a custom snapshot ahead of schedule

**Comment by mhashim6** [comment]
Hi @coreywjohnson, @stevie-patreon, @friederikewild, and @pimentones! I'm glad to tell you our latest release `11.7.0` is out. It adds support to API 33 [amongst other changes](https://github.com/Instabug/Instabug-Android/releases/tag/v11.7.0).

I'll close the ticket for now. Don't hesitate to re-open it if you need any help.
