### ISSUE TITLE
App restart required to apply Instabug InvocationEvents

### ISSUE THREAD

**Issue by muralijoyn** [Instabug/Instabug-Android#436]
### Steps to Reproduce the Problem

**Enable:**
1. Enable Instabug with `InvocationEvents` --> `InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT` 
2. and shake the device without restarting the device and observe bug-report pop-up won't show 
3. shake the device after restarting the app bug-report pop-up will show.

**Disable** 
1. Disable Instabug with `InvocationEvents` --> `InstabugInvocationEvent.NONE`
2. shake the device without restarting the app, a bug report pop-up will show.
3. and shake the device after restarting the app and observe bug-report pop-up won't show 

### Expected Behavior
1. Changes should apply without restarting the app.

### Actual Behavior
1. App restart is required to apply Instabug InvocationEvents

### Instabug integration code
```
package com.test.instabugtest

import android.app.Application
import android.content.Context
import android.content.SharedPreferences
import androidx.core.content.edit
import com.instabug.library.Instabug
import com.instabug.library.invocation.InstabugInvocationEvent

const val KEY_INSTABUG = "Instabug"

class InstabugConfig(
    private val context: Application,
) {
    private val sharedPreferences: SharedPreferences =
        context.getSharedPreferences(this::class.java.simpleName, Context.MODE_PRIVATE)

    var isEnabled
          set(value) {
                sharedPreferences.edit {
                       putBoolean(KEY_INSTABUG, value).commit()
                }
           }
          get() = sharedPreferences.getBoolean(KEY_INSTABUG, false)
    

    fun enable(enable: Boolean) {
            val invocationEvent = if (enable) {
                InstabugInvocationEvent.SHAKE
           } else {
                InstabugInvocationEvent.NONE
           }

           Instabug.Builder(context, context.getString(R.string.instabug_beta_id))
                .setInvocationEvents(invocationEvent)
                .build()

            isEnabled = enable
        }

}
```

```
//Activity
val config = InstabugConfig(this.application)
buttonEnable.setOnClickListener {
      config?.enable( true)
}

buttonDisable.setOnClickListener {
        config?.enable( false)
}
```

### SDK Version

` implementation 'com.instabug.library:instabug:11.5.1'`

### Android Version

```
android {
    compileSdk 32

    defaultConfig {
        applicationId "com.test.instabugtest"
        minSdk 23
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
 ......
}
```

### Device Model

Samsung S21 Ultra (Android 12)

**Comment by IslamMohamady** [comment]
@muralijoyn thanks for reporting the issue. I need to ask you where do you intialize Instabug SDK. Is it in the Application `onCreate()` method or later in an activity?

**Comment by muralijoyn** [comment]
> @muralijoyn thanks for reporting the issue. I need to ask you where do you intialize Instabug SDK. Is it in the Application `onCreate()` method or later in an activity?

Hi IslamMohamady,

Thank you for the response

Yes, we have initialized Instabug SDK in the  Application `onCreate() `  and tried to change `InstabugInvocationEvent` later in the Activity class.

**Comment by mzelzoghbi** [comment]
Hi @muralijoyn , From the snippet shared earlier in the thread, we can see that building the SDK is done in the Activity not in the App class as mentioned, can you please send a sample app with the integration code that cause the issue to get this resolved quickly? 🙏🏻 

You can also use our public app on this repo to speed up replicating the issue. 

Thank you 🙏🏻

**Comment by muralijoyn** [comment]
@mzelzoghbi, Thank you for the response, Sure I will share the test code base.

**Comment by muralijoyn** [comment]
@mzelzoghbi here is the source code,  please replace the api key 

**strings.xml**
```
<string name="instabug_beta_id">enter_your_key_here</string>
```

https://drive.google.com/file/d/11JP-cKkfUZ7PJN1sO643l7cdQTyVnUqT/view?usp=sharing

**Comment by IslamMohamady** [comment]
Hi @muralijoyn 
Please find below a sample project with the correct integration.  
I will close the ticket and if you have any inquiry or update, You can reopen it 🙏🏻 
[InstabugTest.zip](https://github.com/Instabug/Instabug-Android/files/9969504/InstabugTest.zip)

**Comment by muralijoyn** [comment]
@IslamMohamady Thank you for code snippet.

But actually we don't want to disable Instabug completely, we just want to disable SHAKE functionality without restarting an app. So user can report a problem manually from app.


```
fun enable(enable: Boolean) {
        isEnabled = enable
        if (enable) {
            Instabug.enable()                                    
            BugReporting.setInvocationEvents(
                InstabugInvocationEvent.SHAKE,
                InstabugInvocationEvent.FLOATING_BUTTON
            )
        } else {
            BugReporting.setInvocationEvents(InstabugInvocationEvent.NONE)
            Instabug.disable()                // <<<<<<<< This will disable Instabug completely. 
        }
    }
```

And we have already tried the code you suggested, but as I mentioned it will disable Instabug completely.

**Comment by IslamMohamady** [comment]
@muralijoyn Thanks for clarifying the use case

You can just call 
```
 BugReporting.setInvocationEvents(InstabugInvocationEvent.NONE)
```
to disable shake detection

**Comment by muralijoyn** [comment]
Thank you @IslamMohamady for the suggestions, It is working fine now.  🙏🏻
