### ISSUE TITLE
Instabug gradle android doesnt work properly.

### ISSUE THREAD

**Issue by Wridho788** [Instabug/Instabug-Android#446]
i tried using 
`APM.setFragmentSpansEnabled(true)`
and added
method
`Instabug {
    APM {
        fragmentSpansEnabled true
    }
}`
in build.gradle and I don't know whether to put it in build.gradle (app) or build.gradle (project)

**Comment by IslamMohamady** [comment]
Hi @Wridho788 

You need to add 
```
classpath "com.instabug.library:instabug-plugin:11.7.0"
```
in your project build.gradle > buildscript > dependencies clause 

Then add 
```
apply plugin: 'instabug-apm'
``` 
to your application build.gradle
And 
```
Instabug { APM { fragmentSpansEnabled true } }
```
Needs to be added also in the application build.gradle

**Comment by Wridho788** [comment]
I've added a classpath, apply the plugin exactly as you said, But what for fragments in Android Apps never displays the results of apm

**Comment by Wridho788** [comment]
`
Instabug { 
  APM {
              fragmentSpansEnabled true 
  }
 }
`
for this method I don't know where to put it in the method line.
I've put the method in build.gradle :app, but after I synced the gradle, I got this error so I can't build gradle.
`
No signature of method: build_3eyv4ig9d99caqujngq3ed2yf.android() is applicable for argument types: (build_3eyv4ig9d99caqujngq3ed2yf$_run_closure1) values: [build_3eyv4ig9d99caqujngq3ed2yf$_run_closure1@6ac9c7a4]`

**Comment by IslamMohamady** [comment]
I will be closing this issue as we have an ongoing discussion on intercom
