### ISSUE TITLE
All the values of setUserAttribute is not sent in the report

### ISSUE THREAD

**Issue by snehas13** [Instabug/Instabug-Android#448]
**Expected Behavior**
When we submit the report to instabug using interface Instabug.onReportSubmitHandler, both sessionId and UserExternalId values should be sent in the report.
report.setUserAttribute("UserExternalId", userExternalId)
report.setUserAttribute("sessionId", UserInfo.sessionId)

**Actual Behavior**
In the Instabug report only UserExternalId is sent and sessionId value is not sent.

**Instabug version used**
11.5.2

**Android Version**
OS Level 33

**Device Model**
samsung SM-G996U

**Comment by IslamMohamady** [comment]
Hi @snehas13
Thank you for reporting this. I will check it on my side and get back to you ASAP 🙏🏻

**Comment by IslamMohamady** [comment]
@snehas13 I just checked it. And it is working as expected. My recommendation is to update to the latest SDK version and try again.
If the issue persists, I would recommend that you share a sample app with your integration 

I will close the issue but feel free to open it
