### ISSUE TITLE
Missing translation for Norwegian, Slovenian, Greek and Croatian

### ISSUE THREAD

**Issue by MarekMacko** [Instabug/Instabug-Android#450]
### Steps to Reproduce the Problem
1. Change system language to Norwegian / Slovenian / Greek / Croatian.
2. Call one of the below command: 
   - `BugReporting.show(BugReporting.ReportType.FEEDBACK)`,
   - `BugReporting.show(BugReporting.ReportType.BUG)`.

### Expected Behavior
Texts on `FEEDBACK` and `BUG` screen should be translated to Norwegian / Slovenian / Greek / Croatian.

### Actual Behavior
Texts on `FEEDBACK` and `BUG` screen are translated to English.

### Instabug integration code
```
Instabug.Builder(application, "token", InstabugInvocationEvent.SHAKE).build()
BugReporting.setReportTypes(BugReporting.ReportType.FEEDBACK, BugReporting.ReportType.BUG)
```
### SDK Version
`11.6.0`, `11.8.0`
### Android Version
`10`,`11`,`12`,13`
### Device Model
- Samsung Galaxy s10,
- Xiaomi Mi 10

### Instabug SDK resources 
![image](https://user-images.githubusercontent.com/12697488/218097224-c3bec4e2-322b-447b-a92a-106546ec3f07.png)

**Comment by IslamMohamady** [comment]
Hi @MarekMacko 
Currently, we don't support these locales. If you want us to do so, Please email us at [contactus@instabug.com](mailto:contactus@instabug.com) with all the details
