### ISSUE TITLE
minSdkVersion for using App Performance Monitoring feature?

### ISSUE THREAD

**Issue by Orbyt** [Instabug/Instabug-Android#453]
Company was interested in introducing the App Performance Monitoring feature. What is the `minSdkVersion` required to use that feature?

The [documentation](https://docs.instabug.com/docs/android-apm) notes the following:

> Min Required SDK Version
> APM is supported starting Android SDK version 10.0.0.

Android 10.0 is equal to API level 29. Is the `minSdkVersion` to use "APM" really 29? That seems very high, so hoping someone can verify whether or not that minimum version is actually required or if the documentation is incorrect.

**Comment by MohamedHefny** [comment]
Hello @Orbyt thanks for reaching out,
The min required SDK version in our documentation referring to the Instabug SDK version and not the android SDK. So, APM and Instabug SDK are supporting Android back to versions 4.0 (API level 14) and above.

**Comment by Orbyt** [comment]
@MohamedHefny That makes sense, thank you!
