### ISSUE TITLE
Memory leaking in Instabug library class

### ISSUE THREAD

**Issue by shyamkumarm** [Instabug/Instabug-Android#457]
Added the leak canary log given below,

Instabug android lib version: "11.10.0"

HEAP ANALYSIS RESULT
 ====================================
 1 APPLICATION LEAKS
 
 References underlined with "~~~" are likely causes.
 Learn more at https://squ.re/leaks.
 
 709136 bytes retained by leaking objects
 Signature: bdf4f1db7c488b7befdb0bf860958ee920b04962
 ┬───
 │ GC Root: Thread object
 │
 ├─ Tt instance
 │ Leaking: NO (PathClassLoader↓ is not leaking)
 │ Thread name: 'CleanupReference'
 │ ↓ Thread.contextClassLoader
 ├─ dalvik.system.PathClassLoader instance
 │ Leaking: NO (f↓ is not leaking and A ClassLoader is never leaking)
 │ ↓ ClassLoader.runtimeInternalObjects
 ├─ java.lang.Object[] array
 │ Leaking: NO (f↓ is not leaking)
 │ ↓ Object[5121]
 ├─ com.instabug.library.screenshot.f class
 │ Leaking: NO (a class is never leaking)
 │ ↓ static f.c
 │ ~
 ├─ com.instabug.library.screenshot.f instance
 │ Leaking: UNKNOWN
 │ Retaining 709.2 kB in 14097 objects
 │ ↓ f.a
 │ ~
 ├─ com.instabug.library.screenshot.d instance
 │ Leaking: UNKNOWN
 │ Retaining 709.2 kB in 14096 objects
 │ ↓ d.a
 │ ~
 ├─ com.instabug.library.screenshot.e instance
 │ Leaking: UNKNOWN
 │ Retaining 709.2 kB in 14095 objects
 │ ↓ e.a
 │ ~
 ├─ com.instabug.library.core.InitialScreenshotHelper$a instance
 │ Leaking: UNKNOWN
 │ Retaining 709.2 kB in 14094 objects
 │ a instance of com.ui.MainActivity with mDestroyed = true
 │ ↓ InitialScreenshotHelper$a.a
 │ ~
 ╰→ com.ui.MainActivity instance
 ​ Leaking: YES (ObjectWatcher was watching this because com.ui.MainActivity received
 ​ Activity#onDestroy() callback and Activity#mDestroyed is true)
 ​ Retaining 709.1 kB in 14092 objects
 ​ key = 1895db29-63d7-4473-a009-9625ccbb9169
 ​ watchDurationMillis = 5593
 ​ retainedDurationMillis = 588
 ​ mApplication instance of com.app.MainApplication
 ​ mBase instance of androidx.appcompat.view.ContextThemeWrapper
 ====================================
 0 LIBRARY LEAKS
 
 **A Library Leak is a leak caused by a known bug in 3rd party code that you do not have control over.**
 See https://square.github.io/leakcanary/fundamentals-how-leakcanary-works/#4-categorizing-leaks

**Comment by yaraabdelhakiim** [comment]
Hi @shyamkumarm thanks for reaching out. Would you please provide the steps to reproduce this or reproduce it in a sample app and share it ?

**Comment by yaraabdelhakiim** [comment]
@shyamkumarm Thank you for providing the steps, the fix for this leak will be included in our next release
