### ISSUE TITLE
Hide private views in Jetpack compose , although inside fragments

### ISSUE THREAD

**Issue by AndreiAvram123** [Instabug/Instabug-Android#459]
Hi,
We are trying to convert our app from the old view system to the new Jetpack compose. As the app is quite complex, we decided to use fragments alongside Compose. This way we can use the already made navigation architecture alongside Compose. 
The screen is built in Compose and set inside the fragment `onCreateView()`

```
  override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        super.onCreateView(inflater, container, savedInstanceState)
        return ComposeView(requireContext()).apply {
            setViewCompositionStrategy(ViewCompositionStrategy.DisposeOnViewTreeLifecycleDestroyed)
            setContent {
                //all the compose UI 
            }
        }
    }

```

However, one requirements on some particular screens is to hide specific views which might have sensitive data. Is there any way of achieving this in the current situation of using a fragment and the UI itself being build in Compose ?

**Comment by kareem-waleed** [comment]
@AndreiAvram123 Hello 👋 
Unfortunately, private views are not currently supported for Composables. 
However, it's one of our top priorities to provide private views and auto masking support for Jetpack Compose. So, stay tuned for our upcoming updates 🙏 
I'll close this ticket now, please feel free to re-open it if you have other questions 🙏
