### ISSUE TITLE
NPE in call to getWifiSSID() in com.instabug.library.util.DeviceStateProvider.getWifiSSID (DeviceStateProvider.java:5)

### ISSUE THREAD

**Issue by cedmart1decath** [Instabug/Instabug-Android#460]
We are noticing a Firebase Crashlytics log that shows instabug lib is crashing our app

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'android.net.wifi.WifiInfo android.net.wifi.WifiManager.getConnectionInfo()' on a null object reference

com.instabug.library.util.DeviceStateProvider.getWifiSSID (DeviceStateProvider.java:5)

Steps : ?
Actual Behavior => App do not crash

Impl:  
```
new Instabug.Builder(this, instabugToken).build();
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
BugReporting.setReportTypes(BugReporting.ReportType.BUG, BugReporting.ReportType.FEEDBACK);
```
SDK Version : 10.5.0
Android Version : 9
Device Model : Huawei Y6S

**Comment by Bashayer-reda** [comment]
Hello @cedmart1decath , Thank you so much for reaching out. I recommend updating the Instabug version to our latest SDK version[v12.6.0], as we are no longer using this method
