### ISSUE TITLE
Lint warnings in AGP 8.3.0

### ISSUE THREAD

**Issue by ZOlbrys** [Instabug/Instabug-Android#470]
### Steps to Reproduce the Problem
1. Add Instabug to App
2. Run `lint` command, i.e. `gradlew lintDebug`

### Expected Behavior
No lint warnings are reported

### Actual Behavior
2 lint warnings are reported, both of the same type:
```
Correctness	SelectedPhotoAccess	Normal
Behavior change when requesting photo library access Your app is currently not handling Selected Photos Access introduced in Android 14+ Selected Photo Access is a new ability for users to share partial access to their photo library when apps request access to their device storage on Android 14+. Instead of letting the system manage the selection lifecycle, we recommend you adapt your app to handle partial access to the photo library.
```

found at
`../../../.gradle/caches/transforms-3/99bc51d941512f3ed96e040d2d64b529/transformed/instabug-core-12.7.1
AndroidManifest.xml`

lines 13 and 14

<img width="928" alt="Screenshot 2024-02-17 at 00 11 35" src="https://github.com/Instabug/Instabug-Android/assets/2875924/4992d83f-e3af-4502-9052-3f5f4d94d571">

### Instabug integration code
```
implementation(libs.instabug)
...
instabug = { module = "com.instabug.library:instabug", version.ref = "instabug" }
```

### SDK Version
12.7.1

### Android Version
This started showing up in AGP 8.3.0 as far as I can tell.

### Device Model
N/A

### [Optional] Project That Reproduces the Issue
N/A

**Comment by Bashayer-reda** [comment]
Hello, @ZOlbrys Thank you so much for reaching out and reporting this issue. We want to inform you that we are working on this.

**Comment by ZOlbrys** [comment]
I updated my comment with more descriptive information - apologies if it was a bit ambiguous to start.

**Comment by ZOlbrys** [comment]
AGP 8.3.0 is now released and this issue is preventing my team from upgrading to it (since we have lint warning limits imposed).  Any updates on this?

**Comment by ZOlbrys** [comment]
Any update on this? I'd love to be able to get back to no lint warnings!

**Comment by marcorighini** [comment]
Updates on this?

**Comment by marcorighini** [comment]
It is currently a bigger issue at the moment because Google is now requesting additional information to apps that request this kind of permissions.
An ETA would be appreciated. 
Thanks!

**Comment by caseysd** [comment]
As per Google, all apps must comply to the Google Play's Photo and Video Permissions policy by October 31, 2024. 
https://support.google.com/googleplay/android-developer/answer/14115180?hl=en. As Instabug is not considered a core feature (probably for most apps utilizing Instabug), Google will not approve the use of `READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO` permissions.

> Hello, @ZOlbrys Thank you so much for reaching out and reporting this issue. We want to inform you that we are working on this.

We would really appreciate if there are some sort of updates as it's been more than 9 months. Thanks.

<h2 data-renderer-start-pos="385" style="margin-top: 1.8em; margin-right: ; margin-bottom: 0px; margin-left: ; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: ; font-variant-east-asian: ; font-variant-alternates: ; font-variant-position: ; font-weight: var(--ds-font-weight-medium, 500); font-stretch: ; font-size: 1.42857em; line-height: 1.2; font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: ; font-size-adjust: ; font-kerning: ; font-feature-settings: ; font-variation-settings: ; letter-spacing: -0.008em; color: rgb(23, 43, 77); text-transform: none; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgba(9, 30, 66, 0.06); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Timeline information</h2><p data-renderer-start-pos="407" style="margin-top: 0.75rem; margin-right: ; margin-bottom: 0px; margin-left: ; padding: 0px; font-size: 14px; line-height: 1.714; font-weight: 400; letter-spacing: -0.005em; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgba(9, 30, 66, 0.06); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">See the following timeline for the Photo and Video Permissions policy. Note that this is subject to change; updates will be posted in this article.</p><ul class="ak-ul" data-indent-level="1" style="margin: var(--ds-space-150, 12px) 0 0 0; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: var(--ed--list--item-counter--padding, 24px); box-sizing: border-box; list-style-type: disc; display: flow-root; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgba(9, 30, 66, 0.06); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li><p data-renderer-start-pos="558" style="margin-top: 0px; margin-right: ; margin-bottom: 0px; margin-left: ; padding: 0px; font-size: 1em; line-height: 1.714; font-weight: normal; letter-spacing: -0.005em;"><strong data-renderer-mark="true">October 28, 2023:</strong> We announced the Photos and Video Permissions policy.</p></li><li style="margin-top: var(--ds-space-050, 4px);"><p data-renderer-start-pos="633" style="margin-top: 0px; margin-right: ; margin-bottom: 0px; margin-left: ; padding: 0px; font-size: 1em; line-height: 1.714; font-weight: normal; letter-spacing: -0.005em;"><strong data-renderer-mark="true">September 18, 2024 – October 31, 2024:</strong> Developers with apps that carry <code class="code css-1o5d2cw" data-renderer-mark="true" style="font-family: SFMono-Medium, &quot;SF Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Roboto Mono&quot;, &quot;Ubuntu Mono&quot;, Menlo, Consolas, Courier, monospace; font-size: 0.875em; font-weight: normal; background-color: var(--ds--code--bg-color,var(--ds-background-neutral, #F4F5F7)); color: var(--ds-text, #172B4D); border-style: none; border-radius: var(--ds-border-radius, 3px); display: inline; padding: 2px 0.5ch; -webkit-box-decoration-break: clone; overflow: auto; overflow-wrap: break-word; white-space: pre-wrap; border-top-color: ; border-top-width: ; border-right-color: ; border-right-width: ; border-bottom-color: ; border-bottom-width: ; border-left-color: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: 1.33333; --ds--code--bg-color: var(--ds-background-neutral, rgba(9, 30, 66, 0.08));">READ_MEDIA_IMAGES</code> and <code class="code css-1o5d2cw" data-renderer-mark="true" style="font-family: SFMono-Medium, &quot;SF Mono&quot;, &quot;Segoe UI Mono&quot;, &quot;Roboto Mono&quot;, &quot;Ubuntu Mono&quot;, Menlo, Consolas, Courier, monospace; font-size: 0.875em; font-weight: normal; background-color: var(--ds--code--bg-color,var(--ds-background-neutral, #F4F5F7)); color: var(--ds-text, #172B4D); border-style: none; border-radius: var(--ds-border-radius, 3px); display: inline; padding: 2px 0.5ch; -webkit-box-decoration-break: clone; overflow: auto; overflow-wrap: break-word; white-space: pre-wrap; border-top-color: ; border-top-width: ; border-right-color: ; border-right-width: ; border-bottom-color: ; border-bottom-width: ; border-left-color: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: 1.33333; --ds--code--bg-color: var(--ds-background-neutral, rgba(9, 30, 66, 0.08));">READ_MEDIA_VIDEO</code> permissions are prompted in Play Console to either submit a declaration form to qualify for core use/broad access or remove permissions (if one time/infrequent use case). Different actions are required for one time/infrequent use cases and core use/broad access use cases:</p></li></ul><div class="pm-table-container " data-layout="default" style="margin: 0 auto var(--ds-space-200, 16px); padding: 0px; position: relative; box-sizing: border-box; clear: both; z-index: 0; transition: 0.1s linear; display: flex; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgba(9, 30, 66, 0.06); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: inherit;"><div class="pm-table-wrapper" style="margin: 0px; padding: 0px; overflow-x: auto;">
One time/infrequent use case | Core use/broad access use case
-- | --
Apps with one-time or infrequent use of photos are requested to remove READ_MEDIA_IMAGES and  READ_MEDIA_VIDEO permissions from their app manifest and migrate to a system photo picker if necessary. | Apps are only permitted to continue using broad access permissions if they have submitted a declaration and have been approved for usage.

</div></div><ul class="ak-ul" data-indent-level="1" style="margin: var(--ds-space-150, 12px) 0 0 0; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: var(--ed--list--item-counter--padding, 24px); box-sizing: border-box; list-style-type: disc; display: flow-root; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-wrap; background-color: rgba(9, 30, 66, 0.06); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li><p data-renderer-start-pos="1435" style="margin-top: 0px; margin-right: ; margin-bottom: 0px; margin-left: ; padding: 0px; font-size: 1em; line-height: 1.714; font-weight: normal; letter-spacing: -0.005em;"><strong data-renderer-mark="true">September 18, 2024:</strong> A self-service option to request an extension will become available in Play Console, extending the compliance deadline to January 22, 2025.</p></li><li style="margin-top: var(--ds-space-050, 4px);"><p data-renderer-start-pos="1598" style="margin-top: 0px; margin-right: ; margin-bottom: 0px; margin-left: ; padding: 0px; font-size: 1em; line-height: 1.714; font-weight: normal; letter-spacing: -0.005em;"><strong data-renderer-mark="true">October 31, 2024:</strong> Developers are required to submit declaration forms. Note the following:</p><ul class="ak-ul" data-indent-level="2" style="margin-top: var(--ds-space-050, 4px); margin-right: ; margin-bottom: 0px; margin-left: ; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: var(--ed--list--item-counter--padding, 24px); box-sizing: border-box; list-style-type: circle; display: flow-root;"><li><p data-renderer-start-pos="1692" style="margin-top: 0px; margin-right: ; margin-bottom: 0px; margin-left: ; padding: 0px; font-size: 1em; line-height: 1.714; font-weight: normal; letter-spacing: -0.005em;">Developers who have failed to submit a completed declaration form by this date updates will be blocked from updating their app.</p></li><li style="margin-top: var(--ds-space-050, 4px);"><p data-renderer-start-pos="1823" style="margin-top: 0px; margin-right: ; margin-bottom: 0px; margin-left: ; padding: 0px; font-size: 1em; line-height: 1.714; font-weight: normal; letter-spacing: -0.005em;">Developers who have requested an extension will have until January 22, 2025 to submit their completed declaration form.</p></li></ul></li><li style="margin-top: var(--ds-space-050, 4px);"><p data-renderer-start-pos="1948" style="margin-top: 0px; margin-right: ; margin-bottom: 0px; margin-left: ; padding: 0px; font-size: 1em; line-height: 1.714; font-weight: normal; letter-spacing: -0.005em;"><strong data-renderer-mark="true">January 22, 2025:</strong> Full policy compliance is mandatory for all developers, including those who requested an extension. After this date, all apps are subject to removal from Google Play if not compliant.</p></li></ul>

**Comment by samermeqdad** [comment]
Is there any update on this issue @Bashayer-reda? We will be forced to discontinue using this sdk if the issue is not addressed.

**Comment by Bashayer-reda** [comment]
hello @samermeqdad Thank you so much for reaching out. We want to inform you that we are working on this, and the fix will be shipped very soon

**Comment by ZOlbrys** [comment]
I have confirmed that https://github.com/Instabug/Instabug-Android/releases/tag/v14.0.0 contains no lint warnings.  I will close this out accordingly.
