### ISSUE TITLE
FOREGROUND_SERVICE_MEDIA_PROJECTION permission on SDK 34

### ISSUE THREAD

**Issue by leethree** [Instabug/Instabug-Android#475]
### Steps to Reproduce the Problem

We recently updated our `targetSdkVersion` to 34. Now we run into this dialog when we try to submit the app on Google Play Console.

![image](https://github.com/Instabug/Instabug-Android/assets/648142/034b7269-b08d-4f75-a9e0-6c5942744ca4)

I found out this permission is used by `instabug-core` and there's no description as to why it's used and what we should say to Google to get the app submitted.

Why is this permission used? Can we removed it?

### Expected Behavior

N/A

### Actual Behavior

N/A

### Instabug integration code

This is part of Instabug SDK:

```xml
        <service
            android:name="com.instabug.library.internal.video.ScreenRecordingService"
            android:enabled="true"
            android:exported="false"
            android:foregroundServiceType="mediaProjection"
            tools:targetApi="q" />
        <service
            android:name="com.instabug.library.screenshot.ScreenshotCaptureService"
            android:enabled="true"
            android:exported="false"
            android:foregroundServiceType="mediaProjection"
            tools:targetApi="q" />
```

### SDK Version
12.6.0

### Android Version
34

**Comment by IslamMohamady** [comment]
Hi @leethree 
Please contact us at [contactus@instabug.com](mailto:contactus@instabug.com) to help you with the issue. I will close it for now and feel free to re-open it whenever you feel the urge to.

**Comment by nicolasWenia** [comment]
We're having the same issue, the Play Store is complaining about this permission. What should we tell them in that case?

**Comment by SirJalias** [comment]
Why is this issue closed? there is no documentation about it and  it is a real issue , My team spent more than 2 hours to trying to understand what was going on with this same issue

**Comment by leethree** [comment]
I made a recording of the bug reporting flow and screen recording, and submitted the video to Google Play as required by them.

However it's still worth Instabug to take a look at this issue because this does not sounds like the permission we should be requesting. According to Google "You can only use this permission if your app performs tasks noticeable to the user when they're not directly interacting with your app."
