### ISSUE TITLE
"Take a screen recording" option missing after migrating to 13.1.0

### ISSUE THREAD

**Issue by algrid** [Instabug/Instabug-Android#479]
After we migrated from 12.6.0 to 13.1.0 the "Take a screen recording" option is missing from the bug reporting screen.
Was it removed or something is broken in the new version? Testing it on Android 14.

**Comment by lucasroca** [comment]
I'm using the React Native wrapper and I'm having the same issue. @algrid have you found a solution to it?

**Comment by IslamMohamady** [comment]
Hi @algrid & @lucasroca 👋🏻 
To enable that option again in your application, You need to add the following permission to your app's `AndroidManifest.xml` file
```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION"/>

**Comment by IslamMohamady** [comment]
@lucasroca Always happy to help. I will close the issue for now 🙏🏻
