### ISSUE TITLE
Disabling screenshot for "Suggest an Improvement"

### ISSUE THREAD

**Issue by vasilenastas** [Instabug/Instabug-Android#75]
Hello,

Wanted to ask if we can for "Suggest an Improvement" option disable the screenshot while we call simply `Instabug.invoke()` ? (Just for this option). I checked the configuration and seems it adds it automatically all the time (`instabug:4.3.3`). Also tried to use `setWillSkipScreenshotAnnotation(true)`, but unfortunately it didn't worked.

`            new Instabug.Builder(this, BuildConfig.INSTABUG_KEY)
                .setInvocationEvent(InstabugInvocationEvent.SHAKE)
                .build();
            
            Instabug.setWillSkipScreenshotAnnotation(true);
            Instabug.setShakingThreshold(600);
            Instabug.setIntroMessageEnabled(false);`

Any ideas ?

**Comment by Korazy** [comment]
Hey @vasilenastas 

You can disable it using the API found [here](https://docs.instabug.com/v1.0/docs/android-attachments#section-instabug-attachments).
