### ISSUE TITLE
Android Webview Screenshot black

### ISSUE THREAD

**Issue by nirajan-thapa** [Instabug/Instabug-Android#81]
**Issue**
Capturing screenshot of a webview displaying ThreeJS animation results in an empty screen.

**Steps to Reproduce**
* Download the test project. https://github.com/nirajan-thapa/InstaBug-Screenshot
* Replace the API Key in `MyApp.java`
* Shake the device to capture a screenshot

![Actual Screenshot](https://user-images.githubusercontent.com/29066315/37676425-49378d7e-2c4e-11e8-9d8b-b67712f0f8e6.png)

**Comment by Korazy** [comment]
Hey @nirajan-thapa, thanks for reporting this. We will be checking it from our side and getting back to you!

**Comment by nirajan-thapa** [comment]
Hi @Korazy, thank you for such a prompt response.

There are a few other variations involved with this issue, such as sometimes screenshot image coming up entirely black when there's more stuff involved with regards to ThreeJS animation.

While you are looking into this usecase, I will try to set up another html page that will reflect the other scenarios.
If you need any additional information regarding the issue, please, do let me know.

**Comment by Korazy** [comment]
After checking your application, it seems that you’re adding a hardware layer which won’t be capturable by Instabug. We can only capture the software layer.

**Comment by fordhurley** [comment]
Thanks, @Korazy. To clarify, do you mean that Instabug won't be able to capture WebGL at all? If so, we may have a workaround but it doesn't seem fully reliable. We'll prepare another demo application that shows the workaround and the problems we ran into with it. Hopefully you can provide some guidance.

**Comment by nirajan-thapa** [comment]
Hi @Korazy 
As a follow up to our earlier discussions, we made a slight modification to the html file, and as a result, now you are not able to see any views being captured in the screenshot. The entire screen appears black.
I am attaching a screenshot of this result.
![capture _2018-03-27-16-56-18](https://user-images.githubusercontent.com/29066315/37994647-2f8d3ed6-31e0-11e8-826b-ef24135b4a32.png)

The commit that reflects the above mentioned changes in my test repo
https://github.com/nirajan-thapa/InstaBug-Screenshot/commit/ee390854170db2b5f9a1eff703a11c2d1ae48547

I would really appreciate some feedback on how to go about tackling this issue.

**Comment by Korazy** [comment]
Hey all,

Apologies for the incredibly delayed response! We're currently working on allowing the SDK to take screenshots of hardware accelerated features. While it's not quite ready for release as of yet, we're expecting to release it very soon.

We'll update this issue once it is :)
