### ISSUE TITLE
RxJava 1 has reached EOL

### ISSUE THREAD

**Issue by eygraber** [Instabug/Instabug-Android#88]
Please update to RxJava 2 and stop polluting my project with your outdated transitive dependencies, or I will tell my PMs that we will need a new solution, because we will drop yours.

**Comment by ZiadAyman** [comment]
Hey @eygraber 
Apologies for the late reply on this! 

We are going to migrate to rxjava 2 very soon. We are having this as a priority here. I will let you know here once everything is in place 👍

**Comment by knobtviker** [comment]
I just examined some SNAPSHOTs and even the latest 5.0.0 is using RxJava1.

I dug up some issue here saying that 4.0.0-SNAPSHOT is using RxJava2.
Is there anything newer than that?

Also, I don't mind testing RxJava2 release. For now, I'm stuck on 4.0.0-SNAPSHOT.
Please keep me in the loop about this change.

**Comment by Korazy** [comment]
Hey @knobtviker @eygraber 

I just wanted to let you know that the latest release is currently on RxJava 2. Feel free to reach out if you have any questions :)
