### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by armen301** [Instabug/Instabug-Android#99]
`hideClipTrayIfNeeded() TextView is focused!! hideClipTray()`
	`at java.lang.Thread.run(Thread.java:761)`
 	`at com.instabug.bug.d$1.run(LiveBugManager.java:132)`
 	`at com.instabug.bug.d.b(LiveBugManager.java:38)`
 	`at com.instabug.bug.d.d(LiveBugManager.java:192)`
	`at com.instabug.library.util.BitmapUtils.compressBitmapAndSave(BitmapUtils.java:94)`
 	`at java.io.FileInputStream.(FileInputStream.java:146)`
	`at java.io.FileInputStream.open(Native Method)`
` java.io.FileNotFoundException: file_path/bug_1528984450413_.jpg (No such file or directory)`

**Comment by Korazy** [comment]
Hey @armen301 

Thanks for reaching out. Can you please tell me which SDK version you're currently on?

**Comment by chnouman** [comment]
We are getting same issue on tagetSdk 27

> 1528914722463  W/System.err(15975): java.io.FileNotFoundException: /storage/emulated/0/Android/data/package/files/instabug/attachments/bug_1528914641469_.jpg (No such file or directory)
> 
> 1528914722463  W/System.err(15975): 	at java.io.FileInputStream.open0(Native Method)
> 
> 1528914722463  W/System.err(15975): 	at java.io.FileInputStream.open(FileInputStream.java:200)
> 
> 1528914722463  W/System.err(15975): 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
> 
> 1528914722463  W/System.err(15975): 	at com.instabug.library.util.BitmapUtils$1.run(BitmapUtils.java:111)
> 
> 1528914722463  W/System.err(15975): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
> 
> 1528914722464  W/System.err(15975): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
> 
> 1528914722464  W/System.err(15975): 	at com.instabug.library.util.threading.b$1.run(PriorityThreadFactory.java:28)
> 
> 1528914722464  W/System.err(15975): 	at java.lang.Thread.run(Thread.java:764)
>

**Comment by Korazy** [comment]
@chnouman can you please try `implementation 'com.instabug.library:instabug:4.15.3'` to be sure it downloads the latest version? As this crash should already be resolved in the latest version.

**Comment by chnouman** [comment]
@Korazy  ok let me use this.

**Comment by Korazy** [comment]
@chnouman please feel free to reopen this issue if you run into it again :)
